### ISSUE TITLE
侧边栏服装名称无法显示

### ISSUE THREAD

**Issue by Clara174** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#1]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议

### 说说你看到的汉化文本内容？

导入原版存档后，侧边栏的服装名称无法显示
服装显示underfined
口罩显示$worn.face.cn_name_cup

![a8392bcbf6df8ea](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/142773540/d3503a7d-266c-4228-b567-0472d0a6f027)

**Comment by NumberSir** [comment]
旧存档兼容问题，重新买一件衣服就好
