### ISSUE TITLE
修理衣服问题

### ISSUE THREAD

**Issue by nagato19981008** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#10]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

版本为1.1，修理衣服打包装箱的时候钱够却提示钱不够

### 存档 / 代码

[degrees-of-lewdity-1-20230824-182022.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12428332/degrees-of-lewdity-1-20230824-182022.txt)

### 截图

![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/46072324/c3041379-42a9-4eb4-bbff-b73dc5cf567c)

**Comment by NumberSir** [comment]
原版游戏问题，已向作者反馈
