### ISSUE TITLE
学校上课，在历史课上选择与同学社交后历史课变成语文课

### ISSUE THREAD

**Issue by Aliceven** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#100]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

426的3.0.0版本，在下午上课点击社交出现的变课现象

### 存档 / 代码

[存档.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12832772/default.txt)

### 截图

![Screenshot_20231006_232119_com vrelnir DegreesOfLewdityWE](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/127491982/5b0b27ca-0685-4025-ae9e-05971e16d41d)
![Screenshot_20231006_232121_com vrelnir DegreesOfLewdityWE](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/127491982/5fc29e16-b6a0-4b5e-966e-b191f3d91d96)

### 还有别的吗？

无论是第一节不点击社交的话课不会变 但是只要点了社交就会原地变课

**Comment by NumberSir** [comment]
同 [@issue/99](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/issues/99)，已修复。

**Comment by zmh007007** [comment]
求修复大佬，叫悉尼摘掉贞操锁的时候有bug
![Screenshot_20231007_185008_com vrelnir DegreesOfLewdityWE](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/147246779/89203e53-a1cd-4b73-9eef-625fa5d28c1e)
