### ISSUE TITLE
神庙宿舍诱惑男孩事件出错

### ISSUE THREAD

**Issue by Cambarila** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#101]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

最新3.0.1中在神庙诱惑男孩检查通过后出现报错

### 存档 / 代码

[degrees-of-lewdity-20231007-011400.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12833735/degrees-of-lewdity-20231007-011400.txt)

### 截图

![8F9`EQF312TB~_6VL{3~NN7](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/147189342/fe9e8b76-329c-47fa-aa54-10b3ace2d9de)

**Comment by Khaos423** [comment]
已修复，请等待新版本发布
