### ISSUE TITLE
神殿中接近长椅上的悉尼时报错

### ISSUE THREAD

**Issue by Tobba-13** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#102]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

0.4.2.6-chs-alpha3.0.1版本。
贞洁测验遭遇隔日再去神殿，悉尼在长椅上祈祷，点选接近悉尼后跳出报错。

### 存档 / 代码

[Export.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12835910/DOL.txt)

### 截图

![Screenshot_20231007-060303218](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/147212447/4ac7d7b9-f04a-4f52-a469-d93aa8ab1589)

**Comment by Khaos423** [comment]
需要距离报错更近的存档确认

**Comment by Tobba-13** [comment]
是指出现报错后存档再汇出吗？
是的话如附档
[Export2.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12837044/Export2.txt)

**Comment by Khaos423** [comment]
是指报错当时或者前一两步

**Comment by Tobba-13** [comment]
那这个档应该符合，跳出报错讯息后就前进不了了只能先存档。

**Comment by Khaos423** [comment]
已修，请等待新版本发布
