### ISSUE TITLE
森林商店男女水手服bug

### ISSUE THREAD

**Issue by shanmujiuya** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#103]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

直接卡住只能重启

### 存档 / 代码

[欲都孤儿.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12836669/default.txt)

### 截图

![Screenshot_2023-10-07-11-05-17-45_7772ada461b89c699132e33396e4e395](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/146629759/1db96771-d49d-4936-80ea-d1bd03aadee8)
![Screenshot_2023-10-07-11-03-52-26_7772ada461b89c699132e33396e4e395](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/146629759/86cfeb6c-76d3-4b5b-8501-5d8dc4c5478d)

**Comment by Khaos423** [comment]
已修复，请等待新版本发布
