### ISSUE TITLE
应用详情与内版本不一致

### ISSUE THREAD

**Issue by shanmujiuya** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#104]
### 说说你遇到的问题？

![Screenshot_2023-10-07-17-37-48-32_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/146629759/2dc5681f-7287-4b4b-b74b-3e65c4903ba1)
![Screenshot_2023-10-07-17-37-59-47_7772ada461b89c699132e33396e4e395](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/146629759/a4f7b1b4-fe3c-45ea-ab4c-0f1473c81104)
不知道是不是bug，好奇是为什么

**Comment by HSSkyBoy** [comment]
這是APK打包錯誤
遊戲內核更新了，但是打包出來的APK的版本名和版本號並未更新，仍舊是之前的0.4.1.7和401
這個bug誰知道何時才能修復，這致使我每次更新都得自己重新打包:(

**Comment by HSSkyBoy** [comment]
不過它不會對遊戲本身產生影響，伱可以放心

**Comment by shanmujiuya** [comment]
> 不会对游戏本身产生影响，所以可以放心

感谢您的解答

**Comment by HSSkyBoy** [comment]
雖然這不會帶來影響，但我仍然認為需要修復，所以無需關閉

**Comment by NumberSir** [comment]
从下次汉化版发布起将基于[作者博客发布的安卓版本](https://vrelnir.blogspot.com/?zx=a843afdd9c310383)打包新的安卓版
