### ISSUE TITLE
建议将 Readme.me 中 Changelog 的更新方式改为按时间线倒序

### ISSUE THREAD

**Issue by mzji** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#105]
### 说说你遇到的问题？

建议将 Readme.me 中 Changelog 的更新方式改为按时间线倒序，也即越新的 change 越靠上，这样阅读新更动时较为容易，且有很多其他软件或文档的 changelog 也使用此一策略

**Comment by NumberSir** [comment]
已修改，将在下次更新汉化版时应用。
