### ISSUE TITLE
悉尼摘掉贞操锁的时候有bug

### ISSUE THREAD

**Issue by zmh007007** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#106]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

大佬悉尼摘掉贞操锁的时候有bug

### 存档 / 代码

[degrees-of-lewdity-2-20231007-182726.save.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12837666/degrees-of-lewdity-2-20231007-182726.save.txt)

### 截图

![Screenshot_20231007_185008_com vrelnir DegreesOfLewdityWE](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/147246779/882d0565-3223-4d38-990c-c9e4388e1d2f)

### 还有别的吗？

没有啦，感谢大佬

**Comment by NumberSir** [comment]
同 [@issue/102](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/issues/102)，已修复，请等待新版本发布。
