### ISSUE TITLE
跟悉尼在更衣室活动时的错误

### ISSUE THREAD

**Issue by Zeta1002** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#107]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

跟悉尼在更衣室活动时的错误
更：用了个作弊号重新將檔导出一下

### 存档 / 代码

[degrees-of-lewdity-20231008-084515.save.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12839509/degrees-of-lewdity-20231008-084515.save.txt)

### 截图

![Screenshot_20231008_084509_Chrome](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/133109262/3e325f32-e341-485f-8ee7-188c2b337d4b)

**Comment by NumberSir** [comment]
同 [@issue/101](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/issues/101)，已修复，请等待新版本发布。
