### ISSUE TITLE
去神殿找地衣時的文本異常

### ISSUE THREAD

**Issue by EndlessNull** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#108]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

網頁版的， 0.4.2.6-chs-alpha3.0.1 

### 存档 / 代码

[degrees-of-lewdity-20231007-224314.save.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12838076/degrees-of-lewdity-20231007-224314.save.txt)

### 截图

![圖片](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/34579128/cea51101-a4ea-459a-a074-8d2b1e7e0021)

**Comment by NumberSir** [comment]
同 [@issue/101](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/issues/101)，已修复，请等待新版本发布。
