### ISSUE TITLE
森林商店购买上衣时报错

### ISSUE THREAD

**Issue by Grizel4** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#109]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

会报错的上衣如下：
诘襟，水手服
版本是Degrees of Lewdity 0.4.2.6-chs-alpha3.0.1

### 存档 / 代码

[degrees-of-lewdity-Xander-20231008-032602.zip](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12838628/degrees-of-lewdity-Xander-20231008-032602.zip)

### 截图

![QQ图片20231008032732](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/147276659/2a459760-4db4-47c0-8877-401820200d2a)

**Comment by NumberSir** [comment]
同 [@issue/103](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/issues/103)，已修复，请等待新版本发布。
