### ISSUE TITLE
在科學課上的劇情，左右手寫錯了

### ISSUE THREAD

**Issue by EndlessNull** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#110]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

1. 「right hand」沒被翻譯
2. 下面的選項中出現2個左手

*這段劇情後面也還有數次類似的錯誤*

### 存档 / 代码

[degrees-of-lewdity-test-20231008-154455.save.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12840060/degrees-of-lewdity-test-20231008-154455.save.txt)

### 截图

![圖片](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/34579128/5ecbc4da-9c22-46ab-9df8-3d09de9b9e92)
![圖片](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/34579128/20b5a690-16a4-4304-87e6-d84945120b55)

**Comment by NumberSir** [comment]
已修复，请等待新版本发布。
