### ISSUE TITLE
存档在 0.4.2.0 之前之后的游戏中反复导入导致的报错

### ISSUE THREAD

**Issue by Neeeo26** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#111]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

點選闖入碼頭會跳出白色提示框，按確定後點按闖入碼頭沒有反應，無法進入碼頭但可以離開

### 存档 / 代码

[存檔碼.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12840181/default.txt)

### 截图

![IMG_1259](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/147305449/c55d91d0-520e-4855-9ccd-0be7eb3aeb1b)
![IMG_1260](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/147305449/c415988b-d314-420c-9f41-ae5e48480715)
![IMG_1266](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/147305449/ccdf523b-c0bc-468e-9c2c-2c639a467a72)

### 还有别的吗？

後續離開碼頭前往其他地方會跳出附圖紅色框提示
![IMG_1261](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/147305449/051bba0a-2700-46e4-8e14-260bb4322dae)
![IMG_1262](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/147305449/96410aba-d7f2-405b-b9be-3722c7c13c76)
![IMG_1265](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/147305449/901093ce-5b5f-4c0f-8c4b-ea5c5aaea2f6)

**Comment by NumberSir** [comment]
该 bug 是由于你先将存档导入了 0.4.2.0+ 的版本游玩，然后又将存档导入回 0.4.1.0+ 的版本游玩，然后又将存档导入了 0.4.2.0+ 的版本游玩导致的。

由于 0.4.2.0+ 之后更新了犯罪系统，因此在新旧版本间迁移存档会导致与犯罪相关的变量清空。

其中一种修复的方法是：

1. 先用电脑浏览器(如 Edge 或 Chrome 等可以通过 F12 打开控制台的浏览器)在新版本(指 0.4.2.0+ 的游戏版本，如当前的汉化版 alpha3.0.1)载入存档
2. 按 F12 打开控制台（如图）
3. 在空白处输入：
```
V.crime = {assault: {current: 0, history: 0, daily: 0, count: 0, countHistory: 0},coercion: {current: 0, history: 0, daily: 0, count: 0, countHistory: 0},destruction: {current: 0, history: 0, daily: 0, count: 0, countHistory: 0},exposure: {current: 0, history: 0, daily: 0, count: 0, countHistory: 0},obstruction: {current: 0, history: 0, daily: 0, count: 0, countHistory: 0},prostitution: {current: 0, history: 0, daily: 0, count: 0, countHistory: 0},resisting: {current: 0, history: 0, daily: 0, count: 0, countHistory: 0},thievery: {current: 0, history: 0, daily: 0, count: 0, countHistory: 0},petty: {current: 0, history: 0, daily: 0, count: 0, countHistory: 0},trespassing: {current: 0, history: 0, daily: 0, count: 0, countHistory: 0},events: {},}
```
并回车

4. 接着输入
```
V.crimehistory = 0
```
并回车

5. 然后可以修复该报错问题

**Comment by 1027109613** [comment]
![Screenshot_2023-10-18-15-37-48-330_com vrelnir DegreesOfLewdity](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/148332893/b2f40c90-ec73-4501-8262-4c31f3eec410)
![Screenshot_2023-10-18-15-44-48-026_com vrelnir DegreesOfLewdity](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/148332893/b4689ab0-537b-4786-b42a-b2a86b286884)
用美化包自带的作弊器清除转化以后就变成了这样，社交统计和作弊器的npc处都变成了乱码。

**Comment by 1027109613** [comment]
[存档码]( https://kdocs.cn/al/ckIX8q1ejwG5?f=203)

**Comment by Khaos423** [comment]
> [存档码](https://kdocs.cn/al/ckIX8q1ejwG5?f=203)

上面有解决步骤，我用你的存档试了可以解决

**Comment by 1027109613** [comment]
谢谢谢谢

**Comment by rouyi-Y** [comment]
有大佬能帮我看看吗？我是作弊界面全报错，用了上面的方法也没用，谢谢了。

**Comment by Khaos423** [comment]
> 有大佬能帮我看看吗？我是作弊界面全报错，用了上面的方法也没用，谢谢了。

没图没存档能无米之炊吗？

**Comment by rouyi-Y** [comment]
您好！您发送的邮件已收悉！

**Comment by rouyi-Y** [comment]
【金山文档】 存档码
https://kdocs.cn/l/civPc2frqMNd
刚刚卡出去了，以为没发出来，不好意思

**Comment by rouyi-Y** [comment]
![Screenshot_2023_1030_133838](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/149347091/16e499e2-18ec-431d-b7ce-40c859f78797)
![Screenshot_2023_1030_101524](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/149347091/53f41dd0-6522-44f0-881a-aaf96ee298d5)

**Comment by Khaos423** [comment]
> ![Screenshot_2023_1030_133838](https://user-images.githubusercontent.com/149347091/278949810-16e499e2-18ec-431d-b7ce-40c859f78797.png) ![Screenshot_2023_1030_101524](https://user-images.githubusercontent.com/149347091/278949819-53f41dd0-6522-44f0-881a-aaf96ee298d5.jpg)

这和本issue不是同一个问题啊，为什么不自己发个issue

**Comment by rouyi-Y** [comment]
感谢感谢

**Comment by Khaos423** [comment]
> 感谢感谢

你的问题都没解决咋感谢啊？请新开个issue便于跟进问题啊

**Comment by Khaos423** [comment]
> 感谢感谢

这个bug根本原因是原版程序。
你用作弊恢复口腔童贞或者在浏览器F12输入`V.player.virginity.oral=false` 就能解决

**Comment by SakuraDAshigure** [comment]
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/151490379/6416a6e6-aee1-48f9-88b3-d15200a6e828)
特质报错是否有办法修复呢？尝试本帖的方式后无法修复，求助！
[save.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13406202/save.txt)

**Comment by rouyi-Y** [comment]
您好！您发送的邮件已收悉！

**Comment by Khaos423** [comment]
> ![image](https://user-images.githubusercontent.com/151490379/284127635-6416a6e6-aee1-48f9-88b3-d15200a6e828.png) 特质报错是否有办法修复呢？尝试本帖的方式后无法修复，求助！ [save.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13406202/save.txt)

这个应该是类似的问题，存档横跳导致眼镜颜色出错，F12输入`V.leftEyeColour= V.eyeselect`和`V.rightEyeColour= V.eyeselect`即可解决问题
