### ISSUE TITLE
森林商店预览特定衣服报错

### ISSUE THREAD

**Issue by HotoCocoaco** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#112]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用 dol-0.4.2.6-chs-alpha3.0.1 安卓包
在森林商店点“水手服”或“诘襟”即会导致报错。
原存档使用DOL CHS MOD游玩，但是转移到此仓库的整合包仍有问题，暂时认为与美化包无关。

### 存档 / 代码

hi，这是我用百度网盘分享的内容~复制这段内容打开「百度网盘」APP即可获取 
链接:https://pan.baidu.com/s/1MWZC5kWc64PaOdoCHskqMw 
提取码:7114

### 截图

![Screenshot_2023-10-08-23-47-02-414_com vrelnir DegreesOfLewdityWE](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/42245579/d5d10832-42f5-41e1-98a9-2cc3daef5cee)
![Screenshot_2023-10-08-23-46-47-759_com vrelnir DegreesOfLewdityWE](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/42245579/bd7e9d50-feac-43c8-b629-5050f5813b82)

**Comment by NumberSir** [comment]
同 [@issue/103](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/issues/103)，已修复，请等待新版本发布。

**Comment by HotoCocoaco** [comment]
建议通过发布release时来关闭issue，提前关闭issue会让人以为已解决或意识不到此问题已被知悉。

> 同 [@issue/103](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/issues/103)，已修复，请等待新版本发布。

**Comment by NumberSir** [comment]
> 建议通过发布release时来关闭issue，提前关闭issue会让人以为已解决或意识不到此问题已被知悉。
> 
> > 同 [@issue/103](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/issues/103)，已修复，请等待新版本发布。

好的，以后已解决的问题会先标注为`已修复`，等新版本发布时才会关闭；重复问题会标注为`已修复`和`重复`并 `按非计划关闭`。
