### ISSUE TITLE
[0.4.2.7-chs-alpha4.0.0] 在公園的文本錯誤

### ISSUE THREAD

**Issue by EndlessNull** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#114]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

網頁版 0.4.2.7-chs-alpha4.0.0

### 存档 / 代码

[degrees-of-lewdity-test-20231009-110910.save.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12842442/degrees-of-lewdity-test-20231009-110910.save.txt)

### 截图

![圖片](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/34579128/3cdcfa82-abe1-45cb-9506-2e73a3deade7)

**Comment by NumberSir** [comment]
非汉化版bug，这是怎么触发的？需要更详细的步骤

**Comment by EndlessNull** [comment]
右手選擇引導他到我的屁股就有了

![圖片](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/34579128/b5bd5329-5d7c-405a-8a42-85da0408bcdc)

**Comment by NumberSir** [comment]
已向作者反馈
