### ISSUE TITLE
[0.4.2.7-chs-alpha4.0.0] 逃离巨大蛞蝓后文本位置问题

### ISSUE THREAD

**Issue by 4567569** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#119]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议

### 说说你看到的汉化文本内容？

![Screenshot_20231010_000127](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/146926422/cd43343a-4615-40f1-bc6c-bd21c759c594)
[存档.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12851953/default.txt)
逃离巨大蛞蝓后选择到达位置的页面出现数个位置混乱的“不要”文本。甚至选择选项下面还有文本。

### 有什么好的想法？

删除乱序的文本

### 其他内容

我不太确定这是否应该是哪种类型，但没有报错提示，因此我发在这里。

**Comment by NumberSir** [comment]
这是正常的游戏内容，这些“不要”是苍白幽灵说的。如果幽灵处于愤怒状态则会显示“溺死”。

**Comment by 4567569** [comment]
明白了，感谢解释。我还需要对这个issue做什么吗？比如删除或者关闭之类的？

**Comment by NumberSir** [comment]
> 明白了，感谢解释。我还需要对这个issue做什么吗？比如删除或者关闭之类的？

不用改动，如果有其他相同问题的玩家可以参考，更新新版本时会一并关闭。
