### ISSUE TITLE
镜子无法使用，无法切换发型，检查皮肤，化妆

### ISSUE THREAD

**Issue by w1847766036** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#12]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

无法使用镜子，切换发型，检查皮肤，化妆

### 存档 / 代码

[Uploading 存档1.txt…]()

### 截图

![Screenshot_2023-08-26-00-49-27-83_7772ada461b89c699132e33396e4e395](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/142893991/3107bb01-b402-4985-a261-883752d87068)

![网页版](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/142893991/fc92bfc1-cfdf-4602-aa52-1ac9a4e03b26)

![Screenshot_2023-08-26-00-56-54-73_7772ada461b89c699132e33396e4e395](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/142893991/bc2b2eb4-299b-47bf-bfd7-db88b15ea70f)

**Comment by w1847766036** [comment]
我不知道怎么上传存档，非常抱歉，好像点不开

**Comment by Eltirosto** [comment]
镜子问题已修，请等待新版本发布
