### ISSUE TITLE
[0.4.2.7-chs-alpha4.0.0] 运动判定成功率有误

### ISSUE THREAD

**Issue by bb7355608** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#120]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这既不是对游戏报错的反馈，也不是对汉化文本改进的建议

### 说说你遇到的问题？

在跟随狼群狩猎和爬树判定中，运动s，成功率只有10%
![Screenshot_20231011_151116](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/108703258/fe03e604-b6de-4bca-b4d1-0268eaa6341f)
![Screenshot_20231011_150233](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/108703258/1faf4e5a-aa61-4c43-a6f6-ded6c622fa9a)

**Comment by Khaos423** [comment]
信息不足，无法判断是否有问题，请提供存档

**Comment by bb7355608** [comment]
[degrees-of-lewdity-wolf-20231012-085835.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12877106/degrees-of-lewdity-wolf-20231012-085835.txt)

**Comment by NumberSir** [comment]
> 这是原代码中就有的function currentSkillValue()方法的bug，在判定运动技能时，穿着“崎岖”tag的鞋子会让运动技能变为1/10
> 
> ```
> case "athletics":
> 			if (["forest", "moor", "farm"].includes(V.location)) {
> 				if (V.worn.feet.type.includes("heels")) {
> 					result = Math.floor(result * (1 - V.worn.feet.reveal / 5000));
> 				}
> 				if (V.worn.feet.type.includes("rugged")) {
> 					result = Math.floor(result * (1 + currentSkillValue("feetskill", disableModifiers + 1)) / 10000);
> 				}
> 			}
> 			if (V.worn.feet.type.includes("shackle")) result /= 10;
> 			break;
> ```
> 
> ……话说这个应该反馈给作者吗？

这样啊，那就是正常的游戏内容了

**Comment by Khaos423** [comment]
> 这是原代码中就有的function currentSkillValue()方法的bug，在判定运动技能时，穿着“崎岖”tag的鞋子会让运动技能变为1/10
> 
> ```
> case "athletics":
> 			if (["forest", "moor", "farm"].includes(V.location)) {
> 				if (V.worn.feet.type.includes("heels")) {
> 					result = Math.floor(result * (1 - V.worn.feet.reveal / 5000));
> 				}
> 				if (V.worn.feet.type.includes("rugged")) {
> 					result = Math.floor(result * (1 + currentSkillValue("feetskill", disableModifiers + 1)) / 10000);
> 				}
> 			}
> 			if (V.worn.feet.type.includes("shackle")) result /= 10;
> 			break;
> ```
> 
> ……话说这个应该反馈给作者吗？

比起bug更像一种机制，感谢反馈

**Comment by bb7355608** [comment]
> > 这是原代码中就有的function currentSkillValue()方法的bug，在判定运动技能时，穿着“崎岖”tag的鞋子会让运动技能变为1/10
> > ```
> > case "athletics":
> > 			if (["forest", "moor", "farm"].includes(V.location)) {
> > 				if (V.worn.feet.type.includes("heels")) {
> > 					result = Math.floor(result * (1 - V.worn.feet.reveal / 5000));
> > 				}
> > 				if (V.worn.feet.type.includes("rugged")) {
> > 					result = Math.floor(result * (1 + currentSkillValue("feetskill", disableModifiers + 1)) / 10000);
> > 				}
> > 			}
> > 			if (V.worn.feet.type.includes("shackle")) result /= 10;
> > 			break;
> > ```
> > 
> > 
> > ……话说这个应该反馈给作者吗？
> 
> 这样啊，那就是正常的游戏内容了

啊？防滑鞋不应该是增加判定成功率吗，属性面板里还加了20%的运动呢

**Comment by Khaos423** [comment]
> > > 这是原代码中就有的function currentSkillValue()方法的bug，在判定运动技能时，穿着“崎岖”tag的鞋子会让运动技能变为1/10
> > > ```
> > > case "athletics":
> > > 			if (["forest", "moor", "farm"].includes(V.location)) {
> > > 				if (V.worn.feet.type.includes("heels")) {
> > > 					result = Math.floor(result * (1 - V.worn.feet.reveal / 5000));
> > > 				}
> > > 				if (V.worn.feet.type.includes("rugged")) {
> > > 					result = Math.floor(result * (1 + currentSkillValue("feetskill", disableModifiers + 1)) / 10000);
> > > 				}
> > > 			}
> > > 			if (V.worn.feet.type.includes("shackle")) result /= 10;
> > > 			break;
> > > ```
> > > 
> > > 
> > > ……话说这个应该反馈给作者吗？
> > 
> > 
> > 这样啊，那就是正常的游戏内容了
> 
> 啊？防滑鞋不应该是增加判定成功率吗，属性面板里还加了20%的运动呢

这不是比1大吗？确定是减吗？

**Comment by 3naka** [comment]
> > > > 这是原代码中就有的function currentSkillValue()方法的bug，在判定运动技能时，穿着“崎岖”tag的鞋子会让运动技能变为1/10
> > > > ```
> > > > case "athletics":
> > > > 			if (["forest", "moor", "farm"].includes(V.location)) {
> > > > 				if (V.worn.feet.type.includes("heels")) {
> > > > 					result = Math.floor(result * (1 - V.worn.feet.reveal / 5000));
> > > > 				}
> > > > 				if (V.worn.feet.type.includes("rugged")) {
> > > > 					result = Math.floor(result * (1 + currentSkillValue("feetskill", disableModifiers + 1)) / 10000);
> > > > 				}
> > > > 			}
> > > > 			if (V.worn.feet.type.includes("shackle")) result /= 10;
> > > > 			break;
> > > > ```
> > > > 
> > > > 
> > > > ……话说这个应该反馈给作者吗？
> > > 
> > > 
> > > 这样啊，那就是正常的游戏内容了
> > 
> > 
> > 啊？防滑鞋不应该是增加判定成功率吗，属性面板里还加了20%的运动呢
> 
> 确定是减吗？效果的代码和面板显示的数据代码大差不差啊

这代码搁原游戏里也是个bug，
正确的应该是result = Math.floor(result * (1 + currentSkillValue("feetskill", disableModifiers + 1)/ 10000) );
/10000的位置放错导致加成变成/10了

**Comment by bb7355608** [comment]
> > > > 这是原代码中就有的function currentSkillValue()方法的bug，在判定运动技能时，穿着“崎岖”tag的鞋子会让运动技能变为1/10
> > > > ```
> > > > case "athletics":
> > > > 			if (["forest", "moor", "farm"].includes(V.location)) {
> > > > 				if (V.worn.feet.type.includes("heels")) {
> > > > 					result = Math.floor(result * (1 - V.worn.feet.reveal / 5000));
> > > > 				}
> > > > 				if (V.worn.feet.type.includes("rugged")) {
> > > > 					result = Math.floor(result * (1 + currentSkillValue("feetskill", disableModifiers + 1)) / 10000);
> > > > 				}
> > > > 			}
> > > > 			if (V.worn.feet.type.includes("shackle")) result /= 10;
> > > > 			break;
> > > > ```
> > > > 
> > > > 
> > > > ……话说这个应该反馈给作者吗？
> > > 
> > > 
> > > 这样啊，那就是正常的游戏内容了
> > 
> > 
> > 啊？防滑鞋不应该是增加判定成功率吗，属性面板里还加了20%的运动呢
> 
> 确定是减吗？效果的代码和面板显示的数据代码大差不差啊

我截图里的PC运动等级S，成功率都只有10%

**Comment by Khaos423** [comment]
> > > > > 这是原代码中就有的function currentSkillValue()方法的bug，在判定运动技能时，穿着“崎岖”tag的鞋子会让运动技能变为1/10
> > > > > ```
> > > > > case "athletics":
> > > > > 			if (["forest", "moor", "farm"].includes(V.location)) {
> > > > > 				if (V.worn.feet.type.includes("heels")) {
> > > > > 					result = Math.floor(result * (1 - V.worn.feet.reveal / 5000));
> > > > > 				}
> > > > > 				if (V.worn.feet.type.includes("rugged")) {
> > > > > 					result = Math.floor(result * (1 + currentSkillValue("feetskill", disableModifiers + 1)) / 10000);
> > > > > 				}
> > > > > 			}
> > > > > 			if (V.worn.feet.type.includes("shackle")) result /= 10;
> > > > > 			break;
> > > > > ```
> > > > > 
> > > > > 
> > > > > ……话说这个应该反馈给作者吗？
> > > > 
> > > > 
> > > > 这样啊，那就是正常的游戏内容了
> > > 
> > > 
> > > 啊？防滑鞋不应该是增加判定成功率吗，属性面板里还加了20%的运动呢
> > 
> > 
> > 确定是减吗？效果的代码和面板显示的数据代码大差不差啊
> 
> 这代码搁原游戏里也是个bug， 正确的应该是result = Math.floor(result * (1 + currentSkillValue("feetskill", disableModifiers + 1)/ 10000) ); /10000的位置放错导致加成变成/10了


> > > > > 这是原代码中就有的function currentSkillValue()方法的bug，在判定运动技能时，穿着“崎岖”tag的鞋子会让运动技能变为1/10
> > > > > ```
> > > > > case "athletics":
> > > > > 			if (["forest", "moor", "farm"].includes(V.location)) {
> > > > > 				if (V.worn.feet.type.includes("heels")) {
> > > > > 					result = Math.floor(result * (1 - V.worn.feet.reveal / 5000));
> > > > > 				}
> > > > > 				if (V.worn.feet.type.includes("rugged")) {
> > > > > 					result = Math.floor(result * (1 + currentSkillValue("feetskill", disableModifiers + 1)) / 10000);
> > > > > 				}
> > > > > 			}
> > > > > 			if (V.worn.feet.type.includes("shackle")) result /= 10;
> > > > > 			break;
> > > > > ```
> > > > > 
> > > > > 
> > > > > ……话说这个应该反馈给作者吗？
> > > > 
> > > > 
> > > > 这样啊，那就是正常的游戏内容了
> > > 
> > > 
> > > 啊？防滑鞋不应该是增加判定成功率吗，属性面板里还加了20%的运动呢
> > 
> > 
> > 确定是减吗？效果的代码和面板显示的数据代码大差不差啊
> 
> 这代码搁原游戏里也是个bug， 正确的应该是result = Math.floor(result * (1 + currentSkillValue("feetskill", disableModifiers + 1)/ 10000) ); /10000的位置放错导致加成变成/10了

没看清，这个确实得向作者反馈，或者我去PR下
