### ISSUE TITLE
[0.4.2.7-chs-alpha4.0.0] 在森林裡和黃蜂的場景有報錯

### ISSUE THREAD

**Issue by EndlessNull** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#123]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

準確來說是在結束的那個地方

### 存档 / 代码

[degrees-of-lewdity-test-20231013-093453.save.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12888583/degrees-of-lewdity-test-20231013-093453.save.txt)

### 截图

![圖片](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/34579128/7ccb1ac4-9fcd-4041-ac08-4ad548eecf69)

**Comment by Khaos423** [comment]
初步判断是原版bug，如果存档载入原版的话会显示玩家抓住了0（玩家前面摸黄蜂，之后黄蜂在玩家高潮的时候飞走，导致部分变量未重置而依然输出抓住黄蜂的文本），而汉化版里0不是字符串导致replace出错。不过我还未在原版复现出来。

**Comment by NumberSir** [comment]
爆红是汉化的问题，而导致爆红的原因是原版游戏的问题，已向作者反馈。
