### ISSUE TITLE
仓库协议可能存在漏洞?\汉化的技术分享提议

### ISSUE THREAD

**Issue by 15x3** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#126]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这既不是对游戏报错的反馈，也不是对汉化文本改进的建议

### 1 CC协议可能无法保护软件产品

我完全理解汉化组对有人转商用的担心，这一旦转商用就不是侵权那么简单，而是涉嫌传播淫秽物品，但我认为这个问题的一部分根源与错误的开源协议有关，贴吧闹剧放大了这个问题。

CC协议是个文娱作品开源协议，**不是**软件产品开源协议，已经有过因为基于CC协议开发软件被闹上法庭的事情（具体案例请看“[开源许可证与CC许可证](https://zhuanlan.zhihu.com/p/115911178)”），这也是为什么在CC协议如此有名却在[opensource](https://opensource.org/licenses/)上找不到，建议汉化组在仓库license中增加/更换开源协议，并与作者联系，让英文源码仓库也增加/更换开源协议以保护代码的完全开源性。

总不能狡辩做的内容全是文本吧？这可是在某个游戏框架下的依赖运行文件。况且汉化组release的是可执行文件，不是什么SCP文档

### 2 增加技术分享内容

在GitHub上闭源然后“加群了解”确实能杜绝部分动机不纯人士，就像刚才说的，这种东西一旦被抄袭转商用可不是侵权那么简单。

但另一方面，代码本身就已经很高门槛了，再拉一道肯定会多少招致反对，而且这种门槛也确实影响到了我在“仅供交流学习”中的“学习”，我没了解过twine引擎的架构，前端方面还停留在前端三件套上，虽然三兄的事情与处理方式欠妥，不过如果汉化组能在未来某个时间分享一下汉化的技术方面内容，势必能有助于其他像我一样不熟悉该引擎的码农自学，同时，分享技术细节能带动社区的mod氛围，尤其是以社区核心贡献者的身份分享时（虽然是个18，但好歹是个开源不是）
最好是贴在仓库上的技术文档，不需要太多，简单提及一下你们怎么做到的就行，造轮子能少就尽量少造不是 : ) 。

以上，祝贵组开发顺利

_利益相关：《潜渊症》mod作者、靠开源社区自学走到今天的游戏开发爱好者（业余执行策划兼程序，主Unity、Godot）、因为一句话就给封1天的“1级小号”_
_我是真没想到第一次提issue竟是因为贴吧被封1天_

**Comment by NumberSir** [comment]
你好。

1. 关于 CC 协议和替换与否，无论任何协议，都只防君子不防小人。
- 截至写下回复时，距离汉化版发布仅不到两个月，已经在包括但不限于：C\*\*N、壁\*\*擎、9\*\*3安\*网等多家网站上遇到了盗搬；甚至英文版本身也在包括但不限于: com\*\*\*game, c\*\*\*ts.co, lisa\*\*\*\*\*\*\*art 等多家网站上遇到了盗搬。尽管汉化文本中添加了游戏免费发布的告示，仍然免不了在部分小网站上有付费下载的情况出现。
- 另外，在已经有一定门槛的 GitHub 上已经有 14w+ / 140k+ 的总下载量，可以预见在各种其他渠道如其他网站、网盘、群聊上的总下载量应该远超这个数字。
- 上述付费下载 + 大范围传播将导致什么后果我想应该不用多说，希望理解。

2. 鉴于游戏面向字符串编程的引擎特性：
- 一方面，本游戏的汉化过程既和 [Twine3](https://twinery.org/) 引擎完全无关，又和 [SugarCube2](https://www.motoslave.net/sugarcube/2/docs/) 文本格式化器完全无关，更没有所谓的“汉化源码”，只有一堆文本映射，和汉化唯一相关的技术叫做字符串替换，相关内容在[这里](https://github.com/NumberSir/vrelnir_localization)；
- 另一方面，游戏编译的过程无非就是把 twee 文件中的文本、js 文件中的文本和 css 文件中的文本糅合进一个 html 文件而已，唯一的“复杂化”就是对符号进行转义，把 html 符号反转义回原本的符号——你就得到了源码。游戏本身就无“闭源”一说。

综合以上两点，在未来的汉化版发布将不再发布硬编码进 HTML 的汉化文本，而将采取如 [#32](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/issues/32#issuecomment-1754443351) 所述的发布方式，最快将于下一版应用。
> 截至 [0.4.2.7-chs-alpha4.0.0](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/releases/tag/v0.4.2.7-chs-alpha4.0.0) 的汉化方式（下称“旧版汉化方式”）仍然是修改硬编码，直接下载发布版中的 zip 压缩文件解压即玩。
> 
> 未来的新版汉化方式将基于 [ModLoader](https://github.com/Lyoko-Jeremie/sugarcube-2-ModLoader)，（基本用法请查看 ReadMe，基本原理是向原游戏的 HTML 文件中注入 js 实现加载模组的功能）仅放出含汉化词典的 [I18N 模组](https://github.com/Lyoko-Jeremie/Degrees-of-Lewdity_Mod_i18nMod)，在不修改游戏本地英文原文的情况下在运行过程中动态汉化，类比 [Minecraft 的 I18N 模组](https://www.mcmod.cn/class/1188.html)。
> 
> 未来可能的发布汉化版方式可能会是：
> 
> > 1. 玩家自行在官方英文版发布地址下载英文版
> > 2. 本仓库以安装包的形式发布 ModLoader 和内置汉化词典的 I18N 模组
> > 3. 玩家自行安装 ModLoader 和汉化模组

---

另外，关于模组编写相关，以前的模组会使用修改 twee 文件并重新编译的方法（下称“旧方法”），无论对开发、维护或是游玩者都有不小的压力；当前已经有较为成熟的方案（下称“新方法”），详见 [ModLoader](https://github.com/Lyoko-Jeremie/sugarcube-2-ModLoader)。无论在官方 Discord，还是在 QQ 群，均有使用新方法编写模组的相关讨论与内容发布。

作为玩家，我们欢迎所有热爱本游戏的人；作为汉化者，我们欢迎所有愿意共同为汉化做出贡献的人；作为开发者，我们也欢迎所有愿意参与模组开发的人。而对不怀好意前来的人、人前人后两幅面孔的人、冷嘲热讽的人、甚至装成受害者反咬一口的人，我们并不欢迎。

**Comment by 15x3** [comment]
非常感谢如此详尽的分享 😃
