### ISSUE TITLE
[0.4.2.7-chs-alpha4.1.0] 在进入x用品小店签收箱子时有文本错误

### ISSUE THREAD

**Issue by ShiroArashi** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#127]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 说说你看到的汉化文本内容？

![qq_pic_merged_1697433591972](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/40450639/1adb3be0-faf2-47f1-82d8-479965d70dfa)

**Comment by Khaos423** [comment]
已改，请等待新版本
