### ISSUE TITLE
创建角色时使用成就点加能力时会报错

### ISSUE THREAD

**Issue by longlongint** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#13]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [x] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

创建角色时使用成就点数，只要点进加能力等级(如护理等级)的那几个界面就会报错。apk和html版本均如此。版本1.2.2

### 存档 / 代码

[degrees-of-lewdity-Female-new-Run-20230826-212445.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12445444/degrees-of-lewdity-Female-new-Run-20230826-212445.txt)

### 截图

![QQ截图20230826212538](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/46638209/0b5e8c7f-79f5-4f47-953f-8e3a2822e0e7)
![QQ截图20230826212547](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/46638209/9658dee7-41ea-43ab-ab37-8408817a2458)

**Comment by Eltirosto** [comment]
已修复，请在新版本发布前暂时使用 `alpha1.2.1` 版本创建人物
