### ISSUE TITLE
[0.4.2.7-chs-alpha4.1.0]被夺走初吻的文本报错

### ISSUE THREAD

**Issue by 77676zero** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#131]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

罗宾历史课上亲吻剧情、告白剧情中被夺走初吻都出现了报错文本，在遭遇战中被路人夺走初吻也会报错

### 存档 / 代码

[存档码.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13025229/default.txt)

### 截图

![Screenshot_20231018_204631](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/148347806/b3e4f2ac-35f3-471b-9978-46bf899dda16)

**Comment by Khaos423** [comment]
请提供报错当时的存档，最好打开历史记录

**Comment by 77676zero** [comment]
[报错存档码.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13038339/default.txt)
这是报错的存档

**Comment by Khaos423** [comment]
解决方法是去卧室打开怀孕再去破处。
这个爆红是因为原版recordSperm函数缺乏对禁用怀孕而`V.pregnancytype='f' or 'disalbe'`情况的判断，导致牵手和亲吻童贞时程序出错。而且设置方面怀孕似乎只能开局设置，我去原作者那里反馈一下吧。
