### ISSUE TITLE
[4.2.7-chs-alpha4.2.0]无法查看属性页面

### ISSUE THREAD

**Issue by haitun202** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#133]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

老存档和新存档都是一样的，点开属性就报错

### 存档 / 代码

[degrees-of-lewdity-20231020-213534.save.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13054815/degrees-of-lewdity-20231020-213534.save.txt)

### 截图

![20231020213511](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/33251512/505670cc-5022-475b-aed5-ded1e29a9436)

**Comment by Khaos423** [comment]
已改

**Comment by Umonyoumeng** [comment]
無法查看屬性頁面[資料]

https://eltirosto.github.io/Degrees-of-Lewdity-Chinese-Localization/ 

https://eltirosto.github.io/Degrees-of-Lewdity-Chinese-Localization/

**Comment by Khaos423** [comment]
> 無法查看屬性頁面[資料]
> 
> https://eltirosto.github.io/Degrees-of-Lewdity-Chinese-Localization/
> 
> https://eltirosto.github.io/Degrees-of-Lewdity-Chinese-Localization/

网页部署已更新
