### ISSUE TITLE
[0.4.2.7-chs-alpha4.2.0]無法查看屬性頁面

### ISSUE THREAD

**Issue by Yeddaa** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#134]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

剛剛看了issue有類似問題，但導入存檔碼一樣無法查看

### 存档 / 代码

[4231680186fd146fda9b.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13055642/4231680186fd146fda9b.txt)

### 截图

![螢幕擷取畫面 2023-10-20 230810](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/148562848/dade7dc3-291d-43e7-915e-3c3b679a29fb)

**Comment by Khaos423** [comment]
[该问题已提交过](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/issues/133)

**Comment by Yeddaa** [comment]
不好意思，我的畫面重新整理過後還是一樣無法查看，想請問是我沒有使用到最新的版本還是甚麼狀況，我有先確認前面的issue已經被修復，但我這邊的問題依舊存在
![螢幕擷取畫面 2023-10-20 232635](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/148562848/648320a8-1bd4-4618-9c4b-ed87e99d31c8)

**Comment by Khaos423** [comment]
因为修复了但未更新，大概明早更新4.2.1

**Comment by Yeddaa** [comment]
了解，謝謝，辛苦了！

**Comment by Khaos423** [comment]
请下载新版本
