### ISSUE TITLE
屬性欄的不明亂碼

### ISSUE THREAD

**Issue by Akizuki1529** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#136]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

事情很簡單, 就是我玩的時候按開屬性欄, 就看見這個
好像至半小時前也沒事的, 都玩了一整晚了
剛剛這半小時後的現我有全部的存檔開屬性欄都變這個樣子了
其他資訊欄沒事, 就只是這個
重開browser, 重開機, 一樣存在

### 存档 / 代码

[degrees-of-lewdity-秋月-20231020-235351.zip](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13056245/degrees-of-lewdity-.-20231020-235351.zip)

### 截图

![Degrees of Lewdity - Google Chrome 20_10_2023 23_52_52](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/148570741/cf19805f-a721-4d04-9ced-47c24e5c92d1)

**Comment by Khaos423** [comment]
[该问题已提交过](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/issues/133)请下载4.2.1
