### ISSUE TITLE
0.4.2.7-chs-alpha4.2.0 Error characteristics cannot find

### ISSUE THREAD

**Issue by dambakana** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#137]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述
打開不了属性!!
### 存档 / 代码

[degrees-of-lewdity-20231021-001521.zip.zip](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13056329/degrees-of-lewdity-20231021-001521.zip.zip)

### 截图

![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/148572081/2b42ab58-5fbf-44dc-adb5-d797578fc336)

**Comment by Khaos423** [comment]
[该问题已提交过](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/issues/133)请下载4.2.1
