### ISSUE TITLE
[v0.4.2.7-chs-alpha4.2.1] 染眉剂被错误的翻译为染发剂，同时在使用染眉剂的选项中染眉剂的颜色并没有被翻译

### ISSUE THREAD

**Issue by Meow0x7E** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#139]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 说说你看到的汉化文本内容？

https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/133293581/6a3bd7fd-74ed-4f62-b0b0-3ca3e29aa91c

从视频中可以看到我偷了三种颜色的"染发剂"然后回到家中调出化妆页面时看见了相同颜色的染眉剂选项(注：由于我之前已经染色了雪白色染眉所以选择中没有出现雪白色)同时可以看到染眉剂的颜色并没被翻译

![Screenshot_20231021_225628_org mozilla fenix](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/133293581/15090d76-551d-4320-a111-23603d22f6f3)

![Screenshot_20231021_225740_org mozilla fenix](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/133293581/192957f2-dfc5-49f7-9c7b-ce71011e9785)

**Comment by Khaos423** [comment]
选项已反馈漏抓
游戏中是用染发剂染眉，虽然现实生活不推荐。

**Comment by Meow0x7E** [comment]
补一个存档
[Uploading degrees-of-lewdity-20231021-232318.txt…]()

**Comment by Khaos423** [comment]
已翻，请下载新版本
