### ISSUE TITLE
进购物中心的理发店坐下爆红，无法染发和剪发！

### ISSUE THREAD

**Issue by HanFengRuYue** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#14]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

进购物中心的理发店坐下爆红，无法染发和剪发！
游戏版本：alpha1.2.3

### 存档 / 代码

[degrees-of-lewdity-Fraxelia-20230827-180952.zip](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12447742/degrees-of-lewdity-Fraxelia-20230827-180952.zip)

### 截图

![屏幕截图 2023-08-27 181316](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/76541387/4ca35e14-6b5b-46ea-8ee8-98b08bd74978)

**Comment by Eltirosto** [comment]
已修复，请等待新版本发布
