### ISSUE TITLE
[v0.4.2.7-chs-alpha4.2.1] 设置 > 快速编辑 > (一般NPC性别 | 野兽性别) 的滑块调整至正中央时会产生翻译文本错误

### ISSUE THREAD

**Issue by Meow0x7E** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#140]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 说说你看到的汉化文本内容？

![Screenshot_20231021_221804_org mozilla fenix](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/133293581/dcba23fa-9932-482c-88c8-b734dd83711c)

如图所示 (一般NPC性别 | 野兽性别) 的滑块调整至中央时会产生翻译文本错误

存档:
[degrees-of-lewdity-20231021-232532.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13061106/degrees-of-lewdity-20231021-232532.txt)

**Comment by Khaos423** [comment]
已修，请等待新版本
