### ISSUE TITLE
[v0.4.2.7-chs-alpha4.2.1] 島嶼link出错

### ISSUE THREAD

**Issue by Shio84587** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#141]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [x] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

在某個島嶼發生的錯誤

### 存档 / 代码

[Degrees-of-Lewdity-Chinese-Localization-0.4.2.7-chs-alpha4.2.1.tar.gz](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13063201/Degrees-of-Lewdity-Chinese-Localization-0.4.2.7-chs-alpha4.2.1.tar.gz)

### 截图

![螢幕擷取畫面 2023-10-22 201447](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/148691908/f29c8e19-67f4-4181-bff7-84eea0773d15)

**Comment by Khaos423** [comment]
请发存档

**Comment by Shio84587** [comment]
請問是這個嗎?

Khaos423 ***@***.***> 於 2023年10月22日 週日 下午10:52寫道：

**Comment by Khaos423** [comment]
不是，游戏里左边栏存档→导出/载入→导出存档然后把那个文件发上来

**Comment by Shio84587** [comment]
我剛試過在這裡傳save但格式不對，我剛還有用gmail傳附件

**Comment by Khaos423** [comment]
点获取存档码和复制存档码复制到txt里

**Comment by Khaos423** [comment]
或者.save直接改后缀为.txt也是一样的

**Comment by Shio84587** [comment]
[DOL_save_test.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13064379/DOL_save_test.txt)

**Comment by Shio84587** [comment]
不過反覆安全退出2次就可以繼續了

**Comment by Khaos423** [comment]
应该是原版的事件里缺少了相关link，之后能继续是随机到正常的事件但已经浪费了两个小时，下次随机到这两个事件还是会出问题。
