### ISSUE TITLE
玩到一半突然404錯誤

### ISSUE THREAD

**Issue by Hankiebutter** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#143]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这既不是对游戏报错的反馈，也不是对汉化文本改进的建议

### 说说你遇到的问题？

![Screenshot_2023-10-28-14-49-02-53_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/149228148/69a8f980-e193-4153-b4b0-64e0a551c4b1)
突然出現了這個，不知道該如何解決
也打不開

**Comment by Khaos423** [comment]
> 2023.10.15
> 
> 因用户流量过大，停止使用 Netlify 镜像部署在线版，以后将仅用 [GitHub Pages](https://eltirosto.github.io/Degrees-of-Lewdity-Chinese-Localization/) 部署在线版
请看changelog

**Comment by Hankiebutter** [comment]
那請問以后将仅用 GitHub Pages 部署在线版
我原本的遊戲紀錄該怎麼載入呢

**Comment by Khaos423** [comment]
> 那請問以后将仅用 GitHub Pages 部署在线版 我原本的遊戲紀錄該怎麼載入呢

节哀，记得定期导出，本地在线版都是如此

**Comment by szl0834** [comment]
> > 那請問以后将仅用 GitHub Pages 部署在线版 我原本的遊戲紀錄該怎麼載入呢
> 
> 节哀，记得定期导出，本地在线版都是如此

如果是使用的chromium系浏览器，可以试试看用SecureBark Storage Manager这个拓展插件来迁移之前的存档。
