### ISSUE TITLE
 [0.4.2.7-chs-alpha4.3.0] 窥视罗宾房间报错

### ISSUE THREAD

**Issue by Benotasheep** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#144]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

 [0.4.2.7-chs-alpha4.3.0]版本中，在罗宾高性欲的情况下，进入罗宾房间选择窥视一下，会爆红报错。

### 存档 / 代码

[degrees-of-lewdity-20231028-162853.save.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13194952/degrees-of-lewdity-20231028-162853.save.txt)

### 截图

![罗宾房间报错](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/148609564/4e27638c-0122-41e0-bbd9-18326c3e46dd)

**Comment by Khaos423** [comment]
已修，请等待新版本发布
