### ISSUE TITLE
 [0.4.2.7-chs-alpha4.0.0] iOS系统刷新后显示404notFound

### ISSUE THREAD

**Issue by Xiamufeng-0828** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#145]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

就是我是iOS系统，然后在Safari浏览器上玩的，因为图片加载不出来刷新了一次，然后就显示404notFound

### 存档 / 代码

https://graceful-starlight-97b8ae.netlify.app/

### 截图

![D7B5CB6A-B7C4-4F22-BA94-F7430824B02B](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/149240399/f74f6fc4-de70-4681-bd64-5e3c10f95b06)

**Comment by Khaos423** [comment]
> 2023.10.15
> 
> 因用户流量过大，停止使用 Netlify 镜像部署在线版，以后将仅用 [GitHub Pages](https://eltirosto.github.io/Degrees-of-Lewdity-Chinese-Localization/) 部署在线版
请看changelog
