### ISSUE TITLE
[0.4.2.7-chs-alpha4.3.0] 总体知名度bug

### ISSUE THREAD

**Issue by Zior2107** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#146]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

[0.4.2.7-chs-alpha4.3.0]版本中，总体知名度为声名赫赫而非声名狼藉，进而导致被勒索礼顿事件无法触发。

### 存档 / 代码

[degrees-of-lewdity-瑠奈-20231030-141444.save.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13201447/degrees-of-lewdity-.-20231030-141444.save.txt)

### 截图

![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/149357241/a2aac4ee-e9e7-4435-9f60-347fd1dab380)
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/149357241/bdd52d6f-2d9f-402b-a81b-25c4b6bb0aeb)

**Comment by Khaos423** [comment]
并非bug，两版本总计名声数据是一样的（可以在浏览器里打开F12输入
`let result = 0;
	for (const key in V.fame) {
		result += V.fame[key];
	}`
查看总计名声），只是汉化版认为名声大并非负面，而修改了颜色与形容。
注意到`$headdrive`未定义，也就是没有拷贝到礼顿的照片，这个应该才是勒索不了的原因。

**Comment by Zior2107** [comment]
明白了，感谢解释。
