### ISSUE TITLE
[0.4.2.7-chs-alpha4.3.0] 关于悉尼拆带子剧情中对约旦的称呼问题

### ISSUE THREAD

**Issue by Zero20000** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#147]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 说说你看到的汉化文本内容？

![8aa3341ae267fd2b3b49a71a384fc4bd](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/147210385/3596eca6-8f56-400e-a60e-7de8f4814981)

### 有什么好的想法？

约旦在我这个档是女性，也就是修女身份，英语中人们常称呼修女为sister，但并不是姐妹的意思，就是对修女的尊称，和神父总是被称为“father”一样。我认为改成“修女约旦”更符合原文意。

**Comment by Khaos423** [comment]
修士修女互称兄弟姐妹。Sister可以指修女，也可以指女教友，这里汉化组采用偏向后者的意思。

**Comment by kedaya101** [comment]
“姐妹约旦‘’这个词语出现在对话中我个人也是感觉确实有些奇怪，一般而言要么说约旦姐姐要么说约旦妹妹（即使为表亲密），能理解不好判断约旦是否年龄比主角大还是小所以不好直接决定称呼是姐姐妹妹，但姐妹放在人名前看上去属实不太符合中文习惯，修女约旦又不太符合口语化表达，因此我个人推荐是否可以翻译成“约旦修女”呢？

**Comment by Khaos423** [comment]
既然如此，约旦姐妹如何？

**Comment by kedaya101** [comment]
首先非常感谢汉化组各个大佬们的付出。因为我是一直在等beta版本因而一直在关注每周更新，因而在语义上不太能确定。“约旦姐妹”给我的感觉总像是两人，我不太清楚在本剧情中约旦姐妹是一个角色还是一对角色。从我个人观感上来说如果约旦是特指一个角色的话姐妹这个用法还是不太合适，但如果是多人那就完全没问题。但肯定还是以汉化组的意愿为准，有口汉化吃已经很感谢了，而翻译观感来说肯定也是比较主观的东西，在无法广泛收集想法的情况下自然是谁的贡献多谁来确定较好，也许可以让汉化成员选择一下我只是提出一个小建议。

**Comment by Khaos423** [comment]
> 首先非常感谢汉化组各个大佬们的付出。因为我是一直在等beta版本因而一直在关注每周更新，因而在语义上不太能确定。“约旦姐妹”给我的感觉总像是两人，我不太清楚在本剧情中约旦姐妹是一个角色还是一对角色。从我个人观感上来说如果约旦是特指一个角色的话姐妹这个用法还是不太合适，但如果是多人那就完全没问题。但肯定还是以汉化组的意愿为准，有口汉化吃已经很感谢了，而翻译观感来说肯定也是比较主观的东西，在无法广泛收集想法的情况下自然是谁的贡献多谁来确定较好，也许可以让汉化成员选择一下我只是提出一个小建议。

姐妹为何会认为是两个人，约旦兄弟会认为是兄和弟吗？网络用语集美不是姐妹变来的吗？修女修士固然没错，但确实缺失了**同教友之间亲密称呼**这种表达，这意味着**不是特指**约旦这一个人，而是**教友之间互相称呼**，无名修士修女也可以称呼为兄弟姐妹，你称约旦为兄弟姐妹，约旦也可以称你为兄弟姐妹。
