### ISSUE TITLE
[0.4.2.7-chs-alpha4.3.0] 将 统计——杂项——“衣服被剥光”修改为“衣服被剥掉”

### ISSUE THREAD

**Issue by orchid712** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#149]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 说说你看到的汉化文本内容？

![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/149405858/c817dab8-bc97-445d-80d8-0e2bb11593bd)

### 有什么好的想法？

“衣服被剥光：9” 像是 PC 被剥得一丝不挂过 9 次，但这个统计实际上是被剥掉衣服的件数，例如口罩被扯下来就会算一件，下装或上装彻底被脱下来也算。明明内衣安然无恙，却被“剥光”了，实在是很奇怪。
由于这里并没有指定量词为“件”，如果理解为“次”，就会出现很大的歧义。修改为“衣服被剥掉”就会好很多

还有一个方案，就是将“衣服被剥光”与“衣服被破坏”分别修改为“被剥掉的衣服”与“被破坏的衣服”，这样主体就是衣服，避免了 PC 被剥光的歧义

### 其他内容

英语原文
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/149405858/b4a9b8ae-fa78-4f85-9b6d-87f05544a1f7)

**Comment by Khaos423** [comment]
已改，请等待新版本发布
