### ISSUE TITLE
无法与子女进行互动

### ISSUE THREAD

**Issue by kklovehh** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#15]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

将相同存档导入后，在汉化版中无法与子女进行互动

### 存档 / 代码

[存档.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12448311/default.txt)

### 截图

![Screenshot_20230827_225905_com tencent mtt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/143338870/1f1000d1-f421-411b-a680-bd5ffc121cb0)
![Screenshot_20230827_225912_com vrelnir DegreesOfLewdityWE](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/143338870/fffc3e2a-d6df-4ee0-a98b-396cf2c066ba)

### 还有别的吗？

汉化辛苦了！

**Comment by Eltirosto** [comment]
已修复，请等待新版本发布
