### ISSUE TITLE
[0.4.2.7-chs-alpha4.3.0] 悉尼表白词的微小错误

### ISSUE THREAD

**Issue by orchid712** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#151]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 说说你看到的汉化文本内容？

![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/149405858/c01eec4a-e04b-4157-ba20-7feaf76b1f9a)
以前，没有人让我**过有**这样的感觉。——有过
你……有在真正**的**在意着我——地 （我不会单独为了这个反馈，但来都来了）
另外图中用①②③标注的地方都有一个空格，是故意的吗？
附存档
[degrees-of-lewdity-20231031-223922.zip](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13217713/degrees-of-lewdity-20231031-223922.zip)

**Comment by Khaos423** [comment]
文本已修改，感谢反馈。
关于空格，不得不说题主眼力不错，但仅有③是文本原因，属于翻译的时候没删干净；其他地方都是代码导致的，比如原版代码文本换行显示在一起的时候会拼出个空格（代码换行和文本显示换行是两回事），又或者是调用一个方法就出现的幽灵空格，暂且没有解决方法，只能尽量做到不让空格切开句子，但控制流中的断句出现空格还是难译避免的。
