### ISSUE TITLE
[0.4.2.7-chs-alpha4.3.0] 梅森解貞操籠事件文本出錯

### ISSUE THREAD

**Issue by begentle2662** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#152]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

當下只有截圖忘記導出存檔了，因此檔案可能不是那麼準確><
除了定義代詞問題，下方「敏感的陰莖才意識到這點，閉上眼睛趕緊轉過去」應該也是BUG。
造成麻煩很不好意思，謝謝以及辛苦了。

### 存档 / 代码

[degrees-of-lewdity-birdman-20231101-021439.zip](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13220192/degrees-of-lewdity-birdman-20231101-021439.zip)

### 截图

![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/149527560/acbfade8-7f2e-474f-8481-dac7172e76ff)

**Comment by Khaos423** [comment]
由于没有当时存档比较难诊断，不过粗略看了下文本位置的文件，应该是原版bug

**Comment by begentle2662** [comment]
事件順序：
在歷史課自慰被溫特裝上貞操籠>游泳課全裸給梅森看>要求裸泳>隔天再給梅森看一次

謝謝處理:)

**Comment by Khaos423** [comment]
Ok，已经用存档过了一天复现了，是确实是原版bug，我去跟原作者反映一下
