### ISSUE TITLE
[0.4.2.7-chs-alpha4.3.0] PC高潮描述文本細微錯誤

### ISSUE THREAD

**Issue by HanHan3z** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#153]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 说说你看到的汉化文本内容？

![Image](https://cdn.discordapp.com/attachments/1163674899261427786/1169195180583288882/screenshot.png)

Line 3: 隨著痙攣消退，你 ***重又*** 平靜了下來。你希望聲音沒有引起別人的注意。

[存檔文件](https://cdn.discordapp.com/attachments/1163674899261427786/1169194648040914964/degrees-of-lewdity-SAVE-20231101-163634.save)

**Comment by HanHan3z** [comment]
爲了不占用太多版面，在這裏提另一處細微文本錯誤。

![Image](https://cdn.discordapp.com/attachments/1163674899261427786/1169197822701219910/screenshot.png)

Line 3: 這沒什麽可擔心的， ***搶*** 你不要緊張......

[存檔文件](https://cdn.discordapp.com/attachments/1163674899261427786/1169197822940299295/degrees-of-lewdity-SAVE-20231101-165237.save)

**Comment by Khaos423** [comment]
皆已修改，请等待新版本发布
