### ISSUE TITLE
[0.4.3.3-chs-alpha2.0.0] 兽性汉化出现英语版

### ISSUE THREAD

**Issue by thatskysze** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#157]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 说说你看到的汉化文本内容？

![Screenshot_20231103_211328](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/149778733/eb743a6c-00cd-4584-8595-f675cbee5da3)

**Comment by Khaos423** [comment]
已反馈漏抓
