### ISSUE TITLE
[0.4.3.3-chs-alpha2.0.0] 神庙晋升仪式多字

### ISSUE THREAD

**Issue by orchid712** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#158]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 说说你看到的汉化文本内容？

![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/149405858/8eba3661-7196-49dc-b80f-f6f4ee227889)
这里多了个“**的**”
[degrees-of-lewdity-20231103-211852.zip](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13250680/degrees-of-lewdity-20231103-211852.zip)

### 其他内容

![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/149405858/2a52dc88-b74d-47ae-aa17-7fe0fbc2eba6)
我觉得这里加个“的”会比较好，主要前面有个空格，很容易让人停顿一下，再从“他袍子……”开始语感会很怪
当然，如果能把前面那个空格修掉就更好了，只是不清楚是不是技术问题

**Comment by Khaos423** [comment]
已改，空格确实是技术问题，只能移到不断句的地方不能直接消除。
