### ISSUE TITLE
[0.4.3.3-chs-alpha2.0.0] 成人用品店的報错

### ISSUE THREAD

**Issue by Zeta1002** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#159]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

去成人用品店的時候出現了錯誤
如下圖所示：3

### 存档 / 代码

[degrees-of-lewdity-Pc-20231103-215525.save.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13250951/degrees-of-lewdity-Pc-20231103-215525.save.txt)

### 截图

![Screenshot_20231103_215533_Chrome](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/133109262/a82e08c7-95e1-4ff9-a480-70c1323c50d7)
![Screenshot_20231103_215555_Chrome](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/133109262/c9167ffc-fe9c-4637-8605-84904130d918)
![Screenshot_20231103_215543_Chrome](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/133109262/ba61aa42-3189-44d6-a647-a8862b080935)

**Comment by NumberSir** [comment]
已修复，请等待新版本发布
