### ISSUE TITLE
凯拉尔庄园清洁实验室时文本错译

### ISSUE THREAD

**Issue by kklovehh** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#16]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议

### 说说你看到的汉化文本内容？

![Screenshot_20230828_002619_com vrelnir DegreesOfLewdityWE](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/143338870/18b36cf2-a589-4a7a-afeb-e7436ce0e798)
![Screenshot_20230828_002520_com tencent mtt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/143338870/5c641d5b-b404-40ce-87db-9107ab8b1b7b)

### 有什么好的想法？

alembic是蒸馏器

### 其他内容

汉化辛苦了

**Comment by Eltirosto** [comment]
已修改，请等待新版本发布
