### ISSUE TITLE
[0.4.3.3-chs-alpha2.0.0] 哈珀医生的办公室报错

### ISSUE THREAD

**Issue by hyakuyamikaera** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#160]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

去哈珀医生的办公室时出现错误，如图所示

### 存档 / 代码

[[0.4.3.3-chs-alpha2.0.0] 哈珀医生的办公室报错.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13251573/0.4.3.3-chs-alpha2.0.0.txt)

### 截图

![01](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/149758065/78a13409-4322-48a3-bdc5-7ba7105ac1ee)
![02](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/149758065/21c103a2-766e-4e00-bd83-75a72251650a)
![03](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/149758065/f1d9f4c8-eece-4ab8-84f4-de55f63673e3)
![04](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/149758065/e2e774d8-8561-4e3d-a053-77d3661dbfe6)
![05](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/149758065/c9f86b46-e2b3-46a7-90be-e728eb7f8d91)

### 还有别的吗？

该问题在上周发布的版本中同样存在

**Comment by NumberSir** [comment]
这个报错的原因与 #111 类似，也是由于存档在新旧版本间反复导入导致的问题，修复方法也类似：

在控制台中输入
```
V.hypnosis = 0
```
即可
