### ISSUE TITLE
[0.4.3.3-chs-alpha2.0.0] 神庙回廊及态度选项报错

### ISSUE THREAD

**Issue by hyakuyamikaera** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#161]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

仪式结束抵达回廊、点击红色“态度”后出现如下页面

### 存档 / 代码

[[0.4.3.3-chs-alpha2.0.0] 神庙回廊报错.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13252323/0.4.3.3-chs-alpha2.0.0.txt)
[[0.4.3.3-chs-alpha2.0.0] 态度选项报错.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13252324/0.4.3.3-chs-alpha2.0.0.txt)

### 截图

![0 4 3 3-chs-alpha2 0 0  神庙回廊报错](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/149758065/63bfbfc2-c91c-423e-b064-f4004bf01918)
![0 4 3 3-chs-alpha2 0 0  神庙回廊报错（2）](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/149758065/690bc13f-8213-48ec-ae70-db6a83c631ad)
![0 4 3 3-chs-alpha2 0 0  态度选项报错 (1)](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/149758065/aceccf6b-2adc-4610-852d-e6bc35a5c530)
![0 4 3 3-chs-alpha2 0 0  态度选项报错 (2)](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/149758065/7c18877e-2301-4a7c-ac93-358ddc711ce3)
![0 4 3 3-chs-alpha2 0 0  态度选项报错 (3)](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/149758065/9d7e4802-137c-437a-8edb-f055d8ed4d8c)

### 还有别的吗？

态度选项在卧室和其他地方是正常的，只有在神殿看是红色的

**Comment by Khaos423** [comment]
已修
