### ISSUE TITLE
[0.4.3.3-chs-alpha2.0.0] 在街上被狗肏的时候报错

### ISSUE THREAD

**Issue by cybergeekboy** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#166]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

在街上遇到狗了，跟随，给予奖励异种癖二级。

### 存档 / 代码

(https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13256024/N4IglgJiBcIQpgc.txt)

### 截图

![Screenshot_20231104_141529_com vrelnir DegreesOfLewdity](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/115640870/829c32c4-8616-4210-9cb8-339e58ce44dd)

**Comment by NumberSir** [comment]
传一下报错界面的存档，方便复现

**Comment by cybergeekboy** [comment]
![Screenshot_20231104_141529_com vrelnir DegreesOfLewdity](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/115640870/d2b62c65-a5ba-43d2-b4c0-b8a5a0e4d36e)

非常抱歉，照片一开始传错了

**Comment by cybergeekboy** [comment]
> 传一下报错界面的存档，方便复现

非常抱歉，截图一开始传错了
![Uploading Screenshot_20231104_141529_com.vrelnir.DegreesOfLewdity.jpg…]()

**Comment by Khaos423** [comment]
是说存档，不是说图片，需要报错当时的存档

**Comment by cybergeekboy** [comment]
> 是说存档，不是说图片，需要报错当时的存档

哦，原来是这个我马上去街上找狗

**Comment by cybergeekboy** [comment]
> 是说存档，不是说图片，需要报错当时的存档

非常抱歉，再找狗肏就没有了，直接忽略这一条吧
