### ISSUE TITLE
[0.4.3.3-chs-alpha2.0.0]神殿回廊报错

### ISSUE THREAD

**Issue by OpheliaSH** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#167]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

新神殿剧情晋升后探索进入神殿回廊报错
神殿宿舍床铺中选择态度报错

### 存档 / 代码

[degrees-of-lewdity-20231104-161437.zip](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13256133/degrees-of-lewdity-20231104-161437.zip)

### 截图

![微信截图_20231104161410](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/47210141/df842591-b770-442a-81c2-5108967b3582)
![微信截图_20231104161422](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/47210141/f28f4561-99fc-4f75-97cc-92f840eed77c)

**Comment by panxiaoyi12138** [comment]
神殿回廊报错是因为html文件里第513085行中，判断性别比例的代码里，有个malechance中间多了个>成了mal>echance,我自行删除后就恢复正常了

**Comment by OpheliaSH** [comment]
> 神殿回廊报错是因为html文件里第513085行中，判断性别比例的代码里，有个malechance中间多了个>成了mal>echance,我自行删除后就恢复正常了

确实 感谢分享
