### ISSUE TITLE
[v0.4.3.3-chs-alpha2.0.0]神殿晋升文字及动物化变身发情期时状态栏文字的问题

### ISSUE THREAD

**Issue by KaranoAkira** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#169]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 说说你看到的汉化文本内容？

神殿晋升剧情部分文字将约旦译作了乔丹。
另新版本中，动物化变身处于发情期状态时的状态形容现为英文（返回旧版本汉化时是正常的，对比用的截图为v0.4.2.7-chs-alpha4.2.1）
![QQ图片20231104171158](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/149869178/1455e449-0cd4-43ec-a4c1-bd4b42ddce83)
![QQ图片20231104171234](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/149869178/9eb283b8-76eb-4c1d-bdbd-543d7ba72850)
↑此图为v0.4.3.3-chs-alpha2.0.0
![QQ图片20231104171524](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/149869178/643008b6-4550-4b2a-a0e5-5724a989f704)
↑此图为v0.4.2.7-chs-alpha4.2.1

**Comment by Khaos423** [comment]
该问题与[issue157](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/issues/157)重复
