### ISSUE TITLE
[0.4.3.3-chs-alpha2.0.1] 孤儿院布告板海报未汉化

### ISSUE THREAD

**Issue by thatskysze** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#170]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 说说你看到的汉化文本内容？

![Screenshot_20231104_211522](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/149778733/9895684e-51ae-469c-822f-1f13f7eb1f0e)

**Comment by Khaos423** [comment]
已汉化，请等待新版本发布
