### ISSUE TITLE
[0.4.3.3-chs-alpha2.0.1] 迷你和服穿衣报错，显示有误

### ISSUE THREAD

**Issue by shanmujiuya** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#172]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

上商店新买的和服，只能穿上半身，下半身不显示 ，那会占衣柜格，保存重新加载会显示出破碎下半身，如直接购买穿戴并保存设置，便会固定为整套 ，但会显示其存档错误

### 存档 / 代码

[和服.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13258684/default.txt)

### 截图

![Screenshot_2023-11-05-12-06-59-61_c3a7877071fa066085f34e47f499198f](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/146629759/a54c53f5-813e-45a0-a110-db36683a5bd6)
![Screenshot_2023-11-05-12-41-36-18_c3a7877071fa066085f34e47f499198f](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/146629759/030146f0-2839-4d02-9972-7d5f1a5c31b7)
![Screenshot_2023-11-05-12-41-52-95_c3a7877071fa066085f34e47f499198f](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/146629759/f7bbba5b-8a8e-4ffa-b364-caa7d03f5889)
![Screenshot_2023-11-05-12-44-03-62_c3a7877071fa066085f34e47f499198f](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/146629759/6977df64-e401-4797-8d5b-256937ee7842)

**Comment by Khaos423** [comment]
和服和迷你和服的各种问题应该是原版bug

**Comment by shanmujiuya** [comment]
> bug

感谢，了解了
