### ISSUE TITLE
[0.4.3.3-chs-alpha2.0.1] 战斗文本漏翻

### ISSUE THREAD

**Issue by NormanDSG** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#173]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 说说你看到的汉化文本内容？

<img width="1279" alt="屏幕截图 2023-11-05 143720" src="https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/143474611/d92965e9-dbfb-4589-a996-2d1bef14fabb">

战斗场景发生在食堂-靠近学生们

### 其他内容

[degrees-of-lewdity-20231105-144131.zip](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13258798/degrees-of-lewdity-20231105-144131.zip)

**Comment by Khaos423** [comment]
已反馈漏翻
