### ISSUE TITLE
[0.4.3.3-chs-alpha2.0.1] 寄生虫笔记本部分名词翻译错误

### ISSUE THREAD

**Issue by XonlookerX** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#175]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 说说你看到的汉化文本内容？

![}ZKV 4DXR@B)_3Z%U`~(}YT](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/61648955/01e0a265-834e-4275-bff3-bccb4c32a199)
![%}`P74M5GLE$XB(_W~)$}CL](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/61648955/a31fb581-2873-4bbc-a570-30a51b9211f6)

### 有什么好的想法？

第二行的蛆应翻译为蠕虫，译为蛆极易产生歧义并与其他处的翻译不符

**Comment by XonlookerX** [comment]
传了两张图怎么只显示了一张
![QAOHPP7X7GVCKA(}Q7LB10D](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/61648955/eb9274fc-83f9-4147-a3d5-a8570d07e863)

**Comment by Khaos423** [comment]
并没有翻译错，蛆虫是maggots，蠕虫是worms。
