### ISSUE TITLE
[0.4.3.3-chs-alpha2.0.1] 游戏纹身中的“cattle brand”文件夹丢失问题（原游戏）

### ISSUE THREAD

**Issue by FrostNova67204** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#179]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这既不是对游戏报错的反馈，也不是对汉化文本改进的建议

### 说说你遇到的问题？

游戏开始时如果使用成就加成-初始纹身-烙印-图片-牲口烙印，则会在进入游戏后提示丢失相关图片：
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/64702722/11127077-4e79-43f1-b4f9-759cdd6b22d8)
这个问题在英文原版游戏中也有，不排除是作者本人疏忽或尚未添加相关图片的缘故。将其他文件夹（如paw print）复制进“cattle brand”文件夹后问题解决，游戏内会显示复制进去的文件夹（paw print）中的内容。同时在两个体位的文件夹中同样缺失“cattle brand”文件夹，如上处理后可以得到一定缓解（显示其他图案、不再弹出报错标志）。
由于并非汉化bug（是原版游戏自带的问题）或汉化建议，所以放在了其他议题。大大可以向作者反馈一下（如果是已知问题的话就算了）

**Comment by Khaos423** [comment]
缺图报错汉化组也修不了，反馈的话要附带存档和复现步骤，不方便上官方dc反馈的话也要在这里发存档和说明白步骤哦

**Comment by FrostNova67204** [comment]
[degrees-of-lewdity-20231109-191239.zip](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13307360/degrees-of-lewdity-20231109-191239.zip)
存档已上传，使用的是最新的汉化版本（0.4.3.3-chs-alpha2.0.1）。我不认为是汉化导致的，因为我在原版游戏中同样可以复现这个问题，且原版游戏文件夹中同样缺失相应的文件夹。以防万一，附上原版游戏的存档，游戏版本0.4.3.3：
[[Original]degrees-of-lewdity-20231109-191425.zip](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13307393/Original.degrees-of-lewdity-20231109-191425.zip)
要复现这个问题只需要加载存档，一般就可以在角色图像窗口看到红色叹号，这表示相应的烙印（纹身）图片资源没有被加载：
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/64702722/3f64427e-910c-444c-91d6-27c1b0c9c56e)
要暂时修复这个问题，可以前往\img\bodywriting文件夹下新建cattle brand文件夹，然后将其他文件夹（如heart）内的内容复制过来即可。同时还需要在\img\sex\missionary和\img\sex\doggy文件夹下进行同样的操作。

**Comment by Khaos423** [comment]
嗯，应该确实是原版缺图，我去官方dc反馈下好了
