### ISSUE TITLE
1.2.3版本，在理发店发现报错，无法做发型

### ISSUE THREAD

**Issue by FrShepherd** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#18]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题，但是github有问题没法上传图片了emm

### 存档 / 代码

[degrees-of-lewdity-20230828-084314.zip](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12449213/degrees-of-lewdity-20230828-084314.zip)

**Comment by Eltirosto** [comment]
已修复，请等待新版本发布
