### ISSUE TITLE
[0.4.3.3-chs-alpha2.0.1] 妓院販賣機消失

### ISSUE THREAD

**Issue by ann049** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#180]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

當設置在妓院的販賣機因逾時未補貨而被布萊爾丟棄時，玩家重新設置的販賣機不會出現在妓院中，和西里斯的對話中也沒有進貨選項，導致販賣機再次因逾時未補貨而被布萊爾丟棄。

### 存档 / 代码

[degrees-of-lewdity-千人斬-20231110-000119.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13310289/degrees-of-lewdity-.-20231110-000119.txt)

### 截图

![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/150368989/c3be2f9e-c85b-494b-9dd0-857cb0e3c658)

### 还有别的吗？

感謝漢化組

**Comment by Khaos423** [comment]
贩卖机并没有被卖，浏览器控制台查看`V.brothelVending.status`为`set`，如果被卖会是`sold`，并且`V.weekly.brothelVMCollect`是`true`，见不到贩卖机只是这周收过钱了而已吧？到下一周就能在办公室看到了

**Comment by ann049** [comment]
你好，不好意思想再請問一下，這個部分應該要怎麼查看呢？有試過按f12了但沒找到。
另，如上述提到的，因與西里斯的對話中沒有補貨選項，所以也無法收錢。遊戲時間數天過後也無法查看，並不是只在短時間內有這個狀況。

**Comment by Khaos423** [comment]
> 你好，不好意思想再請問一下，這個部分應該要怎麼查看呢？有試過按f12了但沒找到。 另，如上述提到的，因與西里斯的對話中沒有補貨選項，所以也無法收錢。遊戲時間數天過後也無法查看，並不是只在短時間內有這個狀況。

如果想要看到贩卖机，按F12不是为了查看，是为了**输入**`delete V.weekly.brothelVMCollect`，查看只是为了确认问题，输入该代码才能改变变量从而看到贩卖机。
至于补货，因为现在的状态是售货机**已经安装**，只是因为代码问题判断收过钱了所以无法显示，**你再过几天也不能看到补货选项**，反而是过一天后就能去布莱尔的办公室看到收钱选项，因为星期日已经是提供存档的下一周了。

**Comment by ann049** [comment]
你好
我了解到販賣機現在是已設置的狀態了！但上述所說的「無法收錢」是指因無法補貨，導致點進收錢對話選項後，布萊爾只會表示已丟棄玩家的販賣機、需重新設置，而玩家無法收取金錢。
請問這部分有什麼方法可以解決嗎？再次感謝解答！

**Comment by Khaos423** [comment]
> 你好 我了解到販賣機現在是已設置的狀態了！但上述所說的「無法收錢」是指因無法補貨，導致點進收錢對話選項後，布萊爾只會表示已丟棄玩家的販賣機、需重新設置，而玩家無法收取金錢。 請問這部分有什麼方法可以解決嗎？再次感謝解答！

抱歉，是我没理解，在控制台输入`V.brothelVending.weeksEmpty=0`就能够去西里斯那里补货了

**Comment by ann049** [comment]
太好了！他正常了！非常感謝！
