### ISSUE TITLE
[0.4.3.3-chs-alpha2.0.1] 向悉尼忏悔异种癖文本问题

### ISSUE THREAD

**Issue by arottenpen** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#182]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 说说你看到的汉化文本内容？

和啥？！
文字被拆开了
![Uploading Screenshot_2023-11-10-11-18-38-35_c3a7877071fa066085f34e47f499198f.jpg…]()

**Comment by arottenpen** [comment]
[https://p.sda1.dev/14/b95402b4e382cc0ff59747f7b9c42c89/Screenshot_2023-11-10-11-18-38-35_c3a7877071fa066085f34e47f499198f.jpg](url)
不知为何图貌似没上来

**Comment by arottenpen** [comment]
不知为何图貌似没上来
https://p.sda1.dev/14/b95402b4e382cc0ff59747f7b9c42c89/Screenshot_2023-11-10-11-18-38-35_c3a7877071fa066085f34e47f499198f.jpg

**Comment by NumberSir** [comment]
故意为之
