### ISSUE TITLE
[0.4.3.3-chs-alpha2.0.1] 狼后代数异常暴增bug

### ISSUE THREAD

**Issue by francescahsu** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#188]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

最初发生这个bug是以[0.4.2.7-chs-alpha4.3.0]的版本游玩；后续以[0.4.3.3-chs-alpha2.0.1]版本重新读档游玩亦有发生此问题。
原本的狼后代数应为6个，但在几个动作回合后，会瞬间暴增至12个，已经重复读档（从起初正常6个狼后代数的存档），尝试过相同动作回合或是不同的动作回合，最后都会在某个瞬间，狼后代数变成12个，而且曾经一次是跟正常数量（6）的狼崽互动完，下一秒孩子清册就会多出一倍小孩变成12个，名字也已命名（不同的）。已附上游玩过程荧幕录影档案连结。

### 存档 / 代码

[DoL-issues(Wolf children abnormally increases).txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13320013/DoL-issues.Wolf.children.abnormally.increases.txt)

[DoL-issues(before Wolf children abnormally increases-v2).txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13320832/DoL-issues.before.Wolf.children.abnormally.increases-v2.txt)

### 截图

![IMG_6296](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/53037361/21201496-d0c4-4a5a-a34e-983532fe8e8a)
![IMG_6294](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/53037361/a0db9670-54c5-4ab0-bd9d-39ab4f8da2fe)
[DoL-wolf children abnormally increase bug play through ](https://mega.nz/file/7F1HHDjA#7E_iF8xAJ-LncOpw4LjZ8nVCofSNYccsisxhMqDtA9c)

### 还有别的吗？

感謝漢化組！

**Comment by Khaos423** [comment]
给的存档已经有12个后代，需要变化前的存档

**Comment by francescahsu** [comment]
> 给的存档已经有12个后代，需要变化前的存档

**Comment by francescahsu** [comment]
已更新上传变化前的存档于原贴文，谢谢您！

**Comment by Khaos423** [comment]
> 已更新上传变化前的存档于原贴文，谢谢您！

新存档还是12个啊

**Comment by francescahsu** [comment]
> > 已更新上传变化前的存档于原贴文，谢谢您！
> 
> 新存档还是12个啊

不好意思存错版本，已更新正确版本存档（数量为6）于原贴文中。

**Comment by Khaos423** [comment]
在你睡觉的时候，与你交配过的狼给你生了六胞胎，是正常游戏现象，并非数量异常增加。
