### ISSUE TITLE
[0.4.3.3-chs-alpha2.0.1] 遇到惠特尼霸凌孤儿，服从后遮住脸的同时锁腿出现bug

### ISSUE THREAD

**Issue by hedynn** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#189]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

[0.4.3.3-chs-alpha2.0.1] 遇到惠特尼霸凌孤儿，选择服从后，做的时候遮住脸的同时锁腿惠特尼，出现bug

### 存档 / 代码

[文档.docx](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13320720/default.docx)

### 截图

![IMG_1748](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/150456241/82a09a31-67cf-45f5-86a8-a84062d671b9)

**Comment by Khaos423** [comment]
已修复，请等待新版本发布
