### ISSUE TITLE
[0.4.3.3-chs-alpha2.1.1] 木屋工作结束湿身的拒绝线路中报错

### ISSUE THREAD

**Issue by yuban01652** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#192]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

问题发生在dol-0.4.3.3-chs-alpha2.0.1版本，存档迁移至dol-0.4.3.3-chs-alpha2.1.1仍存在
周末在木屋工作时若因故失去衣服，结束工作时可能会遇到电影导演事件，与马的非自愿接触 Chalets Work End Horse
进入战斗界面时报错
报错信息为0.4.3.3-chs-alpha2.1.1 Error (:: Chalets Work End Horse): <<set>>: bad evaluation: Cannot set properties of undefined (setting 'stance')

### 存档 / 代码

[degrees-of-lewdity-20231111-001116.zip](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13321414/degrees-of-lewdity-20231111-001116.zip)

### 截图

![捕获](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/38140455/c9fc088e-1819-41d9-ade5-6ba678320483)

### 还有别的吗？

可能是原版报错，梯子有点问题没下好原版_(:з」∠)_

**Comment by Khaos423** [comment]
属于原版bug，可以去官方dc反馈
