### ISSUE TITLE
[0.4.3.3-chs-alpha2.1.1] 神殿找堕落悉尼多字

### ISSUE THREAD

**Issue by orchid712** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#193]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 说说你看到的汉化文本内容？

![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/149405858/b87e3ece-3e9a-449a-8d23-233aa6d167b6)
框住的部分不应该存在
[degrees-of-lewdity-农场战斗魅魔-20231111-011324.zip](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13321759/degrees-of-lewdity-.-20231111-011324.zip)

**Comment by Khaos423** [comment]
已改，请等待新版本发布
