### ISSUE TITLE
[0.4.3.3-chs-alpha2.1.2] 在debug模式下的战斗中出现<<actionsman>>报错

### ISSUE THREAD

**Issue by unins000** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#196]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

html版本，在开启游戏的Debug模式后，alpha2.1.0~alpha2.1.2版本皆在战斗中出现了<<actionsman>>报错的现象，这一报错并未在v0.4.3.3-chs-alpha2.0.1或v0.4.3.3原始版本中出现。

### 存档 / 代码

[degrees-of-lewdity-20231112-225252.zip](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13328368/degrees-of-lewdity-20231112-225252.zip)

### 截图

![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/101944410/d2a94b9c-77a5-4705-a713-9ebc0c9eb05e)

### 还有别的吗？

在开启debug模式的情况下，个人所遇到的所有与类人生物进行的战斗都会出现相同的报错情况。

**Comment by unins000** [comment]
我找到问题所在了（大概）

Line 114252:			头部位置: &lt;&lt;= $NPCList[_i].location.head.replace(&quot;head&quot;,&quot;头&quot;).replace(&quot;genitals&quot;,&quot;生殖器&quot;)&gt;&gt; -- 生殖器位置: &lt;&lt;= $NPCList[_i].location.genitals.replace(&quot;head&quot;,&quot;头&quot;).replace(&quot;genitals&quot;,&quot;生殖器&quot;).replace(&quot;idle&quot;,&quot;空闲&quot;)&gt;&gt;

只要将114252行改回alpha2.0.1时的代码，战斗时就不会出现报错
原代码：

			头部位置: $NPCList[_i].location.head -- 生殖器位置: $NPCList[_i].location.genitals

**Comment by unins000** [comment]
Line 169947:			&lt;&lt;print _i&gt;&gt; $NPCList[_i].fullDescription: 头部位置: &lt;&lt;= $NPCList[_i].location.head.replace(&quot;head&quot;,&quot;头&quot;).replace(&quot;genitals&quot;,&quot;生殖器&quot;)&gt;&gt; --- 生殖器位置: &lt;&lt;= $NPCList[_i].location.genitals.replace(&quot;head&quot;,&quot;头&quot;).replace(&quot;genitals&quot;,&quot;生殖器&quot;).replace(&quot;idle&quot;,&quot;空闲&quot;)&gt;&gt;

这一行应该关联和植物人战斗时的报错问题，alpha2.0.1时的代码：

			&lt;&lt;print _i&gt;&gt; $NPCList[_i].fullDescription: 头部位置: $NPCList[_i].location.head --- 生殖器位置: $NPCList[_i].location.genitals

**Comment by Khaos423** [comment]
已改（取消此处汉化），请等待新版本发布
