### ISSUE TITLE
[0.4.3.3-chs-alpha2.1.2] 艾弗里对话的称呼不正确

### ISSUE THREAD

**Issue by 117xxx** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#197]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 说说你看到的汉化文本内容？

![QQ截图20231113185302](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/51844964/39c544e7-ba32-467f-aa00-a41109b1ff5e)
0.4.3.3-chs-alpha2.1.2

**Comment by Khaos423** [comment]
并非，不正确。英文原文就是slave，触发条件是PC顺从过高（大于1900），艾弗里的称呼有不少都是非常抽象的。

**Comment by 117xxx** [comment]
懂了
