### ISSUE TITLE
[0.4.3.3-chs-alpha2.1.2] 淫乱度进度条不会增加

### ISSUE THREAD

**Issue by reibu** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#198]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

即使做了理应使它上升的行为依旧不会增加，且隔天进度还会下滑

### 存档 / 代码

[frankfurt.zip](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13365380/frankfurt.zip)
[pdqmc-vtbqq.zip](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13365381/pdqmc-vtbqq.zip)

### 截图

![IMG_2693](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/150917420/e891ef9e-f0df-47ab-9681-f69e33b1bf71)

**Comment by trlaitioer** [comment]
淫乱、露出、异种较高的时候，相对低级的行为是不会增加进度条的
掉淫乱度是游戏机制，淫乱、露出、异种之一达到3级后可以在卧室的态度里关闭

**Comment by reibu** [comment]
您好那时的举动并不是低级的行为可是还是无法增加

**Comment by NumberSir** [comment]
没看懂，需要详细说明
