### ISSUE TITLE
[0.4.3.3-chs-alpha2.1.2] 海岛核桃和风干核桃

### ISSUE THREAD

**Issue by mengyuxiangsui** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#199]
### 在提问之前...

- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这既不是对游戏报错的反馈，也不是对汉化文本改进的建议

### 说说你遇到的问题？

关于游戏内核桃到底是新鲜的好还是风干的好，我翻看代码得知新鲜核桃 -200 饥饿，风干核桃 -400 饥饿，核桃这玩意除了顶饱外还有其他作用吗？

复制-粘贴
		&lt;&lt;islandicon &quot;nuts&quot;&gt;&gt;&lt;&lt;link [[吃一把生核桃|Island Walnut Eat]]&gt;&gt;&lt;&lt;set $island.walnut--&gt;&gt;&lt;&lt;hunger -200&gt;&gt;&lt;&lt;/link&gt;&gt;&lt;&lt;lhunger&gt;&gt;
		&lt;br&gt;
	&lt;&lt;/if&gt;&gt;
	&lt;&lt;if $island.walnut_dried gte 1&gt;&gt;
		&lt;&lt;islandicon &quot;nuts&quot;&gt;&gt;&lt;&lt;link [[吃一把干核桃 (0:05)|Island Walnut Eat Dried]]&gt;&gt;&lt;&lt;set $island.walnut_dried--&gt;&gt;&lt;&lt;island_pass 5&gt;&gt;&lt;&lt;hunger -400&gt;&gt;&lt;&lt;/link&gt;&gt;&lt;&lt;llhunger&gt;&gt;

**Comment by NumberSir** [comment]
目前没有。与汉化版无关的问题请前往[中文维基](https://degreesoflewditycn.miraheze.org/) / [英文维基](https://degreesoflewdity.miraheze.org/)搜索
