### ISSUE TITLE
苍白幽灵战bug

### ISSUE THREAD

**Issue by Lanyilane** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#2]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

血月在公园乱逛然后导致的苍白幽灵遭遇战，进去之后除了遭遇战结束有画面，控人走路时有画面，遭遇战过程场景全红

### 存档 / 代码

[文本(2023-08-21 143340).txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12393088/2023-08-21.143340.txt)

### 截图

![F` $ABSIPHUT)S51~21`1TG](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/142778824/9abe895d-458a-44f2-b373-23c39899ea33)

### 还有别的吗？

我的这个档是英文档转的汉化档，然后我电脑手机上都试过，只要汉化版本就爆错，但是回到英文原版又正常了

**Comment by Eltirosto** [comment]
已修复，请等待新版本发布
