### ISSUE TITLE
角色栏报错

### ISSUE THREAD

**Issue by caotiyu** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#20]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

版本：v0.4.1.7-chs-alpha1.2.4
更新完后进入存档发现角色按钮打开之后出现报错，其他暂无异常

### 存档 / 代码

[degrees-of-lewdity-20230828-200601.zip](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12454230/degrees-of-lewdity-20230828-200601.zip)

### 截图

![U7Z2Z)WAL1@8FO0YX{5} DA](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/75867601/1e5601fa-cfa8-49d6-8d39-e48139a5ed25)

**Comment by Eltirosto** [comment]
已修复，请等待新版本发布
