### ISSUE TITLE
[0.4.3.3-chs-alpha2.2.0] Nginx 无法加载 Modi18n

### ISSUE THREAD

**Issue by Pony-CW** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#202]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

虽然这做法很tm怪但，我真就这么做了
在 Android 通过 Termux Nginx Web 服务器以在 Firefox 游玩 DoL——是挺怪对吧
在加载基本 mod 前能进入主界面，一旦添加汉化mod，就会卡i18n 90%，同时nginx报错找不到文件

### 存档 / 代码

/

### 截图

![ResizedImage_2023-11-17_23-51-02_2](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/44076275/ee9e6266-0e64-455b-bf0d-027ea1b3fbf7)
![ResizedImage_2023-11-17_23-51-02_1](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/44076275/e7c92719-cbbf-4b74-8366-080529e633ee)

### 还有别的吗？

/

**Comment by Meow0x7E** [comment]
你可以尝试启用"桌面版网站"开关，我和你问题差不多
我使用 Termux 运行 ArchLinux 容器。然后在容器内安装Apache2 Web 服务器来用 FireFox 游玩 dol。在卡加载后尝试用桌面版网站后成功进入主界面，在确认汉化 Mod 被加载后我按照提示重载页面，然后发现游戏并未被汉化，随后在 ModLoader的日志中发现了一些和汉化 Mod 相关的警告信息

可以从以下链接获取我通过 ModLoaderGUI 导出的一些文件，这可能对问题分析有帮助
蓝奏云: [DoLModExportData_20231118_041707.zip](https://wwxe.lanzouj.com/if8D71f60kbe)

**Comment by Meow0x7E** [comment]
值得注意的是我现在在做完这些后我突然就可以直接在未启用"桌面版网站"开关的情况下直接进入主界面了，但是已经没有汉化

**Comment by NumberSir** [comment]
请尝试使用当前最新的构建版 [ModLoader](https://github.com/Lyoko-Jeremie/DoLModLoaderBuild/releases/latest) 与 [汉化包](https://github.com/NumberSir/DoL-I18n-Build/releases/latest) ，看看是否还有这个问题

**Comment by Pony-CW** [comment]
新的发行版已正常
不过吐槽一下加载确实够慢，Nginx 那两条报错也还在
什么时候刷新不用重载最好了
