### ISSUE TITLE
[0.4.3.3-chs-alpha2.2.1] 起床时衣物名称显示错误

### ISSUE THREAD

**Issue by Kyereach** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#204]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

如题，在起床选择穿戴衣物时显示为变量而非套装名称

### 存档 / 代码

[bug.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13400281/bug.txt)

### 截图

![屏幕截图 2023-11-18 ](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/104889995/21438c59-4d7f-48c4-a468-ffcd674a4018)

**Comment by NumberSir** [comment]
已修，可以去这里下载最新的汉化包 https://github.com/NumberSir/DoL-I18n-Build

**Comment by kerech** [comment]
ok感谢
