### ISSUE TITLE
[0.4.3.3-chs-alpha2.2.1]起床时套装名称显示错误

### ISSUE THREAD

**Issue by HSSkyBoy** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#206]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 说说你看到的汉化文本内容？

![起床时](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/122550437/39b407a0-70e8-44fe-b183-2b331c5ec18e)
![衣柜](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/122550437/74f13246-93b1-4996-b84c-575c7f1f8325)
在2.2.1中睡觉后起床，衣柜可能出现如图的错误，不知道其他人有没有
不过将模组升级到[2.2.2pre](https://github.com/NumberSir/DoL-I18n-Build/releases/tag/0.4.3.3-chs-alpha2.2.2-pre-397dc6dc794b2add813a94c79f26a342effe354f)后却又恢复正常[![222-pre.jpg](https://i.postimg.cc/qMKPHqDz/222-pre.jpg)](https://postimg.cc/gnYSvzWW)

**Comment by HSSkyBoy** [comment]
[存檔代碼.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13400872/default.txt)
差点忘传存档了

**Comment by HSSkyBoy** [comment]
我真是逆天()

**Comment by HSSkyBoy** [comment]
我可真逆天

**Comment by NumberSir** [comment]
#204
