### ISSUE TITLE
[0.4.3.3-chs-alpha2.2.1] 漏译以及显示代码问题

### ISSUE THREAD

**Issue by Ark-Two** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#208]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 说说你看到的汉化文本内容？

![QQ图片20231119134200](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/72326210/f2c02be2-89d8-4db1-91e8-d8bfd12e6172)
![QQ图片20231119134204](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/72326210/48f85986-201d-4aa8-9ff1-973b1113f2cf)
图一中的stimulated，incredibly pissed off以及full of suspicion都没有对应的翻译
图二中则显示$_outfit.cn_name_cap

### 有什么好的想法？

暂无

### 其他内容

暂无

**Comment by NumberSir** [comment]
第二张图的问题已修，见 #204

**Comment by NumberSir** [comment]
图1是自己修改过代码的吧，汉化的原理是指定位置的字符串替换。如果你手动改了html里的字符，那出现部分地方汉化失效是正常的。
