### ISSUE TITLE
[0.4.3.3-chs-alpha2.2.1] 建设孤儿院阁楼厨房时的剧情文字错误

### ISSUE THREAD

**Issue by PostMeridy** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#209]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

PC 与修士一起向孤儿院阁楼搬运厨房用品时的文本「这些人变现除了比平时更坚强的毅力」打错字，应为「表现出了」

### 存档 / 代码

[degrees-of-lewdity-测试1enhanced-20231119-203756.save.zip](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13403202/degrees-of-lewdity-.1enhanced-20231119-203756.save.zip)

### 截图

<img width="2672" alt="Screenshot 2023-11-19 at 8 50 45 PM" src="https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/120558641/25bd95b7-b860-4d04-bad3-8b15d3718e22">

**Comment by Khaos423** [comment]
已修改，请等待新版本发布
