### ISSUE TITLE
1.2.4版本 图书馆借书报错

### ISSUE THREAD

**Issue by NormanDSG** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#21]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

汉化1.2.4版本图书馆借阅英语书报错

### 存档 / 代码

[存档代码.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12460142/default.txt)

### 截图

![Screenshot_20230829_115410_com vrelnir DegreesOfLewdityWE](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/143474611/5ea1ce0f-9d0e-4e6b-b012-454f4e528bb3)

**Comment by Eltirosto** [comment]
已修复，请等待新版本发布
