### ISSUE TITLE
[0.4.3.3-chs-alpha2.2.1] 起床後快速換裝處「套裝名稱顯示」

### ISSUE THREAD

**Issue by Otilia0372** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#210]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

 在遊戲中，角色睡眠後起床的快速換裝處，套裝名稱顯示出了問題：皆顯示「穿上$_outfit.cn_name_cap」；但衣櫃內顯示仍為正常的自訂套裝名稱（於「截圖處」附上BUG及衣櫃內顯示正常之對比圖

### 存档 / 代码

[BUGt.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13403654/BUGt.txt)

### 截图

<img width="960" alt="BUG" src="https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/151451722/2366208b-e8f1-45ea-a284-b1cf414d4f91">
<img width="960" alt="衣櫃圖" src="https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/151451722/d473a4c8-d291-4258-86b4-977a61f58aaa">

### 还有别的吗？

角色上床後點擊「儘管去睡」或任一時間之後就會觸發

**Comment by NumberSir** [comment]
#204
