### ISSUE TITLE
[0.4.3.3-chs-alpha2.3.0] 人物图像bug

### ISSUE THREAD

**Issue by LeavesWind233** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#211]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

人物在穿着上装水手服（白色）会出现人物图像的bug 脱掉后会恢复正常

### 存档 / 代码

[存档码.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13464767/default.txt)

### 截图

![Screenshot_2023-11-26-00-49-41-425_com vrelnir DegreesOfLewdity](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/144602687/2c83fd17-db38-44f1-ad4d-4db257d7a230)

### 还有别的吗？

暂不清楚条件 更新后 刚打开存档就是这样 在衣柜试了一下发现是上装导致的错误

**Comment by NumberSir** [comment]
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/52584526/4886b25d-e070-47be-a206-72b819c9eeeb)

无法复现

**Comment by LeavesWind233** [comment]
刚才打开正常了 可能是我的设备读取问题
