### ISSUE TITLE
[0.4.3.3-chs-alpha2.3.0] 檢查皮膚出現錯誤

### ISSUE THREAD

**Issue by Zeta1002** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#213]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

照鏡檢查皮膚時出現錯誤

### 存档 / 代码

[degrees-of-lewdity-20231126-090458.save.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13465649/degrees-of-lewdity-20231126-090458.save.txt)

### 截图

![Screenshot_20231126_090217_Chrome](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/133109262/b584b2b9-e4e2-4539-bd7d-5a70104a4018)

**Comment by LittleNightmare** [comment]
纹身时，选择想要的纹身图案也有这个问题
```
0.4.3.3-(chs-alpha2.3.0) Error (:: Tattoo Bodywriting Write): <<bodywritingOptions>>: cannot execute widget: 0.4.3.3-(chs-alpha2.3.0) Error (:: Tattoo Bodywriting Write): <<set>>: bad evaluation: Cannot set properties of undefined (setting '悉尼让我微笑 :)')
<<bodywritingOptions>>
```
