### ISSUE TITLE
漢化插件突然於Edge一般視窗沒有反應

### ISSUE THREAD

**Issue by BananaBox9487** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#214]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这既不是对游戏报错的反馈，也不是对汉化文本改进的建议

### 说说你遇到的问题？

Chrome一般視窗使用沒有問題 但到了Edge時 雖然有普通跟兼容一樣能選 但不論選哪個 漢化插件都沒作用 插件加載時過於迅速(沒有看到成功) 之後會變成全英文 但是切到Edge的InPrivate模式或者另開新的設定檔(沒有太多索引標籤)漢化插件又能正常運作
![加載畫面](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/152090821/f6a57931-4086-4979-847a-75a3513db9bc)

![螢幕擷取畫面 2023-11-27 015806](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/152090821/12031ae5-9b2d-40b9-ae6e-c227a0d04891)
![螢幕擷取畫面 2023-11-27 015941 InPrivate](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/152090821/e48f89bf-015e-4b53-a354-ff2433e807d4)

**Comment by NumberSir** [comment]
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/52584526/dc57a2e5-07ef-41f1-8b3f-52402199052f)
这是因为你启用了安全模式 #205
