### ISSUE TITLE
[0.4.3.3-chs-alpha2.3.0] 鏡子中的髮型處，「瀏海」中的「蓬鬆短髮」破圖

### ISSUE THREAD

**Issue by Otilia0372** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#215]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

如標題，將於截圖區附圖

### 存档 / 代码

[鏡子髮型庫破圖BUG.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13471659/BUG.txt)

### 截图

<img width="959" alt="髮型庫破圖BUG" src="https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/151451722/4541d888-d18a-4c4b-95e7-b329734119fe">

**Comment by NumberSir** [comment]
![c72981c35a57af47938bfc05a4a54f5c](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/52584526/c5328753-407d-471c-9b9a-2a24f13f7cb2)

这个发型是搭配爆炸头（紧密卷发）用的
