### ISSUE TITLE
[0.4.3.3-chs-alpha2.2.1] 无法关闭数字连接导航

### ISSUE THREAD

**Issue by Trkyuu** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#216]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

没有勾选“启用数字链接导航”，但还是显示数字

### 存档 / 代码

[dol存档.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13482939/dol.txt)

### 截图

![Screenshot_2023-11-28-10-14-22-803_com vrelnir DegreesOfLewdity](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/152238022/e4e1061c-fe3e-44a1-ad7f-a2cccf934d72)
![Screenshot_2023-11-28-10-14-33-371_com vrelnir DegreesOfLewdity](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/152238022/d8712166-ef70-4073-a6f5-1bb283afa070)

### 还有别的吗？

好像持续两个版本了

**Comment by NumberSir** [comment]
这是原版的问题，可能是写出bug了
