### ISSUE TITLE
[0.4.3.3-chs-alpha2.3.0] 自慰性玩具无显示

### ISSUE THREAD

**Issue by nekobolo1** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#219]
### 在提问之前...

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [x] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [x] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

性玩具放置时选项消失

### 存档 / 代码

[新建文本文档.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13504069/default.txt)

### 截图

![QQ图片20231130015642](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/152423817/234adba3-b7f4-436f-92e8-db8ed709448f)
![QQ图片20231130011441](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/152423817/b0beaa3e-b5c3-42ab-a541-a30884a0943d)

**Comment by Khaos423** [comment]
放在地上的意思是pc骑在上面，在本次自慰中就会这样使用假阳具，并非bug，不过有贞操带和护肛板似乎用不了。
