### ISSUE TITLE
构建PWA版本？

### ISSUE THREAD

**Issue by ParticleG** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#22]
### 说说你遇到的问题？

可以将网页版本制作成PWA并发布到Github Pages & Vercel等静态网页部署平台，这样玩家不用下载应用即可游玩。且PWA缓存机制可以在没有网的情况下游玩。
个人测试项目：https://github.com/ParticleG/dol-pwa

**Comment by Eltirosto** [comment]
以前尚未汉化完全时测试过，维护压力比较大。有能力的个人可以自己尝试

**Comment by ParticleG** [comment]
> 以前尚未汉化完全时测试过，维护压力比较大。有能力的个人可以自己尝试

我项目中有一个可用的Workflow，不需要额外维护，只需要在最上面的on事件里加入release事件即可，这样每次你们发布新版本都会自动部署到Github Pages，同时如果有Vercel账号也会部署到Vercel。

https://github.com/ParticleG/dol-pwa/blob/main/.github/workflows/main.yml

**Comment by Eltirosto** [comment]
> > 以前尚未汉化完全时测试过，维护压力比较大。有能力的个人可以自己尝试
> 
> 我项目中有一个可用的Workflow能作为参考，其实直接在这个项目里放一个差不多的workflow，不需要额外维护，只需要在最上面的on事件里加入release事件即可，这样每次发布新版本都会自动部署到Github Pages，同时如果有Vercel账号也会部署到Vercel。
> 
> https://github.com/ParticleG/dol-pwa/blob/main/.github/workflows/main.yml

暂且部署到了 Github Pages，选用 [Netlify][netlify] 镜像加速。

[netlify]: https://graceful-starlight-97b8ae.netlify.app/

**Comment by ParticleG** [comment]
> > > 以前尚未汉化完全时测试过，维护压力比较大。有能力的个人可以自己尝试
> > 
> > 
> > 我项目中有一个可用的Workflow能作为参考，其实直接在这个项目里放一个差不多的workflow，不需要额外维护，只需要在最上面的on事件里加入release事件即可，这样每次发布新版本都会自动部署到Github Pages，同时如果有Vercel账号也会部署到Vercel。
> > https://github.com/ParticleG/dol-pwa/blob/main/.github/workflows/main.yml
> 
> 暂且部署到了 Github Pages，选用 [Netlify](https://graceful-starlight-97b8ae.netlify.app/) 镜像加速。

直接使用Netlify镜像加速存在一个问题：Github Pages部署的Root Url为`https://{user}.github.io/`，而对应仓库的静态网页路径为`https://{user}.github.io/{repo}`，因此我的workflow里有专门针对Github的manifest调整（见 [main.yml#L71](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/blob/29f8ab829b1399be53854b8f2d495802bcfe1a59/.github/workflows/main.yml#L71)）。而Netlify的镜像是直接部署在Root Url上的，因此加上这些调整反而会导致Manifest出错，无法安装PWA应用：
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/38580644/e3c94355-924b-4de0-a3b0-24e090c20256)

我不太清楚你们使用的是Netlify的自动绑定Github仓库并选择分支的部署方式还是手动部署的方式，如果是第一种，可以在workflow里增加一个不带manifest调整的deploy步骤，并发布到新的一个分支，如netlify-pages，同时在你的Netlify项目设置中选中这个Github分支。

**Comment by ParticleG** [comment]
顺便，如果是部署到本仓库的Github Pages，是不需要使用自定义的`${{ secrets.ACCESS_TOKEN }}`的，直接使用action自带的`${{ secrets.GITHUB_TOKEN }}`即可。如果没有部署权限请检测仓库的Settings -> Actions/General -> Workflow permissions -> Read and write permissions
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/38580644/9fc6ca47-c7f1-4b9a-a1fa-abfb4ab99642)

**Comment by Eltirosto** [comment]
已合，现在可以正常安装
