### ISSUE TITLE
[0.4.3.3-chs-alpha2.3.0] 無法進行玩牌遊戲

### ISSUE THREAD

**Issue by sheepog** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#220]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

無法與倫恩進行玩牌遊戲。

### 存档 / 代码

[degrees-of-lewdity-X-20231201-190614.save.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13525348/degrees-of-lewdity-X-20231201-190614.save.txt)

### 截图

![IMG_8792](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/152070576/4ec0cbe0-2d86-4e9a-8b0c-dac87283809d)

**Comment by NumberSir** [comment]
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/52584526/901b28f0-c470-4bbe-bfd7-a0577874bf60)

非汉化版问题，可能会在下个大版本更新中修复
