### ISSUE TITLE
[0.4.3.3-chs-alpha2.4.0] 戰鬥輪莫名報錯

### ISSUE THREAD

**Issue by yoyoliu9189** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#222]
### 在提问之前...

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

我使用這個存檔前往觸發戰鬥場景以後便出現以下現象（如圖所示） 哪怕切換回2.3.0也沒有任何改善
它是莫名出現的 我沒有任何頭緒 pc當前情況是體內已有五枚精子 在獲得這五枚精子前觸發戰鬥場景時沒有任何問題 當我準備收集更多精子時 就出現報錯提示了
此外 明明是剛進入戰鬥輪（「控制感破碎」） 下一句卻出現了「pc用腳纏住對方」 這一點也很奇怪
我對此毫無頭緒

### 存档 / 代码

[DOL.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13536478/DOL.txt)

### 截图

![Screenshot_2023-12-02-21-49-08-235_com vrelnir DegreesOfLewdity](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/132116808/1f45f80e-77d1-48a4-a145-043d83259107)
![Screenshot_2023-12-02-21-57-54-494_com vrelnir DegreesOfLewdity](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/132116808/bfd63a6e-b5d0-460d-8f09-204de1bbbdc3)

**Comment by Khaos423** [comment]
请发报错当时的存档

**Comment by Kagamine-Rinrin** [comment]
你是不是开了其他模组 ? 因为我发现你的战斗场景加载了游戏本体中不存在的组件

而且我这边读你的档触发战斗没有报错哦
