### ISSUE TITLE
[0.4.3.3-chs-alpha2.4.0] 检查药片的时候，药品的名称是英文

### ISSUE THREAD

**Issue by XyMinxin** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#224]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议
- [x] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 说说你看到的汉化文本内容？

![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/100689349/5e22e104-5e0d-42bd-833d-6ae1eeb3b52e)

**Comment by Khaos423** [comment]
已修，请等待新版本发布
