### ISSUE TITLE
[0.4.3.3-chs-alpha2.4.0] 统计部分错译

### ISSUE THREAD

**Issue by nerine0** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#225]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 说说你看到的汉化文本内容？

![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/141686660/de69fe43-2589-45c3-b810-2c71188cb365)

统计中怀孕部分晨起服药为错译，应该是服用紧急避孕药（moring after pill) 次数

**Comment by Khaos423** [comment]
已改，请等待新版本发布
