### ISSUE TITLE
[0.4.3.3-chs-alpha2.4.0] 在酒吧，角色性別錯譯

### ISSUE THREAD

**Issue by EndlessNull** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#228]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

依據文字，他是男的，有**丈夫**，還有小孩
應該是妻子吧

### 存档 / 代码

[degrees-of-lewdity-test-20231205-235150.save.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13562356/degrees-of-lewdity-test-20231205-235150.save.txt)

### 截图

![圖片](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/34579128/89867b4a-bbbc-4208-82fc-2dc0c259e0f4)

**Comment by Khaos423** [comment]
游戏npc可以是同性恋，小孩也可以是领养，并且这个丈夫是调用而不是简单的文本翻译，判断是根据设置的性别随机度来的，所以并非是bug或者错译。
该片段代码为
`<<He>>笑了起来，"你可真是，不过还请瞒着我的<<spouse>>！"`
spouse方法代码为
`<<widget "spouse">><<silently>>`
`<<if maleChance($pronoun) gte random(1,100)>>`
`<<set _text_output to ($pronoun is "m" ? "丈夫" : "妻子")>>`
`<<else>>`
`<<set _text_output to ($pronoun is "m" ? "妻子" : "丈夫")>>`
`<</if>>`
`<</silently>><<print _text_output>><</widget>>`
