### ISSUE TITLE
[0.4.3.3-chs-alpha2.5.0]  没有ModLoader显示

### ISSUE THREAD

**Issue by Ark-Two** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#232]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

打开游戏发现右下角没有ModLoader，使用版本为目前的最新版v0.4.3.3-chs-alpha2.5.0（ModLoader-0.4.3.3-v2.11.7）

### 存档 / 代码

null

### 截图

![QQ图片20231210093905](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/72326210/1adfd14e-dc6b-4d71-b9eb-c3cf90710153)

### 还有别的吗？

正常打开游戏，并没有发现右下角的ModLoader窗口
手机型号：vivo s1 pro

**Comment by NumberSir** [comment]
请尝试 polyfill 版
