### ISSUE TITLE
[0.4.3.3-chs-alpha2.5.0] 请求大大们上架自带图片的本体 polyfill 版

### ISSUE THREAD

**Issue by un114514okk** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#234]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这既不是对游戏报错的反馈，也不是对汉化文本改进的建议

### 说说你遇到的问题？

ployfill版本载入图片包和汉化包后，图片包不生效，汉化生效并且欲都孤儿正常显示

**Comment by NumberSir** [comment]
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/52584526/48145077-f113-494c-a810-fd47f6980a93)

![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/52584526/eeef8351-3f96-4a05-83af-12ce3a2b6788)


无法复现，请在模组加载器界面划到最下方导出所有数据，然后在导出的压缩包中找到 ModLoaderLog.txt 上传
