### ISSUE TITLE
版本 Degrees of Lewdity 0.4.4.4

### ISSUE THREAD

**Issue by xurui165023** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#235]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这既不是对游戏报错的反馈，也不是对汉化文本改进的建议

### 说说你遇到的问题？

版本已经更新。

**Comment by xurui165023** [comment]
现在是Degrees of Lewdity version 0.4.4.4

**Comment by Khaos423** [comment]
词条已更新，正在汉化中，稍安勿躁
