### ISSUE TITLE
各位大佬能否考虑在每次原作者版本更新后发布一次旧版汉化方式的游戏？

### ISSUE THREAD

**Issue by dufy2000** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#236]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这既不是对游戏报错的反馈，也不是对汉化文本改进的建议

### 说说你遇到的问题？

如题，各位佬能否考虑一下每次更新时顺带制作一下如0.4.3.3-chs-alpha2.1.2版本时的旧汉化版本。
我不清楚是否有其他人和我一样，但我确实不喜欢给游戏上mod，我希望能体验原汁原味的dol
新汉化方式的mod加载器在每次开启游戏时相较于旧版汉化方式时间长了非常多，并且bug频出，部分文本汉化也会丢失。
因此对于我来说，新版的mod加载器汉化形式对我的游戏体验其实是完全负面的
所以能否考虑一下在每一次版本更新后制作一次旧汉化形式的游戏？
在后续没有太大恶性bug的情况下，部分文本错字只更新在mod版本中就可以了，旧汉化形式只在每次大版本更新时推出一次
如果实施我的提议会造成各位佬的工作量增加太多，各位权当没看见我在这说……抱歉

**Comment by NumberSir** [comment]
**不会。**

所谓“旧版汉化方式”是将汉化文本以直接替换的方式写入源码，从根本上覆盖了游戏源码，是技术不成熟时的妥协方式，在任何时候都应该作为最后考虑的没有办法的办法。这种方法除了所谓的“加载快”、“原汁原味”之外没有任何优点。事实上，如果[模组加载器(JML)](https://github.com/Lyoko-Jeremie/sugarcube-2-ModLoader) 在汉化之前就存在，那连所谓的“旧版汉化方式”都不会存在，从一开始就会使用“新版汉化方式”汉化发布。

之所以更新汉化方式，主要有以下几点原因：
1. 由于旧版汉化方式以硬编码的方式写死进有六十四万多行的游戏源码，对英文游戏源码进行了彻头彻尾的修改，这也是旧版汉化方式一切缺点的根源：
    1. 首先，汉化文本与游戏本体耦合严重，即使对汉化文本小修小补，更新时也需要下载大量的本不用下载的无用内容；而新版汉化方式中汉化文本与游戏本体分离，对汉化文本的小更新只需要下载汉化包即可，而由于将图片包也分离出来，每次更新仅需下载不到之前三分之一的文件大小，对于玩家而言更便捷。
    2. 其次，旧版汉化游戏兼容性极差，一切基于英文游戏源码进行的其它修改均无法同旧版汉化共存；而新版汉化方式对英文游戏源码不进行静态修改，只在运行时动态替换，因此兼容性好，基于英文游戏源码进行的游戏修改更容易与新版汉化共存，对于模组开发者而言更便捷。
    3. 再次，旧版汉化文本在维护、更新时需要耗费大量的时长，对汉化组成员而言压力巨大；而新版汉化方式大幅缩短了每次更新和维护时的时长，无论汉化文本润色、问题排除还是更新测试，需要耗费的精力更少，对于汉化组成员而言更便捷。
2. 由于“旧版汉化方式”受汉化形式所限，只能得到硬编码后的游戏 HTML 文件，不存在正常意义上的“汉化版源代码”，这与英文游戏仓库的 [CC-NC-SA 4.0](https://gitgud.io/Vrelnir/degrees-of-lewdity/-/blob/master/LICENSE) 许可证有存在冲突的可能性；而“新版汉化方式”因为保留英文源码不变，避免了潜在争议的可能性。
3. 此外，除中国玩家外，诸如俄罗斯、韩国、巴西、法国等地都有希望将英文游戏本地化的玩家群体。作为第一个稳定更新、维护本地化版本的玩家群体，自然有许多来自世界各地的玩家前来友善交流学习本地化经验。旧版汉化方式没有任何参考价值，而新版汉化方式由于以词典/映射的方式提供，可以供世界各地希望本地化游戏的玩家群体学习参考。

除此之外，“文本汉化丢失”和“bug频出”并非汉化方式不同造成的，如由于安卓手机内置 Webview 版本过旧导致的无法加载，无论在新旧汉化方式上均存在；而对于仅在新版汉化方式上存在，旧版汉化方式上不存在的报错，只有可能是与同时加载的其它模组产生兼容性问题；

这样一来，事实上只有“启动时间长”是难以避免的负面特性，而启动时间长是受制于游戏本身引擎 SugarCube2 全同步运行的特性限制；而且，即便启动时间长，在多次优化加载逻辑后，在一般电脑端上的启动时间也仅有 5-10 秒，在一般安卓移动端上的启动时间最长也仅有 20-30 秒，如果出现超过 1 分钟的加载时间，一定是在加载过程中遇到了问题。

最后，模组加载器作为新版汉化方式的依托，也作为一个游戏能否保持活力的必备物品，在游戏发展过程中必然出现。而游戏额外内容在开发时的规范化，也在游戏发展过程中必然经历。因此未来对于汉化的方式只会继续不断优化、改进，而不会再倒退回此前的旧版汉化方式。

**Comment by dufy2000** [comment]
好的，多谢大佬解答。大佬们辛苦了
