### ISSUE TITLE
一部分關鍵詞以及服飾顏色未翻譯

### ISSUE THREAD

**Issue by yatounoneko** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#24]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议

### 说说你看到的汉化文本内容？

包括但不限於這些，還有一些服飾顏色和器官及動物詞語，都沒有還未翻譯。不太清楚是否與 #17 有關？
版本：0.4.1.7-chs-alpha1.2.5

![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/22129910/1092301e-3c93-45b0-b7e9-a056ccdfad5c)
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/22129910/4616f81d-4905-4bdf-be1f-35f41129f6f1)
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/22129910/fa6b3275-c5eb-4c72-a8ed-876bda8741d8)
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/22129910/0782c0b0-5fdb-4d19-8141-b7653c98211a)
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/22129910/55172c81-934d-4c05-af59-a765f04d48cc)
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/22129910/bf4bf4c3-bc39-4669-a4fe-26a03cbe47c1)
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/22129910/6556adcb-ebfc-4903-8c3b-da39ad4338e7)

### 有什么好的想法？

希望能夠修復這些問題

**Comment by Eltirosto** [comment]
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/142655202/4ced52df-53b7-47f5-aae0-afe12e6d1fb5)
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/142655202/2d6d1e9f-4c86-4699-9387-02bf4f7d8d71)
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/142655202/ab595f54-a39a-446a-b1fc-367e7f295083)

**Comment by Eltirosto** [comment]
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/142655202/ad41030f-81cd-4d06-b024-982381875090)
下次请附上每处页面的存档，方便检查是否修复
