### ISSUE TITLE
[v0.4.5.3-chs-alpha1.0.0]导入ModI18N后启动报错

### ISSUE THREAD

**Issue by ShiroSakurairo** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#243]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

似乎是因为版本错误，游戏本体文件名写的是v0.4.5.3但启动后游戏内显示v0.4.5.2，随后游戏内出现大量报错无法一一指出

### 存档 / 代码

无关

### 截图

![Uploading Screenshot_2023-12-29-21-18-47-57_c3a7877071fa066085f34e47f499198f.jpg…]()

**Comment by NumberSir** [comment]
已修复，请更新最新版本
