### ISSUE TITLE
[0.4.5.3-chs-alpha1.0.2] 丸吞战斗界面报错

### ISSUE THREAD

**Issue by yimoandloucy** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#251]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

我在罗宾在森林里散步时触发篮子掉进森林的剧情，我选择了去拿回来并触发了丸吞事件。但是触发了战斗界面丢失的错误bug。我只安装了汉化插件和Inazma蔚蓝档案的光环模组。

### 存档 / 代码

[新文字文件.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13801452/default.txt)

### 截图

![QQ图片20231231224511](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/155311455/3215dd94-eab8-4e5e-b213-d3d63a0743d7)

**Comment by NumberSir** [comment]
#247
