### ISSUE TITLE
[0.4.5.3-chs-alpha1.0.2] 物品栏玩具图片不显示

### ISSUE THREAD

**Issue by branpurnae** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#253]
![Screenshot_20231231_004258_Degrees of Lewdity.png](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/99044636/5d3782d8-a243-4c3b-8551-816b85ff9732)

店内购买时正常

**Comment by NumberSir** [comment]
#246
