### ISSUE TITLE
[0.4.5.3-chs-alpha1.0.2] 无法在海滩小摊商店添加出售的手持物品

### ISSUE THREAD

**Issue by HAL900O** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#255]
### 在提问之前...

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

同一个手持物品用modloader加入游戏时，在服装店中可以显示，但是在海滩商店里没有显示，去掉了汉化mod和图片包也不行，不知道是具体哪个mod的问题…
在原版中直接修改html文件可以正常显示海滩商店添加物品。

### 存档 / 代码

[问题示例存档.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13807921/default.txt)

### 截图

![IMG_3451](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/155423875/ed71be85-856f-4f34-b5de-41cc5772ea41)
![IMG_3452](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/155423875/b127440b-9f40-4e2a-b349-5e7c1031e294)

![IMG_3453](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/155423875/ee6a9d11-0b98-4d72-ad8b-44c8c6688d7c)

### 还有别的吗？

[在服装店和海滩增加手持物品的测试mod.zip](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13807934/mod.zip)

**Comment by Kagamine-Rinrin** [comment]
你点开看看预览图的图片地址是不是出现错误了诶
