### ISSUE TITLE
[0.4.5.3-chs-alpha1.2.0] 孤儿院报错

### ISSUE THREAD

**Issue by qwzther** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#263]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

更新模组加载器与汉化mod后依然出现如issue/261的报错。

### 存档 / 代码

[错误存档.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13922659/default.txt)

### 截图

![IMG_20240113_020613](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/156461764/31867238-7396-4536-8052-9b299b9f32fc)

### 还有别的吗？

从该存档中离开房间即触发此报错。
这个报错是在尝试触发不同的孤儿院事件时发生的。我尝试通过不同的路径回到孤儿院大厅并触发事件时，在经过一次洗澡之后进入罗宾房间，便触发了该报错。而在其他路径下仍可正常触发孤儿院事件。

**Comment by Kagamine-Rinrin** [comment]
这个上周五应该已经修复过啦
