### ISSUE TITLE
[0.4.5.3-chs-alpha1.2.0] 约旦跟踪事件报错

### ISSUE THREAD

**Issue by Meowmeow030** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#264]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

约旦跟踪事件中选择“回头看”会报错，选择“对峙”时缺少姓名文本

### 存档 / 代码

[1_cundang1.docx](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13924272/1_cundang1.docx)

### 截图

[![Screenshot-2024-01-13-05-46-27-235-com-vrelnir-Degrees-Of-Lewdity.jpg](https://i.postimg.cc/FR9ZjbQ6/Screenshot-2024-01-13-05-46-27-235-com-vrelnir-Degrees-Of-Lewdity.jpg)](https://postimg.cc/7CW042h1)
[![Screenshot-2024-01-13-05-46-33-520-com-vrelnir-Degrees-Of-Lewdity.jpg](https://i.postimg.cc/rsGMvLHs/Screenshot-2024-01-13-05-46-33-520-com-vrelnir-Degrees-Of-Lewdity.jpg)](https://postimg.cc/YLS5WTMB)
[![Screenshot-2024-01-13-05-38-25-743-com-vrelnir-Degrees-Of-Lewdity.jpg](https://i.postimg.cc/FzpwyFqy/Screenshot-2024-01-13-05-38-25-743-com-vrelnir-Degrees-Of-Lewdity.jpg)](https://postimg.cc/QKB6sDjC)

**Comment by Meowmeow030** [comment]
> ### 在提问之前...
> * [x]  我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
> * [x]  我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
> * [x]  我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
> * [x]  我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]
> 
> ### 问题描述
> 约旦跟踪事件中选择“回头看”会报错，选择“对峙”时缺少姓名文本
> 
> ### 存档 / 代码
> [1_cundang1.docx](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13924272/1_cundang1.docx)
> 
> ### 截图
> [![Screenshot-2024-01-13-05-46-27-235-com-vrelnir-Degrees-Of-Lewdity.jpg](https://camo.githubusercontent.com/fefc2b284e523fc3da03d0a32901019713041ebb64ff61a71282439544a8263a/68747470733a2f2f692e706f7374696d672e63632f3464394a5163627a2f53637265656e73686f742d323032342d30312d31332d30352d34362d32372d3233352d636f6d2d7672656c6e69722d446567726565732d4f662d4c6577646974792e6a7067)](https://postimg.cc/62BJ9yP3) [![Screenshot-2024-01-13-05-46-33-520-com-vrelnir-Degrees-Of-Lewdity.jpg](https://camo.githubusercontent.com/71ea73028d83e9732fa3bc8e773ed98d060234a3a71fedba890000b8bcbe762b/68747470733a2f2f692e706f7374696d672e63632f7273474d764c48732f53637265656e73686f742d323032342d30312d31332d30352d34362d33332d3532302d636f6d2d7672656c6e69722d446567726565732d4f662d4c6577646974792e6a7067)](https://postimg.cc/YLS5WTMB) [![Screenshot-2024-01-13-05-38-25-743-com-vrelnir-Degrees-Of-Lewdity.jpg](https://camo.githubusercontent.com/673c6bafbec3593113498b5a7fa3f9b4341631b3b6a04f9bd45b8c1899fc07bc/68747470733a2f2f692e706f7374696d672e63632f467a7077794671792f53637265656e73686f742d323032342d30312d31332d30352d33382d32352d3734332d636f6d2d7672656c6e69722d446567726565732d4f662d4c6577646974792e6a7067)](https://postimg.cc/QKB6sDjC)
> 
> ### 还有别的吗？
> _No response_



> ### 在提问之前...
> * [x]  我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
> * [x]  我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
> * [x]  我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
> * [x]  我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]
> 
> ### 问题描述
> 约旦跟踪事件中选择“回头看”会报错，选择“对峙”时缺少姓名文本
> 
> ### 存档 / 代码
> [1_cundang1.docx](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13924272/1_cundang1.docx)
> 
> ### 截图
>[![Screenshot-2024-01-13-05-46-27-235-com-vrelnir-Degrees-Of-Lewdity.jpg](https://i.postimg.cc/FR9ZjbQ6/Screenshot-2024-01-13-05-46-27-235-com-vrelnir-Degrees-Of-Lewdity.jpg)](https://postimg.cc/7CW042h1)
 [![Screenshot-2024-01-13-05-46-33-520-com-vrelnir-Degrees-Of-Lewdity.jpg](https://camo.githubusercontent.com/71ea73028d83e9732fa3bc8e773ed98d060234a3a71fedba890000b8bcbe762b/68747470733a2f2f692e706f7374696d672e63632f7273474d764c48732f53637265656e73686f742d323032342d30312d31332d30352d34362d33332d3532302d636f6d2d7672656c6e69722d446567726565732d4f662d4c6577646974792e6a7067)](https://postimg.cc/YLS5WTMB) [![Screenshot-2024-01-13-05-38-25-743-com-vrelnir-Degrees-Of-Lewdity.jpg](https://camo.githubusercontent.com/673c6bafbec3593113498b5a7fa3f9b4341631b3b6a04f9bd45b8c1899fc07bc/68747470733a2f2f692e706f7374696d672e63632f467a7077794671792f53637265656e73686f742d323032342d30312d31332d30352d33382d32352d3734332d636f6d2d7672656c6e69722d446567726565732d4f662d4c6577646974792e6a7067)](https://postimg.cc/QKB6sDjC)
> 
> ### 还有别的吗？
> _No response_

**Comment by Kagamine-Rinrin** [comment]
你这个档不对呀，读取之后不是在追踪画面
是否加载了什么mod？

**Comment by Kagamine-Rinrin** [comment]
修复了，但是是手动加入的词条，因为历史遗留问题，目前的修复只是一个临时的解决方法。
需要 @NumberSir 在base-combat\effects.twee：4858行 `<<nnpc_He $NPCList[0].fullDescription>>` 加入额外提取规则
详见para里该词条的备注
