### ISSUE TITLE
[0.4.5.3-chs-alpha1.1.1] 忏悔室对话出现英文单词

### ISSUE THREAD

**Issue by Ham-desu** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#265]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

版本：0.4.5.3-(chs-alpha1.1.1)
前置：与悉尼在忏悔室进行战斗后进入忏悔室接受忏悔
频率：Once

### 存档 / 代码

[1.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/13944437/1.txt)

### 截图

![Screenshot_2024-01-16-08-25-10-231_com vrelnir DegreesOfLewdity lyra](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/11458903/aa5901f6-1b52-4f6f-a334-3224eb556d7e)

**Comment by Ham-desu** [comment]
下个版本update resolve吗

**Comment by Kagamine-Rinrin** [comment]
> 下个版本update resolve吗
一般版本更新都会修复之前发现的错误
不过具体时间你还是得问南玻色
