### ISSUE TITLE
[0.4.5.3-chs-alpha1.2.0] 耳中史莱姆任务无法完成

### ISSUE THREAD

**Issue by mirrormirroronwall** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#266]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这既不是对游戏报错的反馈，也不是对汉化文本改进的建议

### 说说你遇到的问题？

耳中史莱姆的命令中，有一部分需要在一定时间内完成任务，如睡前跑步或游泳一小时、用精子灌入自己的阴道等
原版中可以正常完成，但汉化版中即使满足条件，到时间也会显示任务失败
并且如果是在汉化版接任务，换到原版满足条件，也是任务失败

**Comment by Kagamine-Rinrin** [comment]
应该找到原因了，等南玻色来修复
