### ISSUE TITLE
人物显示这里一直这样吗？

### ISSUE THREAD

**Issue by liwangerde** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#267]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这既不是对游戏报错的反馈，也不是对汉化文本改进的建议

### 说说你遇到的问题？

![Screenshot_20240117_220503](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/156917504/9d03b8d0-9831-4ec8-b83c-590d13670c02)

**Comment by Kagamine-Rinrin** [comment]
抱歉我没看懂你想表达什么O.O

**Comment by liwangerde** [comment]
> 抱歉我没看懂你想表达什么OO

我记得我之前玩的时候在主角人物的右侧会显示一个主角的面部特写

**Comment by HanFengRuYue** [comment]
面部特写是模组功能，原版没有的

**Comment by liwangerde** [comment]
> 面部特写是模组功能，原版没有的

感谢感谢ꉂ(ˊᗜˋ*)
