### ISSUE TITLE
安卓最新版本0.4.5.3 无法找到Mod文件管理器

### ISSUE THREAD

**Issue by meowmeowmeowmeowmeomeoww** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#268]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

游戏左下角找不到Mod文件管理器

### 存档 / 代码

[Uploading 阿巴阿巴.txt…]()

### 截图

![Screenshot_2024-01-19-14-51-07-50_c3a7877071fa066085f34e47f499198f](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/157098628/a961e76a-c616-4ac4-acdb-14f38489d884)

**Comment by NumberSir** [comment]
请升级手机的 Webwebview 内核版本，或使用 HTML 版而非 APK 版
https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/issues/98#issuecomment-1749917413
