### ISSUE TITLE
0.4.5.3-chs-alpha1.3.0孤儿院每日随机事件报错

### ISSUE THREAD

**Issue by bd-star** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#270]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

大部分事件可以正常触发，应该是某个事件有bug

### 存档 / 代码

[报错存档码.docx](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/14031805/default.docx)

### 截图

![Screenshot_20240124_095603](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/157553573/33dce830-b6cb-4722-b85c-e0cff4e70e8f)

### 还有别的吗？

[前置.docx](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/14031836/default.docx)
从前置存档看几次镜子就能触发了

**Comment by Kagamine-Rinrin** [comment]
应该是[[0.4.5.3-chs-alpha1.2.0] 孤儿院报错](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/issues/263)同样的BUG吧？
之前应该修复过了

**Comment by Kagamine-Rinrin** [comment]
检查了一下,发现就是已经修复过的那条:
`你停留了一会儿，随意地看向布告板，你看到了一张有趣的海报。上面是贝利，她的脸上画了个大大的“X”，上面一字未着，但不言而喻。`
还有就是@NumberSir， 编译的汉化版里是塞了什么东西影响随机数么？
英文原版读同一个档，但是读出来的游戏进度不一致。
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/43258604/9bd4414c-4264-4888-953c-bd88eac1a102)
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/43258604/1915a12b-751c-4b20-8437-aa88ca8896d6)
