### ISSUE TITLE
[0.4.5.3-chs-alpha1.5.0] 岛屿绳索事件翻译有误

### ISSUE THREAD

**Issue by branpurnae** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#277]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 说说你看到的汉化文本内容？
![Screenshot_20240203_195007_Degrees of Lewdity](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/99044636/5ebabdb4-131a-4813-a514-a191b58ee63a)
选项(1)不应为划桨

**Comment by branpurnae** [comment]
![Screenshot_20240203_195007_Degrees of Lewdity](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/99044636/43c067ea-438f-4687-9ff0-c62bcfab5e52)

**Comment by Kagamine-Rinrin** [comment]
已修改
