### ISSUE TITLE
[0.4.5.3-chs-alpha1.3.0] 耳朵史莱姆出现汉化问题导致裸体在学校图书馆读书1小时无法识别完成

### ISSUE THREAD

**Issue by mark2330** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#278]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 说说你看到的汉化文本内容？

<img width="1045" alt="屏幕截图 2024-02-04 191248" src="https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/158816192/6c5c0b74-aead-4a44-acbe-01c673f3d13e">
已经完成任务仍无法上床

**Comment by Kagamine-Rinrin** [comment]
@NumberSir

**Comment by creeping1023** [comment]
1.5.0汉化也存在这个问题

原因是`$earSlime.event`存的字符串是中文的，而`widget "slimeEventEnd"`传的参数是英文的，导致`"跑步或游泳1小时".includes("running")`返回`false`而无法完成任务

解决办法可以把所有 `slimeEventEnd "\w*?"` 后面的字符串也汉化了

**Comment by creeping1023** [comment]
label应该需要换成bug

**Comment by creeping1023** [comment]
虽然 @NumberSir 在<https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/issues/266> 说解决了，但好像没完全解决？

**Comment by Kagamine-Rinrin** [comment]
> 1.5.0汉化也存在这个问题
> 
> 原因是`$earSlime.event`存的字符串是中文的，而`widget "slimeEventEnd"`传的参数是英文的，导致`"跑步或游泳1小时".includes("running")`返回`false`而无法完成任务
> 
> 解决办法可以把所有 `slimeEventEnd "\w*?"` 后面的字符串也汉化了

从目前已发现的且翻译好的源码里看确实已经修复了，你说的地方我记得男波色后来也翻译了。虽然这不是最好汉化的方法，但我搜了下判定就那么几个
应该没有漏掉。
不过现在发布的游戏汉化是建立在modloader的基础上的，之前遇到过一些奇奇怪怪的bug就是modloader导致的…
话说能发个存档么？分别测试一下使用和不使用modloader的情况下，是否能正常运行就知道了…

**Comment by creeping1023** [comment]
> > 1.5.0汉化也存在这个问题
> > 原因是`$earSlime.event`存的字符串是中文的，而`widget "slimeEventEnd"`传的参数是英文的，导致`"跑步或游泳1小时".includes("running")`返回`false`而无法完成任务
> > 解决办法可以把所有 `slimeEventEnd "\w*?"` 后面的字符串也汉化了
> 
> 从目前已发现的且翻译好的源码里看确实已经修复了，你说的地方我记得男波色后来也翻译了。虽然这不是最好汉化的方法，但我搜了下判定就那么几个 应该没有漏掉。 不过现在发布的游戏汉化是建立在modloader的基础上的，之前遇到过一些奇奇怪怪的bug就是modloader导致的… 话说能发个存档么？分别测试一下使用和不使用modloader的情况下，是否能正常运行就知道了…

[degrees-of-lewdity-20240207-202430.save.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/14193772/degrees-of-lewdity-20240207-202430.save.txt)
不知道具体是按什么方式修复的，至少我看`i18n.json`里的`<<slimeEventEnd \"running\">>`并没有翻译呀

**Comment by Kagamine-Rinrin** [comment]
啊这，看来是漏抓了。
回头改一下就好了。

**Comment by Kagamine-Rinrin** [comment]
> > > 1.5.0汉化也存在这个问题
> > > 原因是`$earSlime.event`存的字符串是中文的，而`widget "slimeEventEnd"`传的参数是英文的，导致`"跑步或游泳1小时".includes("running")`返回`false`而无法完成任务
> > > 解决办法可以把所有 `slimeEventEnd "\w*?"` 后面的字符串也汉化了
> > 
> > 
> > 从目前已发现的且翻译好的源码里看确实已经修复了，你说的地方我记得男波色后来也翻译了。虽然这不是最好汉化的方法，但我搜了下判定就那么几个 应该没有漏掉。 不过现在发布的游戏汉化是建立在modloader的基础上的，之前遇到过一些奇奇怪怪的bug就是modloader导致的… 话说能发个存档么？分别测试一下使用和不使用modloader的情况下，是否能正常运行就知道了…
> 
> [degrees-of-lewdity-20240207-202430.save.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/14193772/degrees-of-lewdity-20240207-202430.save.txt) 不知道具体是按什么方式修复的，至少我看`i18n.json`里的`<<slimeEventEnd \"running\">>`并没有翻译呀

我改了，这次所有的代码都换回了原版判定，只在显示任务的时候汉化。
话说求个史莱姆的档，我这两天刚好测试一下

**Comment by creeping1023** [comment]
> > > > 1.5.0汉化也存在这个问题
> > > > 原因是`$earSlime.event`存的字符串是中文的，而`widget "slimeEventEnd"`传的参数是英文的，导致`"跑步或游泳1小时".includes("running")`返回`false`而无法完成任务
> > > > 解决办法可以把所有 `slimeEventEnd "\w*?"` 后面的字符串也汉化了
> > > 
> > > 
> > > 从目前已发现的且翻译好的源码里看确实已经修复了，你说的地方我记得男波色后来也翻译了。虽然这不是最好汉化的方法，但我搜了下判定就那么几个 应该没有漏掉。 不过现在发布的游戏汉化是建立在modloader的基础上的，之前遇到过一些奇奇怪怪的bug就是modloader导致的… 话说能发个存档么？分别测试一下使用和不使用modloader的情况下，是否能正常运行就知道了…
> > 
> > 
> > [degrees-of-lewdity-20240207-202430.save.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/14193772/degrees-of-lewdity-20240207-202430.save.txt) 不知道具体是按什么方式修复的，至少我看`i18n.json`里的`<<slimeEventEnd \"running\">>`并没有翻译呀
> 
> 我改了，这次所有的代码都换回了原版判定，只在显示任务的时候汉化。 话说求个史莱姆的档，我这两天刚好测试一下

我之前回复里的就是接了耳史的跑步或游泳任务的档呀

**Comment by Kagamine-Rinrin** [comment]
> 我之前回复里的就是接了耳史的跑步或游泳任务的档呀
啊这，才发现你不是楼主。 尴尬

**Comment by creeping1023** [comment]
新版本可能修复了逻辑，但既有存档还是会有问题：现在的代码逻辑全是基于英语的，但之前的存档里已经保存了中文的变量的话，该任务会无法完成。
不过问题不大，只是跨版本的这一次任务完成不了，后面的任务应该就顺利了。

**Comment by Kagamine-Rinrin** [comment]
> 新版本可能修复了逻辑，但既有存档还是会有问题：现在的代码逻辑全是基于英语的，但之前的存档里已经保存了中文的变量的话，该任务会无法完成。 不过问题不大，只是跨版本的这一次任务完成不了，后面的任务应该就顺利了。

是的，所以我拿你的档一直没测（懒病发作）
