### ISSUE TITLE
对"索引数据库"(IndexedDB)的过度翻译

### ISSUE THREAD

**Issue by Lyoko-Jeremie** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#28]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议

### 说说你看到的汉化文本内容？

<img width="857" alt="2023-09-03 16_54_32-Degrees of Lewdity — Mozilla Firefox" src="https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/6566869/f4a56481-fc4d-45b8-9da1-76150c9e96ba">

在设置界面中的`启用索引数据库`设置存在过度翻译问题，没有猜错的话原文应该是`IndexedDB`

而`IndexedDB`这个词应该属于领域专有名词，我认为应该原样保留这个单词

### 有什么好的想法？

保留`IndexedDB`单词原文即可

根据原始项目代码中此处文本写的是 `Enable indexedDB`，  
我建议此处可以翻译为 `启用IndexedDB` 或者更符合中文语义的 `使用IndexedDB`。

### 其他内容

关于IndexedDB这个名词的MDN官方文档：

英文原版： https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API
中文翻译版： https://developer.mozilla.org/zh-CN/docs/Web/API/IndexedDB_API

在这个官方文档的中文翻译版本中全程没有对该名词的翻译，在全文中均保留此名词的原文。  
且在通常的日常使用中对该名词的阅读、交流也使用原始单词进行。

考虑到用户在设置此选项时，如果无法搜索到其含义，可能会无法理解或产生误会，因此我建议保留此单词不予翻译。

**Comment by Eltirosto** [comment]
已改，请等待新版本发布
