### ISSUE TITLE
[0.4.5.3-chs-alpha1.5.0] 在线选择界面选定模式后无法开始游戏并报错

### ISSUE THREAD

**Issue by rainfall1019** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#280]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

使用的在线汉化版普通模式，无其他mod加载，在做完分裂成就后回到神殿左侧人物处弹了几个报错，刷新界面后无法回到游戏。因此没有得到报错时的存档很抱歉，只有mod管理器导出的所有数据，但因为大小为58.6mb，超过上限无法随帖子上传，这是我的两个使用中的邮箱，可以向我发邮件要求得到所有数据     1924336213@qq.com     332700wyq@gmail.com

### 存档 / 代码

[Uploading Import Overlay.twee.txt…]()
无法得到报错时的对应存档，很抱歉。这是saves export文件夹里的 twee 类型的文件，我以txt格式将其导出并上传

### 截图

<img width="914" alt="屏幕截图 2024-02-07 022959" src="https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/159181146/8f6592f4-9b4a-4d22-8870-c80055cd3bdf">
<img width="921" alt="屏幕截图 2024-02-07 003958" src="https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/159181146/0160ebd2-07b9-424a-af60-48fc4347b364">

### 还有别的吗？

没看懂上方报错，因为报错提到了数字20，我打开了选项，性能页面，调整 历史记录回溯功能，但关闭并应用无法生效并使上方不断报错，调回最初的 历史记录回溯功能 设置并关闭也无法恢复正常，点开存档界面无法保存存档与读档，刷新页面后再也无法进入游戏界面了

**Comment by NumberSir** [comment]
只用传导出压缩包里的 `ModLoaderLog.txt` 就行了。
第一张图的问题是因为你启用了安全模式，需要先把安全模式关掉：
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/52584526/e1a9418e-55ec-4199-b528-9d7ecf382dbc)
