### ISSUE TITLE
[0.4.5.3-chs-alpha1.5.0] 衣柜快速着装bug

### ISSUE THREAD

**Issue by DachuiWong** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#281]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

当在衣柜把浴巾保存为一套着装的时候，快速换装会出现上身无法覆盖，这个bug存在了非常多个版本。
截图使用的是新开存档，只穿浴巾，覆盖睡衣，快速换装睡衣。有其他服装配件的时候情形相同，但是手动在衣柜里换就没事。

### 存档 / 代码

N4IglgJiBcIQpgcwE73gZwLQHsBmmAbeAdwjABcBPEAGhHXIENz4ZQwA7BADxgAY66NFFgBEgMMAdXADmA/wFKAnwC3JAVz58AjABZ0GrToCLAMcM6+0AL0BKAKEBzgBIABAJcBogH19XFvgAjAEeAEIBw7AAvAFuAOQApAAeAF4AVgEOAAbSAKwBlgA00gCiLbQA2AAcAEoATgGqAFoBOgFHAgArJDgAOz2MAUgAigFS5AD8ACIBs8oBjAE2FADcAXLSAKh7TAHTyvjiAY4AOACEAa4UZAHKIAGpgAH4jlYBB8sCAO4BfiqiAMG2KoAdamKwAygBW+wALrAAAIAEsAFU+AGYvioAK8AHYAOQAmABlEIANdJyrgIAFCdIAB8ARRKzhKADeAoFcQBCLLc0YAOoAI0iEdxygBWGYAU4As1kADcZTwABOGADIADEAHug3AASQBV8QAYoC8HpAFkAPNJOTGDi7fIAMWscRUa0kyFcAHYFCiAH8AK4AetKQ9wAP4xACSVWQAFUAD4AWIAvty5G1TAAUgBpAE4ABM1SUAeJoFzTABEAEoKn3BADT3JUAC0puV0dqABZpSWjFLS3oAL4ADQB1UQAA4AfAB9MBvYjwACN5QqKw4AIAogBKzkBdHGXBNQa0ODwAhMGAAbVA5AoRBgIAnjGQEGQ2ECrDoK3fYCMIERDoGwIDzmwaZ0FUjDoOgjCIPAAAKqArC+ZzwJ+2DYAAtheMFwQhrCwG+H5fj+F5MIgoHQLeIDwNwFAAMI9vA8wANZnJQBGgQAunQj44fAEJMDhVT8HQ2BVI+2AcDRoAcPAKzwMgcTqAglrwBw6g0bgjAEEIdCMOo5DYPBynVmA8HAZhMB6QZ8CCD22DEExjDSWAskogx5AwOQyDqI59CQPAgTvrWWkIKgyAvvMjAcP+oGCCFYXICJzA0XAVlAUQUDJQgqUomAQkvmQ1m5Re8y4WF5BMbJ/nYAZL7IIwZDYJR76IeQACa2DqMgQgELgdn6YZ9DzF+BAEBFQk4T+MXQPZY04e5lrYMpQkcL50D+YFdArVUAAySCMPM1CLaNQUHZa77sSpumXft7kolJI0OXQxVETR2h0FVc3MDGK2Id9dCBNgECUMQyAUJwiCA19fkBUF6BgAQzmBeQLA7hwOW2TtSMCfFgOINjuMiLtQVMBwHCw6TNnkwTwUFe+ACCNMrTJcmI3tIDAZw7G0zj9Pc0Ff01Wzn2cw970gD2+m4ExBBmZhdMVRdMvzHLLXzCwyCHWAiA9uQqt4xTdAEAbRsQlU2DkBbhvbXwAB0hLm5b5AAOItWQWmO07P0gPbRse0rxD8P7bsO86BDMBJgfu3V/1+678cOyizp1UrC3OynK3cOlLAgyA2lia1b1jYpxCkVhP4iZQz74zzOnwHE75fsQN3IHd21LcjAtVAXVmPvM6B1RwuBgMgHOeRw5fI85xDVqF6iIBFXAqSpc/QfAVRVCp1stZQlnoFUMfnfQ8aMJQSUgFVXC4egx+n1fL4MPFEDvnlt9K0IZwmaZHA1qBFRsRXudAojYTwtAbQWg6Al3mmAXAlB5xaTJjAAOgkMBUAbiAHCqMKDvmoJJAgEB5hKw4lvEAj4qhlVxi+Ya0FYLwUQnVdQW1SrZWFtBM+mDKH+UYBQAA8spZAZ9nTYCnrHWATAbIXgKivWhsjpFyOYPAcRkjtr0Q4JgD2ZxKqyQnlPSy+lsCIATDbDgKIgKK2VnPKC9AmDIHINWVRMAKjoh9AWH0JwfSVFgZeQIK847flyGxcgAA1e6M8wLqBoaomx5BWI0UJAWOguB4AZXQXQYgn9yIYBgCneYOlTI4UzhImiug6BsL+rgCRMiG4pxPmxQCBB5xkNtkkmAEpfpywYBQc66JBACw4GUhaAd4yoI4GdQRgRQk6wijBSeBT9rN3UDhNmj4ACOgUaKpOLlUeYCTOnQKMuzZgM8i4TMQDjKZlAWYrGwJAeK8xiIB3/IgTgjAJzwHIIpOCMBBkgCuTcs6zowC8BOSAXA/UabkH6sRdE9jzLwEiQNC5d4QDO10E7CUTt0SYAABSaywPpKocttA4qdnwWwIB+LFzWQgpBKChZqwDjHBg1c8kQiVpo2Je8Yp0EQIwWa4NiLFwkStAgF5OANTjnC0y0N9Jx04BQDgBy/owUfMAi2VAsnfw6bDecsSP4sD1TBFqKMWBGriaayFar5ityEhAVFKNZLLP1Ykw18DN7QMBc/SgPrQCIXXgtKFF4hAQrDUZXeGSWpTOIgIIFWkrJx3eZ8uOe8aZwTAFEV5oNUCwXICjXNccwaYwfjmhNoN9IGWLVWoFX4OB9VntARN8ZZLNvkrLetPYU2tvscGqK84wYQxfIwfR98oFgJACsSeHzYXnVAPFJVjcgoSJXWbJNNMG6brTTjKVq6BLwDEg3adcsuDORIbDEWdABb/NXfYkd9cwDbMgGBRSFDoBBuwnHIQm044fscfwex0MHbvigd+9qrbBDHq0gBsJ75gPm3gLgRxEGQCIB/dB+gsGW2JsA4h/tAle2GzAphqDia/1wewwR7Oj7bYlLI1hyjuH4M60I3wexcKcI4UXRh5jMH/00YQ3RnpWCmMUcE9R/DImkNQtOsRSDv7WPCfY6J2WAiFpKew1RvDcDZNEahWgba2mWNCZk2puTe7GB9SLSFCTynzP6cs4Z6zDmdMqYs0Bwzma+2mak3p4uBnOOnJ0u5sz0nnPeZC7g2zPZwsBbY9FtM9jODKS2hIvjEbTLX0gr9WSEAH6QUfTW9AO5GIMEobgVAHEQKUMHSpec7k97vmeWKvCgrIqNea7Gtr849I63KXeUA6S8E0wXXHAbCqXyABZNQAi8qAH9UwAZXogCgiN49KqJvYamxIl8gBj5UAEV+q2aDrbGyq3V23TrTdgIAHndACO+sd07m3+mTau7t2AgBrd0ANvWgB4wMe0Zs7W3E07dDYAZXlADR6v90bz2LuYALCnEHL5AAxAYASIC5uAD74qHG3xsvcu4N0NgB/zUAP1KBLuDaEAAdqgBb6MAOGmgAAo0AL8BgAYAMAOVygB8V0ACFugAJU0ADnmNK1sA5h+dYHb3Q2ABS0wAAu6AGMIwAsOaAH05engBod0AAxKgBkfMAO6xWPAe4+F/jl8EuZfy+V4AZzlAD8RoAck1ADwOprwXr3dewEAAOBgALhIJXwQY7PAD3yoAQcjADhznzk7AuccXZ19dkAgA4M0AHxm7PADVcaDwAQbaADI81bdLoeB/OnDlODXkBNZja1+N85iAUHRuQec60VIrkI1GjDXWs89dzy8/PhfbMl5EeXrPIOaL3gD+doXaSRezcWyt/nKfu+25D4d63qfR/vZAPdifI+8ch++39of2P5/B+nxDufW30+97tyAVHGOt/a93yH4npOKc04ZyzjnPO/dPcnwv6fgBoOUAKMRR+LvogqOvsXUu5eK9VxrivlrrDhKN/i+IAB8RgATOns6m7v497yZ75e7R5x6J5pjJ6r4LoN6JJN6l7ICt4FLaAnCdYhrzg2wMDwovizx/gISfLlZDw3pbpWR0GVbqxjT8ovJgDKQQDDoFoMB1oZoqQcFcHDoMYVolqGZhRCBxBIRMRgS+Y0SJpubYaBC8FFoIDoDzBxyazibYYxzsacxxxECobnoiCJqgZGwmFxzxRhbYY4RxZxyZ5xzqETRgAeRurbbqBTRLwaHQxuGBacBCBFLQxB7QSNrNoZphFsJdqsRxy9oKH2LyH8HKGqFJGJplolKpHVpTTZriFtrJroDOGlqqGFHYasT6SJKxEZLXg9h5y/rDJVRKz9RypoCBatSeGOwfRbRfi/p7xsQ9jyEYBxR7w9FoCazWaDHuT1pNJ9HWFCAaGTFyrcRTFUwvJxx2FyS6xWE6ycEJr2LSFMT6wsGd6ayFq46gDyEvgXhKEgAXizGXH2LkLnLuHABIoCzZF5YNodpREfH8IUAd68T84nF9IXbnH5GXHUHzrjqwC3HaSZTHaBzYBxQGFfqvGoxNQomhFfFcwYlUItR/F3gAn+5AmPggmMFwkQnprQmhZwkPGIlPEtovFDJonyQJGRHYmMm4kCJFoEmAm9Ikl8YXFUkzo0E4zgkgB3HQm0lInRI4noBvHokcntpNrfE4m/Hcm0SEmgDElnFklinXEwk2E3FSn0kfFynMkfFKmdo/F4nqm3iam3x8k6mCk3EUmilCkSlGnmx0nIkclmnvE4mWkqkclqn/FoF0AYSFqHHbR0SFaICVSxzQQGwXjECNQMJwCNRkqcAXgWxRCfwXg/iIagzYCFm3wFpwqoAXjOQDS/hQrYC8B0ByzEDsT6JhyCBVAhQxR0r2pRkuoykpz7GOrESd7OntKJK2SulQniqKQXiOGwAdaXg+GuHIkgD3IqREJUJPhiqBIox/LoArRUHgByRsT9S44gDl7NmYnKktq4L4T5FJF+r5ElEgCABZyoALOJKOgASxb5miE4SZG8ylZ/kqEZJ8GVpFHAXkBPlG4zb5kpGQXQVMlTKNR9ShrEC9qmpHqRbikQDtF6rnbKpdGSZUJLEvg9hrLxSUQBQsGJpKzKROG4SGHFJxwtSIS/pMC2oumclkVxzwABplJNGwDCrzSVmaZ8WhpBzkAqEuQHnamknOlXEimTkGk0lwLCovirnIDrlVAnkhG3wSIBR+ERFIAgqLqslGXPJ3IPJPLxpdKKFzrz5Lr7oMHroHrTq+anqPTCmQkuUeUmGXpkAcBxmsGUzHqnygIeV3rSxCCslYnRFiqABrcpWX2iAAlQ2fdC+ClbLMVOlYlb+VeMNLAHFYAFeBgAj7oXj7kviADsroAF1y3558FVgAltplXUYgDVWAA3cqtvzs6U2tORObFDyqxF/LOZXs4b4cuWcAIkQOuSSTgnFKgEwHdAKoeYEdpefOefhGyfQreVmn+fIU+d1TWekWIfWmFNkYBSkaBdAD6PmuBU+YAKoeZuMBJuMF4FBRgxL491j14a9RSF/FZ5aFN

### 截图

![Screenshot_2024-02-08-00-27-57-785_com vrelnir DegreesOfLewdity](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/159290679/42067445-1386-43aa-8ef8-8b195b0fe146)
![Screenshot_2024-02-08-00-28-04-478_com vrelnir DegreesOfLewdity](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/159290679/dc52b00f-2846-4570-86b1-1a11a2e715ae)

**Comment by NumberSir** [comment]
非汉化版错误，这是由于浴巾和普通服装有不同导致的
