### ISSUE TITLE
[0.4.5.3-chs-alpha1.6.0] [错误：未能定义代词到"He" ]

### ISSUE THREAD

**Issue by Paul-16098** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#282]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

当前版本号:
0.4.5.3-(chs-alpha1.3.0) -- 0.4.5.3-(chs-alpha1.4.0) -- 0.4.5.3-(chs-alpha1.5.0) -- 0.4.5.3-(chs-alpha1.6.0)
从版本中保存加载: 0.4.5.3-(chs-alpha1.6.0)

---
`
0.4.5.3-(chs-alpha1.6.0) Error (:: Street Private Show Strip): <<person1>>: cannot execute widget: 0.4.5.3-(chs-alpha1.6.0) Error (:: Street Private Show Strip): <<personselect>>: cannot execute widget: 0.4.5.3-(chs-alpha1.6.0) Error (:: Street Private Show Strip): Undefined NPC in personselect 0.
<<person1>>
`

### 存档 / 代码

[degrees-of-lewdity-20240211-115915.save.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/14231223/degrees-of-lewdity-20240211-115915.save.txt)

### 截图

![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/127955132/1d6e709e-3b5a-4b95-9a57-0777d6998289)
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/127955132/548fcdd5-20b2-4f34-9f2c-409ba4f4fe51)
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/127955132/14a4733f-462a-4bc0-8637-52b78cb7c5f9)
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/127955132/da58f0b9-c445-490f-804b-477ed4bae690)

**Comment by Kagamine-Rinrin** [comment]
感谢反馈，
不过用英文版读取也会发生这个BUG，可能是原版的BUG。
可以反馈到作者的discord或者仓库博客里面哦~

**Comment by Kagamine-Rinrin** [comment]
话说这个吊带袜天使风格的人物预览mod发布了么~
之前在贴吧上看到觉得挺好的XDDD

**Comment by Kagamine-Rinrin** [comment]
啊！不对~！应该是mod的问题
我在未加载MOD的汉化版中，使用你存档的返回功能返回到上一步
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/43258604/aae461bb-c229-4c5c-8613-7a8a3952243d)
选择选项后一切正常，并没有出现你图里所示的BUG。

所以我推断是你使用的某个MOD出现BUG导致的问题

**Comment by Kagamine-Rinrin** [comment]
你可以排查一下是哪个MOD引起的BUG
然后反馈给mod作者
