### ISSUE TITLE
[0.4.5.3-chs-alpha1.6.0] 聖誕節孤兒院劇情報錯

### ISSUE THREAD

**Issue by ruuu219** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#283]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

問題：送羅賓聖誕禮物後的劇情無法執行
遊戲版本：0.4.5.3-(chs-alpha1.6.0)

### 存档 / 代码

[degrees-of-lewdity-1st-20240212-033548.save.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/14233770/degrees-of-lewdity-1st-20240212-033548.save.txt)

### 截图

![Screenshot_20240212-031222_Chrome](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/159724529/1d7b20a9-b015-4dc0-98f1-5dfe693874ce)

**Comment by Kagamine-Rinrin** [comment]
谢谢反馈。
<<he>>少了个>，已修复~

**Comment by Kagamine-Rinrin** [comment]
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/43258604/666ead74-0a90-466e-9188-0364f00f50ac)

**Comment by tichdiji44** [comment]
![Screenshot_20240213_224331_com microsoft emmx](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/46858077/0421a875-da64-4551-b5d0-7fd1fb497152)

在线版还没有修复

**Comment by Kagamine-Rinrin** [comment]
请等待在线版更新。
