### ISSUE TITLE
[0.4.5.3-chs-alpha1.8.0]学校中触发惠特尼寄生虫事件发生错误

### ISSUE THREAD

**Issue by morrisan428** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#287]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

在线版游戏在学校中进行到惠特尼寄生虫这个事件时发生错误，无法继续

### 存档 / 代码

[degrees-of-lewdity-20240225-000929.save.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/14393511/degrees-of-lewdity-20240225-000929.save.txt)

### 截图

![IMG_2899](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/161073293/f756e435-9d6c-4e21-b8b5-85c29eaf06fe)

### 还有别的吗？

之前在线版都没有出现这种事件无法加载的问题，我也试过避开但是似乎是这个事件是这个阶段在学校里必定会触发的，只是早晚问题，麻烦看看谢谢

**Comment by kateW223** [comment]
我也有這個錯誤,完全躲不掉 
![Uploading 螢幕擷取畫面 (1833).png…]()

**Comment by bogayalo** [comment]
同樣的問題
樓主的擷圖就是我在選反抗選項遇到的狀況(第三張圖)
如果選同意則會像第二張圖
另外
選反抗後 在戰鬥也會遇到錯誤
但忘記把它截下來了
麻煩大大們請使用下面的存檔碼測試了
謝謝
[dol錯誤存檔碼.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/14395911/dol.txt)
![Screenshot_20240225-172031_Degrees_of_Lewdity](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/161203658/df204535-a509-4448-8e23-db9b4ac28a16)
![Screenshot_20240225-172050_Degrees_of_Lewdity](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/161203658/18ccab1c-13f3-4c3b-83f2-516b1917509b)
![Screenshot_20240225-172104_Degrees_of_Lewdity](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/161203658/38b78828-d0b9-4d54-968e-e8819a030010)

**Comment by Alfafar** [comment]
我也遇见了这个错误，尝试战斗和逃跑，无论成功或者失败都会进入错误，我现在学校内只能靠进入卫生间、SL来规避这个霸凌事件

**Comment by Kagamine-Rinrin** [comment]
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/43258604/3950dfff-5f62-4562-9c8c-bf8a3e5c2143)
haoqiguai好奇怪，我这边的版本读出来你的档是正常的。

**Comment by Kagamine-Rinrin** [comment]
> 同樣的問題 樓主的擷圖就是我在選反抗選項遇到的狀況(第三張圖) 如果選同意則會像第二張圖 另外 選反抗後 在戰鬥也會遇到錯誤 但忘記把它截下來了 麻煩大大們請使用下面的存檔碼測試了 謝謝 [dol錯誤存檔碼.txt]

你的档我这边读也是正常的
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/43258604/197e6bce-cb8f-4fcd-a823-b0c0c16b6dca)




我怀疑是不是某个最近已修复的BUG导致的

**Comment by Alfafar** [comment]
> > 同樣的問題 樓主的擷圖就是我在選反抗選項遇到的狀況(第三張圖) 如果選同意則會像第二張圖 另外 選反抗後 在戰鬥也會遇到錯誤 但忘記把它截下來了 麻煩大大們請使用下面的存檔碼測試了 謝謝 [dol錯誤存檔碼.txt]
> 
> 你的档我这边读也是正常的 ![image](https://private-user-images.githubusercontent.com/43258604/307709829-197e6bce-cb8f-4fcd-a823-b0c0c16b6dca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NDE3MjUsIm5iZiI6MTcwODk0MTQyNSwicGF0aCI6Ii80MzI1ODYwNC8zMDc3MDk4MjktMTk3ZTZiY2UtY2I4Zi00ZmNkLWE4MjMtYjBjMGMxNmI2ZGNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDA5NTcwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjMTI0NWM3OTI0MjM5MTZhYjUzNmM5ZDY5NDRmM2MyMzM2NmY0YzE3NGE1YWM2NDZmY2FjNjAyM2JkYmRhNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AQeWKkPCjLjiJYHv-NI4fPDMo0ZOa8YlEBr6I9qAZWw)
> 
> 我怀疑是不是某个最近已修复的BUG导致的（划掉） 我的版本是23日编译的… 看你们玩的版本是24号发布的。
> 
> 这期间发生了什么奇怪的事情么,还是说在线版有啥问题,或者说是I18N的锅? @NumberSir

[degrees-of-lewdity-20240226-182442.save.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/14403175/degrees-of-lewdity-20240226-182442.save.txt)
可以也试试我的吗，我的版本是0.4.5.3-v2.16.0

**Comment by Kagamine-Rinrin** [comment]
> > > 同樣的問題 樓主的擷圖就是我在選反抗選項遇到的狀況(第三張圖) 如果選同意則會像第二張圖 另外 選反抗後 在戰鬥也會遇到錯誤 但忘記把它截下來了 麻煩大大們請使用下面的存檔碼測試了 謝謝 [dol錯誤存檔碼.txt]
> > 
> > 
> > 你的档我这边读也是正常的 ![image](https://private-user-images.githubusercontent.com/43258604/307709829-197e6bce-cb8f-4fcd-a823-b0c0c16b6dca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NDE3MjUsIm5iZiI6MTcwODk0MTQyNSwicGF0aCI6Ii80MzI1ODYwNC8zMDc3MDk4MjktMTk3ZTZiY2UtY2I4Zi00ZmNkLWE4MjMtYjBjMGMxNmI2ZGNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDA5NTcwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjMTI0NWM3OTI0MjM5MTZhYjUzNmM5ZDY5NDRmM2MyMzM2NmY0YzE3NGE1YWM2NDZmY2FjNjAyM2JkYmRhNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AQeWKkPCjLjiJYHv-NI4fPDMo0ZOa8YlEBr6I9qAZWw)
> > 我怀疑是不是某个最近已修复的BUG导致的（划掉） 我的版本是23日编译的… 看你们玩的版本是24号发布的。
> > 这期间发生了什么奇怪的事情么,还是说在线版有啥问题,或者说是I18N的锅? @NumberSir
> 
> [degrees-of-lewdity-20240226-182442.save.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/14403175/degrees-of-lewdity-20240226-182442.save.txt) 可以也试试我的吗，我的版本是0.4.5.3-v2.16.0

![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/43258604/6efcca79-7cb7-4438-876f-6e2e78a6ac13)
 
我这边依旧正常，也许是I18N的问题？ 不过暂时还不好下结论。
可以麻烦你排查一下么？卸载掉其他mod看看会不会报错。
顺带一提可以给下你报错的截图，或者错误码么？

**Comment by Kagamine-Rinrin** [comment]
> [degrees-of-lewdity-錯誤1-20240226-211127.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/14414504/degrees-of-lewdity-.1-20240226-211127.txt) 我的也是同樣錯誤 我讀上面其他人的檔也是出錯 @NumberSir

![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/43258604/a8fc9639-8f7d-4d86-b2ff-4dad75f6343a)

我这里读取你的档也是正常的呢，
可以麻烦你排查一下么？卸载掉其他mod看看会不会报错。

**Comment by kateW223** [comment]
> > [degrees-of-lewdity-錯誤1-20240226-211127.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/14414504/degrees-of-lewdity-.1-20240226-211127.txt) 我的也是同樣錯誤 我讀上面其他人的檔也是出錯 @NumberSir
> 
> ![image](https://private-user-images.githubusercontent.com/43258604/308090129-a8fc9639-8f7d-4d86-b2ff-4dad75f6343a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMjcxNDUsIm5iZiI6MTcwOTAyNjg0NSwicGF0aCI6Ii80MzI1ODYwNC8zMDgwOTAxMjktYThmYzk2MzktOGY3ZC00ZDg2LWIyZmYtNGRhZDc1ZjYzNDNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDA5NDA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkNGIxYWVlMjRhMzdkYjQzOThkNzljM2Q4ODFiZjdiZDI3NDg1NzBkMjNlZTBmMjlmZTBkZjAzNTA0N2QyZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.igiZJQbyzS3FcVAZBScYNkxUIteS4OCvciGH0Xhq82M)
> 
> 我这里读取你的档也是正常的呢， 可以麻烦你排查一下么？卸载掉其他mod看看会不会报错。

我沒裝過mod
