### ISSUE TITLE
[0.4.5.3-chs-alpha1.8.1] 戴著羽毛发夹 還是天使化錯誤

### ISSUE THREAD

**Issue by kateW223** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#290]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

在線版一到半夜12點 我的哈比化就會強制變成天使化 即便是戴著羽毛髮夾都沒用 之前沒有這個問題

### 存档 / 代码

[degrees-of-lewdity-20240301-202338 錯誤.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/14461005/degrees-of-lewdity-20240301-202338.txt)

### 截图

![螢幕擷取畫面 (1873)](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/138902219/33d6b8f4-ded6-42f6-a5f6-48c3f07d141c)

### 还有别的吗？

嘗試過更換髮夾,全身脫光等 但還是會強制天使化 (上方存檔是接近半夜12點) 被強制天使化之前

**Comment by mirrormirroronwall** [comment]
看统计，哈比转化只有28，过0点小于30就会这样

**Comment by kateW223** [comment]
> 看统计，哈比转化只有28，过0点小于30就会这样
好的 謝謝
