### ISSUE TITLE
Mac无法导入mod

### ISSUE THREAD

**Issue by 1diotDoomSpira1** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#294]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这既不是对游戏报错的反馈，也不是对汉化文本改进的建议

### 说说你遇到的问题？

Mac下载zip文件后会自动解压，再压缩回zip文件导入mod管理器后，显示Error: bootJson文件 [boot.json] 无效

**Comment by NumberSir** [comment]
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/52584526/ef7f588f-138d-4390-a492-658f0111ea0d)

请确保压缩包根目录结构如图所示
