### ISSUE TITLE
[0.4.5.3-chs-alpha1.11.0] ①贝利台词/②凯拉尔庄园神龛/③裸跑（多伦）/④隐藏转化文本相关

### ISSUE THREAD

**Issue by 404bako** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#295]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 说说你看到的汉化文本内容？

可以直接贴内容吗？有些是看文本的时候偶然发现的，没有对应位置的存档和截图。

①        "f": "\"Alright, you little shit,\" <<he>> growls. \"If it'll shut you up, I'll **throw you a bone**.\"",
        "t": "\"好吧，你这个小混蛋，\"<<he>>低沉的嗓音说道。“如果这能让你闭嘴，我就**给你一根骨头**。”",
        "pos": 796,
        "fileName": "main.twee",
        "pN": "Bailey Office Seduce"
【这里的“throw you a bone”有对应的俗语翻译“给某人甜头/可怜某人”。】
②        "f": "In front of you stands a bizarre **monstrance**, almost as tall as you. Numerous spikes of silver and bronze surround a central space, giving the impression of a sun. The metal at the top is distorted, as if someone has hacked part of it off. Bronze tendrils emerge from the base, running along the lower half of the spikes, licking them.",
        "t": "在你面前矗立着一个奇异的**神龛**，它几乎和你一样高。无数银色和青铜的尖刺环绕着一个中央空间，就像是太阳一样。顶部的金属被扭曲了，仿佛有人把其中的一部分给砍掉了。那青铜卷须从底座冒出，沿着尖顶的下半部分盘绕着。",
        "pos": 425,
        "fileName": "manor.twee",
        "pN": "Manor Kylar Secret 4"

        "f": "<span class=\"green\">You recognise it from history class.</span> \"It's a host for sacramental bread,\" you explain. <span class=\"gold\">\"The temple might know more about this one.\"</span>",
        "t": "<span class=\"green\">你从历史课上认出了它。</span> \"这是供圣体面包的**圣餐台**，\" 你解释道，<span class=\"gold\">\"或许神殿里会对这个有更多了解。\"</span>",
        "pos": 853,
        "fileName": "manor.twee",
        "pN": "Manor Kylar Secret 4"

        "f": "The <<bishop>> is silent for a moment. \"Jordan was mistaken about the **monstrance**. Our good priest did not err, however. This is not for them to know. Their soul is pure.\"",
        "t": "<<bishop>>沉默了一会儿。\"约旦对那个**神龛**有什么误会。不过，我们的好司祭并无犯下罪行。他们不应当知道这些。他们的灵魂是纯洁的。\"",
        "pos": 13,
        "fileName": "events.twee",
        "pN": "Street Monstrance 2"

        "f": "\"I was told you made an inquiry, about a certain <span class=\"pink\">**monstrance**?</span> You found it in a manor. Tell me, what do you think of the inhabitants? Do they not frighten you?\"<<gstress>><<stress 6>>",
        "t": "\"我听说你对某处的<span class=\"pink\">**神龛**</span>进行了调查？听说它是在一个庄园里的，能告诉我那里的居民是什么样的人吗？他们有没有吓到你？\"<<gstress>><<stress 6>>",
        "pos": 22144,
        "fileName": "widgets.twee",
        "pN": "Widgets Events Street"

        "f": "<span class=\"blue\">You recognise <<him>>.</span> <<Hes>> the <<priest>> that told you about the **monstrance** in Kylar's manor.",
        "t": "<span class=\"blue\">你认出了<<him>>。</span><<Hes>>是告诉你关于凯拉尔庄园**神龛**的那位<<priest>>。",
        "pos": 1176,
        "fileName": "confess.twee",
        "pN": "Temple Confessor Intro 2"

        "f": "<<askicon>><<link [[\"Inquire about the **monstrance** you found in Kylar's manor\"|Temple Kylar Monstrance]]>><<set $kylar_manor_secret to 2>><</link>>",
        "t": "<<askicon>><<link [[\"询问你在凯拉尔庄园发现的**神龛**\"|Temple Kylar Monstrance]]>><<set $kylar_manor_secret to 2>><</link>>",
        "pos": 3580,
        "fileName": "main.twee",
        "pN": "Temple Jordan"

        "f": "Jordan listens to your description. \"You were in that house?\" <<he>> asks, ignoring the **monstrance**. \"My child, I must caution you against returning. That building is considered profane. It is unsafe. Please open your mouth.\"",
        "t": "约旦听了你的描述，问道：\"你进过那栋房子？\"<<he>>无视了**神龛**。\"孩子，我必须警告你不要再回去。那栋建筑被认为是亵渎的。这是不安全的。请张开你的嘴巴。\"",
        "pos": 26,
        "fileName": "main.twee",
        "pN": "Temple Kylar Monstrance"

        "f": "You open your mouth. Jordan examines the interior, and sighs in relief. \"You are untainted,\" <<he>> says. \"Forgive my intrusion.\" <<He>> incants a quick prayer. \"As for the **monstrance**, I doubt it's of significance to the temple. But thank you for bringing it to our attention.\"",
        "t": "你张开嘴巴。约旦检查了一下你的口腔，然后松了一口气。<<he>>说：\"你没有被污染。请原谅我的侵扰。\"<<He>>快速地念了一段祈祷。\"至于这个**神龛**，我怀疑它对神殿来说并无太大意义。但还是感谢你把它告诉我们。\"",
        "pos": 13,
        "fileName": "main.twee",
        "pN": "Temple Kylar Monstrance Open"

        "f": "\"Forgive the violation,\" <<he>> says. <<His>> voice shakes with genuine shame. \"I must follow the precepts.\" <<He>> incants a quick prayer. \"As for the **monstrance**, I doubt it's of significance to the temple. But thank you for bringing it to our attention.\"",
        "t": "\"请原谅我的冒犯，\"<<he>>说。<<His>>的声音因为真诚的羞愧而颤抖。\"我必须遵循教规。\"<<He>>快速地祈祷了一番。\"至于这个**神龛**，我怀疑它对神殿来说并无太大意义。但还是感谢你把它告诉我们。\"",
        "pos": 465,
        "fileName": "main.twee",
        "pN": "Temple Kylar Monstrance Refuse"
【这里的“monstrance”翻译成“神龛”和“圣餐台”个人觉得都不太准确？毕竟游戏里另外还有几处正确的神龛（凯拉尔柜子、荒原祈祷etc）。monstrance有中文名叫“圣体匣”。】
③        "f": "Doren double-takes, **staring back at you** in disbelief. <<if $player.gender_appearance is \"m\">>\"Lad?<<else>>\"Lass?<</if>> Is that..? What are you doing?!\"",
        "t": "多伦两眼放光，难以置信地回望着你。<<if $player.gender_appearance is \"m\">>\"小伙子？<<else>>\"小姑娘？<</if>>那是……？你在做什么？！\"",
        "pos": 3057,
        "fileName": "run.twee",
        "pN": "Park Run NPC Show"
【这句话或许应该是“多伦愣了一会才回神，难以置信地盯着你”而不是“两眼放光”？】
④        "f": "Hiding parts of your Inner Self will slowly increase your Trauma over time (excludes pubes and **pits**).",
        "t": "随着时间的推移，隐藏你的自我会慢慢地增加你的创伤（不包括阴毛和**雀斑**）。",
        "pos": 75656,
        "fileName": "mirror.twee",
        "pN": "Widgets Mirror"
【之前在issue285提到的“pits”还有一处没有修改成“腋毛”。】

**Comment by Maenoko** [comment]
为什么神龛不对

**Comment by NumberSir** [comment]
> 为什么神龛不对

神龛有对应的 shrine 了，和 monstrance 的图片差得确实挺大
