### ISSUE TITLE
[0.4.5.3-chs-alpha1.12.0] 统一用词：成人用品店/成人商店

### ISSUE THREAD

**Issue by creeping1023** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#299]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 说说你看到的汉化文本内容？

同样是`adult shop`，有的地方是`成人用品店`，有的地方是`成人商店`，是不是统一一下比较好？

**Comment by NumberSir** [comment]
已统一成“成人用品店”
