### ISSUE TITLE
robin可以翻译为知更

### ISSUE THREAD

**Issue by Raven-233486** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#30]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议

### 说说你看到的汉化文本内容？

skip

### 有什么好的想法？

罗宾给人的感觉太男性了，第一反应如“罗宾汉”的简称
robin是知更鸟的意思，如果翻译为“知更”，给人的感觉更中性化

**Comment by Lyoko-Jeremie** [comment]
![图片](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/6566869/a8f05ca1-d807-4321-94eb-28880e373ad1)

我觉得应该没错，内存里的Robin就是男性，穿着男性服装，有巨大肉棒，所有的称谓都是男“他”

**Comment by Eltirosto** [comment]
> ### 在提问之前...
> * [x]  我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
> * [x]  我确定这是对汉化文本内容的建议
> 
> ### 说说你看到的汉化文本内容？
> skip
> 
> ### 有什么好的想法？
> 罗宾给人的感觉太男性了，第一反应如“罗宾汉”的简称 robin是知更鸟的意思，如果翻译为“知更”，给人的感觉更中性化
> 
> ### 其他内容
> _No response_

我们在为 NPC 名称确定汉化时曾考虑过两种方案，一是实现根据性别不同使用不同的中文名称，由于需要改动过多放弃了。现在使用的是尽量偏中性化的名称，且在翻译所有人名时均使用音译而非意译。

游戏中已出现的名称与将会出现的名称共有 114 个，不可能为了使名称完全中性化而逐个意译，否则只是本末倒置。
