### ISSUE TITLE
[0.4.6.6-chs-alpha1.0.0]小巷遭遇惠特尼，选项中惠特尼加支配没有名字

### ISSUE THREAD

**Issue by dufy2000** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#309]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 说说你看到的汉化文本内容？

![PXN}5`C)OJ9RT2K)HSOP@WH](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/153524367/8b8856f2-8793-45e2-b06e-70e2e531589d)
[新建文本文档.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/14885918/default.txt)

**Comment by NumberSir** [comment]
![09c08926fdf55d600da8674a593cb1b3](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/52584526/2c9b6e7e-b05b-44f9-a39d-6ee812073bb4)
开发者自己也没搞清楚哪个该用哪个

**Comment by Kagamine-Rinrin** [comment]
翻译的问题，“的”字的位置没有放对
原版这里也不显示“惠特尼”的。
（排查了半天…本以为应该显示人名，直到我原版载入了一下存档……）
