### ISSUE TITLE
[0.4.6.6-chs-alpha1.0.0] Robin's ROOM不能进入

### ISSUE THREAD

**Issue by SlimFight1** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#311]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] #315

### 问题描述

尝试修改MOD加载次序无效，未开新档测试

### 存档 / 代码

0.4.6.6-(chs-alpha1.0.0) Error (:: Robin's Room Entrance): <<robinroom>>: cannot execute widget: 0.4.6.6-(chs-alpha1.0.0) Error (:: Robin's Room Entrance): <<robinPayout>>: cannot execute widget: 0.4.6.6-(chs-alpha1.0.0) Error (:: Robin's Room Entrance): <<print>>: bad evaluation: Invalid or unexpected token

### 截图

.

**Comment by NumberSir** [comment]
没看懂问题，请附存档，或至少附上截图

**Comment by NumberSir** [comment]
[@issue-dc/10](https://discord.com/channels/1103864219620884560/1226092955065122836)
