### ISSUE TITLE
日志报错

### ISSUE THREAD

**Issue by ALEXDRAGON555** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#313]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

用的最新版0.4.6.6模拟器
![Uploading Screenshot_20240406_144317_com.vrelnir.DegreesOfLewdity.jpg…]()

### 存档 / 代码

[存档码.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/14892744/default.txt)

### 截图

![Screenshot_20240406_144317_com vrelnir DegreesOfLewdity](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/166203741/822d47c7-25ff-41e6-b34c-132ca94877fc)

### 还有别的吗？

没有了

**Comment by LittleNightmare** [comment]
我的也是这样，英文原版没有问题。卸载汉化mod后，不报错了。

**Comment by NumberSir** [comment]
#308
