### ISSUE TITLE
[0.4.6.6-chs-alpha1.0.0] 笔记页面报错

### ISSUE THREAD

**Issue by xiaolok29** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#316]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

已試過重新安裝MOD和IMAGE

### 存档 / 代码

[degrees-of-lewdity-20240406-235324.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/14894185/degrees-of-lewdity-20240406-235324.txt)

### 截图

![報錯](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/166239183/403fa239-1d92-4438-9e82-59a18f5da0b4)
![LOG紀錄](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/166239183/084a4dac-d231-4a65-9745-57c2a7db28ea)

### 还有别的吗？

N/A

**Comment by xiaolok29** [comment]
突然想起來，我這個存檔還沒有辦法改變已有名字的NPC的性別

**Comment by xiaolok29** [comment]
> 重新載入下一個新的漢化包？
試過了
還是不行
我甚至從新下載了一次漢化包，還是沒用(枯了

**Comment by xiaolok29** [comment]
> hmmm旧版汉化包有移除吗，添加完有点左上重新载入吗，我这里测试是正常的
有的
移除以後英文原版可以顥示，但只要用了漢化包就無法顯示
換別的瀏覽器也是一樣(頭痛

**Comment by xiaolok29** [comment]
淦，我重新開機之後突然又能顯示了

**Comment by xiaolok29** [comment]
[degrees-of-lewdity-20240407-012303.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/14894328/degrees-of-lewdity-20240407-012303.txt)
不知道有什麼不同，先放上來吧

**Comment by xiaolok29** [comment]
我發現
![LOG紀錄](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/166239183/bd2b727b-c74d-4581-91ea-ee431822d07a)
橙色那行警告在我移除了漢化包之後還在
然後，我剛才直接再下一次主程式，還是沒用

**Comment by NumberSir** [comment]
橙色警告不会影响游戏正常运行，下次更新会修复

**Comment by NumberSir** [comment]
#308
