### ISSUE TITLE
[0.4.6.6-chs-alpha1.0.1] 查看“统计-额外统计”一栏时报错

### ISSUE THREAD

**Issue by robot1415** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#318]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

已将汉化包更新至alpha1.0.1且移除旧版本汉化包，“额外统计”一栏报错仍未解决

### 存档 / 代码

[存档码.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/14894320/default.txt)

### 截图

![Screenshot_20240407_010840_com vrelnir DegreesOfLewdity](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/67535753/e155d5bb-bf76-43c7-8db4-aa91765a1f26)

### 还有别的吗？

无

**Comment by Kagamine-Rinrin** [comment]
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/43258604/ea6fcdb4-094a-467d-8ac9-c5bf438a6a48)
使用你的存档未发现问题，也可能是我用的修复后的版本测试，所以没有报错。
请等待更新

**Comment by robot1415** [comment]
补充报错：
0.4.6.6-(chs-alpha1.0.1) Error (:: Domus Street): <<=>>: bad evaluation: Cannot read properties of undefined (reading 'fetus') : {"passage": "Domus Street", "stack": ["extraStatistics"], "phase": "home", "rng": 73, "danger": 4638, "index": 0} ;
0.4.6.6-(chs-alpha1.0.1) Error (:: Domus Street): <<=>>: bad evaluation: Cannot read properties of undefined (reading 'fetus') : {"passage": "Domus Street", "stack": ["extraStatistics"], "phase": "home", "rng": 73, "danger": 4638, "index": 0} ;
0.4.6.6-(chs-alpha1.0.1) Error (:: Domus Street): cannot execute macro <<foldout>>: 0.4.6.6-(chs-alpha1.0.1) Error (:: Domus Street): <<=>>: bad evaluation: Cannot read properties of undefined (reading 'fetus') : {"passage": "Domus Street", "stack": ["extraStatistics"], "phase": "home", "rng": 73, "danger": 4638, "index": 0} ;
0.4.6.6-(chs-alpha1.0.1) Error (:: Domus Street): <<extraStatistics>>: cannot execute widget: 0.4.6.6-(chs-alpha1.0.1) Error (:: Domus Street): cannot execute macro <<foldout>>: 0.4.6.6-(chs-alpha1.0.1) Error (:: Domus Street): <<=>>: bad evaluation: Cannot read properties of undefined (reading 'fetus') : {"passage": "Domus Street", "stack": ["extraStatistics"], "phase": "home", "rng": 73, "danger": 4638, "index": 0} ;
