### ISSUE TITLE
[0.4.6.6-chs-alpha1.0.1] 百貨公司與悉尼觸發性愛時間後，離開百貨公司報錯

### ISSUE THREAD

**Issue by waxchian** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#319]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

觸發在百貨試衣間做愛後發生了報錯的問題，目前無法退出

### 存档 / 代码

[degrees-of-lewdity-悉尼-20240407-105316.save.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/14895609/degrees-of-lewdity-.-20240407-105316.save.txt)

### 截图

![Screenshot_2024-04-07-10-52-43-03_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/166269971/c50b2567-93f4-48f1-ba37-8a8761481887)

**Comment by Kagamine-Rinrin** [comment]
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/43258604/16c4282b-4752-4f36-a069-aca000c7f672)
读取你的存档发现正常
可能是已修复的BUG，麻烦等新版本发布后再试一次。
