### ISSUE TITLE
发现翻译闪烁问题，想咨询一下汉化的方式

### ISSUE THREAD

**Issue by Lyoko-Jeremie** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#32]
### 说说你遇到的问题？

在游玩过程中有发现存在同一句子同一单词，前一对话翻译成了中文后一对话就变成英文，或者反过来，这样的翻译闪烁问题。  
在家里的sex玩具箱页面特别容易触发这个现象。

我想请问一下，汉化是使用内存注入并替换输出字符串形式的动态汉化，还是直接修改原始剧本脚本(.twee脚本)的静态汉化，还是官方原版游戏框架中提供了原生的i18n系统呢？

**Comment by Eltirosto** [comment]
我们直接修改 .twee 和 .js 原文件中的文本后使用源仓库自带的编译脚本编译为 html 文件。

出现这种情况十分正常，因为游戏基于 [Twine/Twee3](http://twinery.org/) 引擎，使用的编码格式是 [Sugarcube2](https://github.com/tmedwards/sugarcube-2)，因此在游戏源代码中常常会出现普通的文本字符串与变量、逻辑语句混杂交织的情况，对于任何形式的 i18n 均不友好。

例如挑一句源代码中的文本如下：
`a hidden pocket on the inside of <<nnpc_his "Kylar">> <<if $NPCName[$NPCNameList.indexOf("Kylar")].pronoun is "m">>pant leg<<else>>skirt<</if>>`
其对应的汉化文本为：
`<<nnpc_his "Kylar">>的<<if $NPCName[$NPCNameList.indexOf("Kylar")].pronoun is "m">>裤子<<else>>裙子<</if>>内的隐藏口袋里掏了出来。`
其中的变量 `<<nnpc_his "Kylar">>` 的定义在此处不得而知，需要在其他地方独立翻译。包括这一种情况在内的有各种复杂情况，包括但不限于：
- 在某句中使用的变量定义在另一句
- 不该汉化的变量被错误地汉化，进而导致报错
- 在某处用作输出文本的变量在另一处却参与逻辑判断，进而对其汉化导致报错
- 不同位置处的两句文本格式相似，但一句能够汉化，另一句汉化则会出错
- 等等等等……

截止目前形如此的需汉化文本有超过 111,719 条，因此在汉化过程中会出现大量的语义混杂、中英交织，或是非字符串被错误地汉化进而导致的报错问题，直至现在仍在完善过程中。因此需要大量玩家反馈游玩过程中可能出现的各种问题，进而修复完善汉化。

**Comment by Lyoko-Jeremie** [comment]
刚才想测一下，发现这个 https://gitgud.io/Vrelnir/sugarcube-2 不是最新版的代码，得问问作者请他push最新的sugarcube-2更改上来

**Comment by LittleNightmare** [comment]
@Lyoko-Jeremie 可以考虑看这个https://github.com/tmedwards/sugarcube-2的develop分支

**Comment by Lyoko-Jeremie** [comment]
@LittleNightmare 研究了一下git log，不像是

把两个project放在一起可以看到 [Vrelnir](https://gitgud.io/Vrelnir/sugarcube-2) 这个版本有个DoL特定的patch，但没看到 [tmedwards](https://github.com/tmedwards/sugarcube-2) 这个版本上有这个patch ， 所以感觉这应该是为另一个游戏做的特化版本，或者就是sugarcube-2的后续开发

![图片](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/6566869/f14eebe2-27c4-4bbc-9e76-c47d11b63611)


把tmedwards这个版本放进去跑起来也是：

![Screenshot 2023-09-10 at 14-07-52 Degrees of Lewdity](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/6566869/23902652-5056-4cce-83c0-9a7582d9562c)

---


另外我可以确定正确版本应该是 [Vrelnir](https://gitgud.io/Vrelnir/sugarcube-2) 的版本，因为之前我放进去之后的第一个报错是有关 [maxSessionStates](https://gitgud.io/Vrelnir/sugarcube-2/-/merge_requests/3/diffs#87f3e0e4cc62eefaef83559ad73420b22d52e801_136_137) 缺失的，刚好就是这个还没合并的 [PR#3](https://gitgud.io/Vrelnir/sugarcube-2/-/merge_requests/3/diffs) 里面添加进来的。 但是我在我本地手动Patch这个PR之后报错提示还缺少其他东西，所以我可以肯定是作者本地已经合并了这个PR，然后在其上还做了其他开发加了点最新版游戏必须的功能，但是没有把最新修改推上来。

**Comment by Lyoko-Jeremie** [comment]
我的错，刚才研究了一下，打了这个 [PR#3](https://gitgud.io/Vrelnir/sugarcube-2/-/merge_requests/3/diffs) 之后得清理掉本地所有数据才能用，不然读取旧数据会报JSON解析失败，可能是IndexBD里面的数据格式变了。现在可以打开进入游戏了，但不确定其他地方会不会有问题，后边我研究一下这个sugarcube-2怎么运行的。

**Comment by Lyoko-Jeremie** [comment]
打过 PR#3 能跑的版本 https://github.com/Lyoko-Jeremie/sugarcube-2_Vrelnir

**Comment by Eltirosto** [comment]
想咨询下能否来组里协助具体实现一个更便捷的汉化方式？有意向的话可以加Q 307079773

**Comment by Pi1viayarn** [comment]
> 打过 PR#3 能跑的版本 https://github.com/Lyoko-Jeremie/sugarcube-2_Vrelnir

构建对比了下，游戏用的版本打了[PR#3](https://gitgud.io/Vrelnir/sugarcube-2/-/merge_requests/3/diffs)，并把[PR#2](https://gitgud.io/Vrelnir/sugarcube-2/-/merge_requests/2/diffs#5472979c811789112715bb003f8e1c45e8d55ce5)还原了

**Comment by Lyoko-Jeremie** [comment]
@Pi1viayarn 3Q~~

**Comment by Lyoko-Jeremie** [comment]
@Eltirosto 测试了一下，这个框架好像挺复杂的，先给我点时间找到能用的注入点弄个demo出来

**Comment by Lyoko-Jeremie** [comment]
初步分析写在 [这里了](https://github.com/Lyoko-Jeremie/sugarcube-2_Vrelnir/issues/1) ， 上面的 **汉化方法2** 应该是可以实现了。

**Comment by Lyoko-Jeremie** [comment]
汉化方法2实现demo了 https://github.com/Lyoko-Jeremie/sugarcube-2_Vrelnir/issues/1#issuecomment-1714805847 🤣

<img width="1455" alt="2023-09-12 08_39_30-Degrees of Lewdity — Firefox Developer Edition" src="https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/6566869/90ced1e7-f6f3-43c6-a3fe-6ab945c3b57c">

**Comment by NumberSir** [comment]
未来汉化发布方式将独立于原版游戏，采取 I18N 模组的方式发布

**Comment by SexyAkko** [comment]
想问一下，这类翻译的使用方式，之前没有接触过，能不能补贴一下使用方式之类的？

**Comment by NumberSir** [comment]
> 想问一下，这类翻译的使用方式，之前没有接触过，能不能补贴一下使用方式之类的？

截至 [0.4.2.7-chs-alpha4.0.0](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/releases/tag/v0.4.2.7-chs-alpha4.0.0) 的汉化方式（下称“旧版汉化方式”）仍然是修改硬编码，直接下载发布版中的 zip 压缩文件解压即玩。

未来的新版汉化方式将基于 [ModLoader](https://github.com/Lyoko-Jeremie/sugarcube-2-ModLoader)，（基本用法请查看 ReadMe，基本原理是向原游戏的 HTML 文件中注入 js 实现加载模组的功能）仅放出含汉化词典的 [I18N 模组](https://github.com/Lyoko-Jeremie/Degrees-of-Lewdity_Mod_i18nMod)，在不修改游戏本地英文原文的情况下在运行过程中动态汉化，类比 [Minecraft 的 I18N 模组](https://www.mcmod.cn/class/1188.html)。

未来可能的安装方式可能会是：
>
> 1. 玩家自行在官方英文版发布地址下载英文版
> 2. 本仓库以安装包的形式发布 ModLoader 和内置汉化词典的 I18N 模组
> 3. 玩家自行安装 ModLoader 和汉化模组
