### ISSUE TITLE
[0.4.6.6-chs-alpha1.0.1] 查看特质和额外统计报错

### ISSUE THREAD

**Issue by XonlookerX** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#320]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

查看特质页面和额外统计页面时报错

### 存档 / 代码

[degrees-of-lewdity-1-20240407-154728.zip](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/14896158/degrees-of-lewdity-1-20240407-154728.zip)

### 截图

![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/61648955/1d6dc7e0-2daa-4e06-b7fb-6feb0c864dbf)
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/61648955/58462861-d0c1-426c-ae61-316981bb8f83)

**Comment by Kagamine-Rinrin** [comment]
应该已修复了，请更改版本更新

**Comment by XonlookerX** [comment]
> 应该已修复了，请更改版本更新

不行，刚重新装的最新版，这个档特质页还是会报错，而另一个的档不会报错，两个档的额外统计全都报错
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/61648955/8a8dd7d6-5438-4c29-8516-c597ef34d2a2)

**Comment by NumberSir** [comment]
#318
