### ISSUE TITLE
[0.4.6.6-chs-alpha1.0.1] 打开药柜，选中药品后药品信息旁的图标无法显示

### ISSUE THREAD

**Issue by wx348055736** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#323]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

打开药柜，选中药品后药品信息旁的图标无法显示

### 存档 / 代码

[degrees-of-lewdity-20240403-012834.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/14896827/degrees-of-lewdity-20240403-012834.txt)

### 截图

![20240407183101](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/69603006/9300ff5f-f2a5-441c-a14a-b8d34932e2e3)

**Comment by Kagamine-Rinrin** [comment]
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/43258604/f4114344-2d93-4f96-b451-422e510ddf2a)
使用你的存档读取后我这里是正常的。
可能是已修复的BUG，麻烦等下个版本的时候再试试

**Comment by NumberSir** [comment]
与图片包的实现方式有关，无法涵盖原游戏中千奇百怪的图片添加方式，需要等待 @Lyoko-Jeremie 修复
