### ISSUE TITLE
[0.4.6.6-chs-alpha1.0.1] 额外统计报错问题依旧存在

### ISSUE THREAD

**Issue by Willy0v0** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#325]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

虽然此问题已被提及修复，但本人反复尝试多次存档刷新问题依旧存在，但日志报错问题已被修复

### 存档 / 代码

[Dol_FIle.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/14900811/Dol_FIle.txt)

### 截图

![Screenshot (14)](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/166356069/d8a0da4b-54ba-4a97-820e-d1b4a0c68d8a)

### 还有别的吗？

-本人下载的是zip file并以Microsoft浏览器游玩

-在新版本使用的存档是旧版本的存档，不确定是否与之有关

**Comment by NumberSir** [comment]
#318
