### ISSUE TITLE
出错了·

### ISSUE THREAD

**Issue by whrfssb** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#326]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

版本：0.4.6.6-(chs-alpha1.0.1) lyra整合包最新的BJ+WAX+BES+作弊+csd
报错：载入存档时卧室中出错
0.4.6.6-(chs-alpha1.0.1) Error (:: Bedroom): <<doVersionCheck>>: cannot execute widget: 0.4.6.6-(chs-alpha1.0.1) Error (:: Bedroom): <<backComp>>: cannot execute widget: 0.4.6.6-(chs-alpha1.0.1) Error (:: Bedroom): <<npcPregnancyUpdater>>: cannot execute widget: 0.4.6.6-(chs-alpha1.0.1) Error (:: Bedroom): <<if>>: bad conditional expression in <<if>> clause: Cannot read properties of undefined (reading 'pregnancy')
但在游戏过程中没有问题
存档做过部分修改但在0.4.5.3未报错
最后非常感谢各位大佬的汉化QaQ

### 存档 / 代码

[degrees-of-lewdity-全成就-20240408-225742.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/14907441/degrees-of-lewdity-.-20240408-225742.txt)

### 截图

![1712589787674](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/162877370/797e23d2-c09b-4367-92e0-f8b35703a57e)

### 还有别的吗？

仅在刚载入存档时出现问题
麻烦各位大佬了·

**Comment by whrfssb** [comment]
也就是说是0.4.6.6版本自身的问题对吗

**Comment by NumberSir** [comment]
解决方法请看 #321
