### ISSUE TITLE
[0.4.6.6-chs-alpha1.0.2] 成就加点中初始纹身失效

### ISSUE THREAD

**Issue by XonlookerX** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#328]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

所有自己选择的纹身都不会生效，只会有没选择的随机生成的纹身，比如选了三个，进去游戏就只会生成两个随机的

### 存档 / 代码

任何新档

### 截图

这是选了一个的情况
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/61648955/5e8ca980-e456-4b5e-9bff-e2ca8ccb15ee)

**Comment by wx348055736** [comment]
把下面的代码添加进 ModI18N-0.4.6.6-chs-alpha1.0.2.mod 的 i18n.json 文件的 TypeBInputStoryScript 下可以解决这个问题。
`{
        "f": "<<for _label, _value range $featsBoosts.tattoos>>",
        "t": "<<set _penOptionsENMapping to {'纹身':'Tattoo','烙印':'Brand'}>>\n<<set _bodypartOptionsENMapping to {'额头':'Forehead','左脸':'Left cheek','右脸':'Right cheek','左肩':'Left shoulder','右肩':'Right shoulder','背部':'Back','胸部':'Breasts','左屁股':'Left bottom','右屁股':'Right bottom','左大腿':'Left thigh','右大腿':'Right thigh','耻骨':'Pubic'}>>\n<<set _tattooOptionsENMapping to {}>>\n<<for _value range setup.bodywriting>>\n<<set _tattooOptionsENMapping[_value.writ_cn] to _value.writing>>\n<</for>>\n<<for _label, _value range $featsBoosts.tattoos>>\n<<if typeof _penOptionsENMapping[_value.pen] isnot \"undefined\">>\n<<set $featsBoosts.tattoos[_label].pen to _penOptionsENMapping[_value.pen]>>\n<</if>>\n<<if typeof _bodypartOptionsENMapping[_value.bodypart] isnot \"undefined\">>\n<<set $featsBoosts.tattoos[_label].bodypart to _bodypartOptionsENMapping[_value.bodypart]>>\n<</if>>\n<<if typeof _tattooOptionsENMapping[_value.tattoo] isnot \"undefined\">>\n<<set $featsBoosts.tattoos[_label].tattoo to _tattooOptionsENMapping[_value.tattoo]>>\n<</if>>\n<</for>><<for _label, _value range $featsBoosts.tattoos>>",
        "pos": 15691,
        "fileName": "feast.twee",
        "pN": "Feats"
      }`

**Comment by wx348055736** [comment]
虽然还会有个不知道算不算BUG的问题，就是如果第一个纹身的位置选择背部的话，第二个纹身还可以选择背部，虽然最后只有一个能生效。
