### ISSUE TITLE
有关单词"护理"(tending)的汉化问题

### ISSUE THREAD

**Issue by Lyoko-Jeremie** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#33]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议

### 说说你看到的汉化文本内容？

<img width="240" alt="2023-09-03 23_54_48-Degrees of Lewdity — Mozilla Firefox" src="https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/6566869/e40d6689-586b-4d7a-aefe-661a00e70ff5">

  

tending 这个技能好像主要用在种植方面，例如孤儿院花圃、公园摘花、森林摘苹果和蘑菇，唯一的例外是安抚狗狗。  
 
在日常英文使用中这个词也存在使用于“护理照顾”和“农场培育”这两个方向。

### 有什么好的想法？

在游戏中更容易看到的好像是“种植培育”这个方向（或许我的游玩进度比较短，后面还有更多其他应用）。  

所以我建议将这个词汉化为更加偏向于农业的“培育”或者广泛一点的“自然”。

**Comment by Lyoko-Jeremie** [comment]
截图的数值忽视就好，我改了内存 🤣

**Comment by Eltirosto** [comment]
tending 在游戏中不止与植物相关，事实上在艾利克斯的农场给马刷毛、喂猪喂狗、甚至在路上与狗狗握爪也需要 tending 技能，因此暂且翻译为“护理”
