### ISSUE TITLE
[0.4.6.6-chs-alpha1.0.2] 旧档读取存档记录时报错

### ISSUE THREAD

**Issue by Sleependermasn** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#330]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

旧档读取存档记录时报错，即使重新存档后再读取依然报错。在新版本下创建新的存档则没有这样的情况发生。其中旧档的命名NPC的性别偶尔也发生错乱，例如罗宾实际为男性，在对话过程中却显示为“她”。不过当时我没有进行截图、存档。

### 存档 / 代码

[存档码.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/14915078/default.txt)

### 截图

![1](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/166488007/512e4bb2-566a-4fab-af31-0afbc04a68d0)
![2](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/166488007/8c8e4950-095f-4824-a08c-a4594aef289f)

### 还有别的吗？

复现报错的步骤：
1.在任意时机存档
2.读档

**Comment by Kagamine-Rinrin** [comment]
你是不是之前玩的时候装了MOD呢？
在官方的discord中有类似的报错，得到的回答是
That means you have save data from a mod that adds NPCs.

我在你的存档中发现有个名叫“Casey“的NPC，但游戏中并没有找到这个NPC。可能是因为这个导致的错误

**Comment by Sleependermasn** [comment]
我大概明白了 这个存档我很早就开始玩了 后来才从官方渠道下载的 对mod也不甚了解 总感觉对后期的会是个隐患 有办法解决吗

**Comment by NumberSir** [comment]
解决方法请看 #321

**Comment by Sleependermasn** [comment]
> 解决方法请看 #321

在控制台中输入代码，按下回车：
V.NPCNameList

在第三步翻车了，我不明白……
![Uploading QQ截图20240410203717.png…]()

**Comment by Kagamine-Rinrin** [comment]
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/43258604/827996dc-8d23-4952-b652-99992f6e71d9)

你的截图炸了

另外请注意，目前版本删除NPC会导致位移显示错误人名的BUG，所以如果不是遇到恶性BUG暂时不建议手动删除
目前这个BUG已经临时修复，将会随下个版本推送
但不保证不会出现其他的衍生问题
