### ISSUE TITLE
[0.4.6.6-chs-alpha1.0.2] 图片显示异常

### ISSUE THREAD

**Issue by Pony-CW** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#332]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

这神殿祈祷的图片应该要叠加到一起吧，不知道是什么 bug

### 存档 / 代码

[save.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/14921066/save.txt)

### 截图

![ResizedImage_2024-04-09_23-52-49_1](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/44076275/3dc48e57-dc5f-44f6-beb8-d0a07729f619)

### 还有别的吗？

GameOriginalImagePack-0.4.6.6.mod 还是取的最初的 alpha1.0.0 发行版上的
医院的药物胸部增减和药物的图片应该叠加的
也不知道原版有没有，我先往这一放

**Comment by Kagamine-Rinrin** [comment]
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/43258604/33d1f324-d85b-48ae-9977-67cb10bb73bd)
你这个档是不是装了MOD呀，我这里读你的档图片是正常的，但是别的地方有问题。

**Comment by NumberSir** [comment]
#323
