### ISSUE TITLE
[0.4.6.6-chs-alpha1.0.2]罗宾创伤线地下妓院对话 文本优化建议

### ISSUE THREAD

**Issue by xixia0516** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#333]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 说说你看到的汉化文本内容？

![Screenshot_20240410_234024_MT Manager](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/166011805/ff711c64-6771-4c01-a0c3-c90e81976060)

### 有什么好的想法？

这个想法是和大佬们讨论后得出的。
这里的"And that one combo you keep spamming"或许可以翻译得更像游戏术语，比如：
“那样我们就可以用激光剑和大炮逃出这里了。再加上你老是在用的那套连招。”重新想起自己的家，<<He>>听起来更开朗了些。
或者再稍微修改一下语序，让这句话看起来更适合中文：
“那样我们就可以用激光剑和大炮、还有你老是在用的那套连招来逃出这里了。”听起来重新想起自己的家让<<He>>更开朗了些。

这里的“想到”或许也可以改成“想起”。

"spam"在格斗游戏里一般是指那种，像是在发垃圾邮件一样频繁地做某件事，比如脸滚键盘一样地按技能。
"spam the combo"一般是在说格斗游戏玩家滥用同一套连招来取胜。（来自那位大佬）

非常感谢。

**Comment by Maenoko** [comment]
改了
