### ISSUE TITLE
 [0.4.6.7-chs-alpha2.0.0] 安卓存档进电脑端一直卡在存档升级提示界面

### ISSUE THREAD

**Issue by dufy2000** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#336]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

安卓端存档放进电脑端一直提示版本问题，一直点一直是

### 存档 / 代码

[新建文本文档.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/14945823/default.txt)

### 截图

![C(GXU7GBOB`25SIFAD 136L](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/153524367/e83081b7-1fdd-41ef-bbae-8b247820e8e3)

**Comment by Kagamine-Rinrin** [comment]
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/43258604/92602077-3a3f-4c59-90e4-6236d7ef0426)
O.O 我这里读你的档是正常的诶

**Comment by dufy2000** [comment]
……就这个档不行，不知道为啥 = = 
手机上出孤儿院再存一次上来就能打开了
