### ISSUE TITLE
[0.4.6.7-(chs-alpha2.0.0)] 和谐，残暴文本漏抓

### ISSUE THREAD

**Issue by miyakoAki4828** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#337]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 说说你看到的汉化文本内容？

位于 game/base-system/stat-changes.js 的 573 行
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/153734729/6839c07b-4b26-4eea-a36b-49d432400630)
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/153734729/a15a5958-7506-4ad0-8b69-76832ee9c282)
[degrees-of-lewdity-20240412-000316.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/14948594/degrees-of-lewdity-20240412-000316.txt)

**Comment by Kagamine-Rinrin** [comment]
可以直接抓base-system\text.js:8
return ` | <span class="${colorClass}">${prefix.repeat(Math.abs(amount))}${statType}</span>`;
将statType replace一遍就可以一劳永逸了

**Comment by Kagamine-Rinrin** [comment]
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/43258604/7d7d9e07-9769-4fa5-aa92-7e576ab038be)
测试可行,等待同步
