### ISSUE TITLE
[0.4.6.7 chs-alpha2.0.0] 飞行员眼镜次要颜色中“原色”选项显示Original

### ISSUE THREAD

**Issue by gn02994106** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#338]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 说说你看到的汉化文本内容？

![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/64271432/5b7e984f-1f7b-404c-835e-3398c098006a)

![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/64271432/c739ca7c-68a5-403c-820d-3bf489d1468c)

如图1，次要颜色中最左边的选项显示为“Original”，怀疑可能是漏抓
而图2，旧有的眼镜也会显示“Original”，但新买的显示正常（显示主要颜色名称），可在同存档的衣柜中确认

存档如下，但需自行点击“查看面饰”，“飞行员眼镜”（其实任何存档皆可触发
[degrees-of-lewdity-20240412-003208.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/14948830/degrees-of-lewdity-20240412-003208.txt)

**Comment by Kagamine-Rinrin** [comment]
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/43258604/3f5e8770-5c17-45db-abf3-d2a5c77bcd6a)
已修复，感谢反馈
旧的眼睛应该是买了之后存到衣柜的时候把名字定下来了，新买的就没有这个问题了。

**Comment by Kagamine-Rinrin** [comment]
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/43258604/bd6cc0af-fb0f-4800-b68f-c47f06f7f340)  full.png缺失
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/43258604/ba93b1e5-42f8-432e-a730-445725dc54e4)导入旧版full.png后
你这个眼镜是不是旧版买的呀~ 可能是版本更新导致的

**Comment by Kagamine-Rinrin** [comment]
小红点报错多半是因为版本更新，但是又忘记在导入旧版存档时对旧存档处理导致的。
新版测试买到的图片显示就正常啦
