### ISSUE TITLE
[0.4.6.7-chs-alpha2.0.1] 各位大佬怎么汉化

### ISSUE THREAD

**Issue by blackuoi** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#339]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 说说你看到的汉化文本内容？

各位大佬怎么汉化

**Comment by NumberSir** [comment]
请阅读 [README](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/blob/main/README.md)
