### ISSUE TITLE
被贝利绑走的扶她相关内容有一点点

### ISSUE THREAD

**Issue by 2077930253** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#34]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议

### 说说你看到的汉化文本内容？

![TNQ 7%K{KD3A{6}DQ)B892U](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/39304597/7fec9b7d-2ac5-43e8-8deb-df0cf4fa39bf)

**Comment by Eltirosto** [comment]
已汉化，请等待新版本发布
