### ISSUE TITLE
[0.4.6.7 chs-alpha2.0.0]latexleotard/乳胶紧身裤图片缺失

### ISSUE THREAD

**Issue by limidafei** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#340]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

这个资源图片并不存在，导致角色立绘不正常显示，主要表现为无内裤且不显示penis

```
Failed to load image img/clothes/under_lower/latexleotard/torn_gray.png for layer under_lower ;
Failed to load image img/clothes/under_lower/latexleotard/torn_gray.png for layer under_lower ;
Failed to load image img/clothes/under_lower/latexleotard/torn_gray.png for layer under_lower ;
```

### 存档 / 代码

[0.4.6.7 chs-alpha2.0.0默认模组 存档.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/14967260/0.4.6.7.chs-alpha2.0.0.txt)

### 截图

![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/96374182/faddb762-44de-4dbd-8d0c-36466d8d441d)

![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/96374182/3aeae9f6-5e50-4a74-82f7-afea669d1141)

**Comment by Kagamine-Rinrin** [comment]
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/43258604/194d83d3-973a-4aea-8e8e-72a533c4b92b)
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/43258604/8828e50c-3702-4788-a6b6-7f25e1e9de64)
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/43258604/0b88b12e-b677-42fc-b23b-2d248370d1d7)
这里用你的档新买了一件乳胶衣服测试了一下，
但是乳胶连身衣不管是直接穿，还是拆开上下衣分开穿都显示的正常的。
可能是因为这个档是旧档，或者是mod档导致的呢

**Comment by limidafei** [comment]
问题是衣服状态，没有破损和撕裂状态

**Comment by NumberSir** [comment]
原版问题
