### ISSUE TITLE
[0.4.6.7 chs-alpha2.0.0]耳内寄生虫满成长后遇买内衣事件时报错

### ISSUE THREAD

**Issue by zsbxws** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#341]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

耳内寄生虫满成长后遭遇30块买内衣事件时会报错，附报错前存档移动至康努达塔斯街触发

### 存档 / 代码

[20240416.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/14987115/20240416.txt)

### 截图

![Screenshot_20240416_132127](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/167164225/adda7738-71bc-4cda-8476-cd2126944384)

**Comment by Kagamine-Rinrin** [comment]
怀疑应该是一个原版BUG，英文版测试也是如此
可能一个条件都没满足，所以导致木有可用的link
待会我上报给官方。
