### ISSUE TITLE
[0.4.6.7 chs-alpha2.0.0]翻譯報錯以及存檔bug

### ISSUE THREAD

**Issue by willie9815** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#342]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

1.在隨機的猥褻事件都有可能會產生錯誤。
2.在事件中讀檔時一些隨機要素，比如NPC的名稱或是行動，會跟存檔時不符。

### 存档 / 代码

[degrees-of-lewdity-20240418-152342.save.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/15021383/degrees-of-lewdity-20240418-152342.save.txt)

### 截图

![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/62329413/259a8032-9873-48cd-ac9e-f315da30db00)

### 还有别的吗？

在線版的瀏覽器存檔在這版更新後全都消失了，我上一個遊玩的版本如下
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/62329413/29220135-4f4c-4298-84b5-baf47b8111e3)
更新完之後存檔欄直接被清空

**Comment by willie9815** [comment]
後一項的問題實際演示大概是假如我在這裡存檔
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/62329413/0d3b4694-a2ea-461f-aa48-71baf94986c4)

讀檔後當下的變數就會跑掉了
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/62329413/954f5307-a473-4d00-a7b0-9cfa95750f39)

**Comment by Kagamine-Rinrin** [comment]
①应该是一个原版错误，这个NPC狗没有role属性所以在替换的时候报错了。稍后我去上报一下官方。

**Comment by Kagamine-Rinrin** [comment]
零食解决了
顺带一问，你玩的时候有没有加入mod呢？
因为我看你上文描述是狗，到了下面变成了男人？

**Comment by willie9815** [comment]
有的，是lyra的在線版，但這應該是美化模組？作弊功能從沒用過
https://dol-lyra.github.io/hub/

**Comment by Kagamine-Rinrin** [comment]
谢谢反馈 
我已经上报给官方了,等待修复吧.

**Comment by Kagamine-Rinrin** [comment]
> 那關於另外一個存檔bug有確認到嗎，我覺得這個是比較嚴重的
> 
> 存檔2是存檔1移動到豐收街的存檔，但存檔2讀檔的內容卻不符存檔時的場景 存檔1 [degrees-of-lewdity-iPhone-20240419-222443.save.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/15043779/degrees-of-lewdity-iPhone-20240419-222443.save.txt) 存檔2 [degrees-of-lewdity-iPhone-20240420-012632.save.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/15043780/degrees-of-lewdity-iPhone-20240420-012632.save.txt)

复现方式是用存档1移动到丰收街么，
我这里存档1移动到丰收街后显示的是
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/43258604/da327054-bb6b-49f4-8ab7-9af63a955412)
似乎和你不一致呢，
然后我再进行存档读档，读出来的内容和之前是一致的

**Comment by willie9815** [comment]
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/62329413/08fbb8af-8aa1-4da2-bdef-f3916ab5a6a8)
我讀檔的結果

**Comment by willie9815** [comment]
不論我開哪一版這問題都持續出現

**Comment by willie9815** [comment]
> > 那關於另外一個存檔bug有確認到嗎，我覺得這個是比較嚴重的
> 
> > 
> 
> > 存檔2是存檔1移動到豐收街的存檔，但存檔2讀檔的內容卻不符存檔時的場景 存檔1 [degrees-of-lewdity-iPhone-20240419-222443.save.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/15043779/degrees-of-lewdity-iPhone-20240419-222443.save.txt) 存檔2 [degrees-of-lewdity-iPhone-20240420-012632.save.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/15043780/degrees-of-lewdity-iPhone-20240420-012632.save.txt)
> 
> 
> 
> 复现方式是用存档1移动到丰收街么，
> 
> 我这里存档1移动到丰收街后显示的是
> 
> ![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/43258604/da327054-bb6b-49f4-8ab7-9af63a955412)
> 
> 似乎和你不一致呢，
> 
> 然后我再进行存档读档，但是我这边读出来的内容和存档时候的内容是一致的

請問你那邊測試的是在線版還是離線版？

**Comment by Kagamine-Rinrin** [comment]
> > > 那關於另外一個存檔bug有確認到嗎，我覺得這個是比較嚴重的
> > 
> > 
> > > 
> > 
> > 
> > > 存檔2是存檔1移動到豐收街的存檔，但存檔2讀檔的內容卻不符存檔時的場景 存檔1 [degrees-of-lewdity-iPhone-20240419-222443.save.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/15043779/degrees-of-lewdity-iPhone-20240419-222443.save.txt) 存檔2 [degrees-of-lewdity-iPhone-20240420-012632.save.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/15043780/degrees-of-lewdity-iPhone-20240420-012632.save.txt)
> > 
> > 
> > 复现方式是用存档1移动到丰收街么，
> > 我这里存档1移动到丰收街后显示的是
> > ![image](https://private-user-images.githubusercontent.com/43258604/324079398-da327054-bb6b-49f4-8ab7-9af63a955412.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NTc4MzQsIm5iZiI6MTcxMzc1NzUzNCwicGF0aCI6Ii80MzI1ODYwNC8zMjQwNzkzOTgtZGEzMjcwNTQtYmI2Yi00OWY0LThhYjctOWFmNjNhOTU1NDEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDAzNDUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjYzNkNjJlNDU3MmFlYWZhMWM3NjMwZmE3NDY0ZGRlN2E0ODE5MTYxM2MzZjQ4MWE4MThiZjUwNTM5MzUzOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Hdp7rEAgB-Xc72JkdqretksGjm0kpY4e9xbxeb_dhw8)
> > 似乎和你不一致呢，
> > 然后我再进行存档读档，但是我这边读出来的内容和存档时候的内容是一致的
> 
> 請問你那邊測試的是在線版還是離線版？

是离线版本呢

**Comment by willie9815** [comment]
> > > > 那關於另外一個存檔bug有確認到嗎，我覺得這個是比較嚴重的
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > 存檔2是存檔1移動到豐收街的存檔，但存檔2讀檔的內容卻不符存檔時的場景 存檔1 [degrees-of-lewdity-iPhone-20240419-222443.save.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/15043779/degrees-of-lewdity-iPhone-20240419-222443.save.txt) 存檔2 [degrees-of-lewdity-iPhone-20240420-012632.save.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/15043780/degrees-of-lewdity-iPhone-20240420-012632.save.txt)
> > > 
> > > 
> > > 复现方式是用存档1移动到丰收街么，
> > > 我这里存档1移动到丰收街后显示的是
> > > ![image](https://private-user-images.githubusercontent.com/43258604/324079398-da327054-bb6b-49f4-8ab7-9af63a955412.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NTc4MzQsIm5iZiI6MTcxMzc1NzUzNCwicGF0aCI6Ii80MzI1ODYwNC8zMjQwNzkzOTgtZGEzMjcwNTQtYmI2Yi00OWY0LThhYjctOWFmNjNhOTU1NDEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDAzNDUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjYzNkNjJlNDU3MmFlYWZhMWM3NjMwZmE3NDY0ZGRlN2E0ODE5MTYxM2MzZjQ4MWE4MThiZjUwNTM5MzUzOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Hdp7rEAgB-Xc72JkdqretksGjm0kpY4e9xbxeb_dhw8)
> > > 似乎和你不一致呢，
> > > 然后我再进行存档读档，但是我这边读出来的内容和存档时候的内容是一致的
> > 
> > 
> > 請問你那邊測試的是在線版還是離線版？
> 
> 是离线版本呢

我重新使用離線版本測試一次，問題依舊存在

https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/62329413/b16fb662-a58a-4cdb-880c-269368a95c28

另外modloader載入時有跳出一項警告，不知道是否有關
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/62329413/4927d001-9b33-4732-8baa-c275716937c6)

**Comment by Kagamine-Rinrin** [comment]
> > > > > 那關於另外一個存檔bug有確認到嗎，我覺得這個是比較嚴重的
> > > > 
> > > > 
> > > > > 
> > > > 
> > > > 
> > > > > 存檔2是存檔1移動到豐收街的存檔，但存檔2讀檔的內容卻不符存檔時的場景 存檔1 [degrees-of-lewdity-iPhone-20240419-222443.save.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/15043779/degrees-of-lewdity-iPhone-20240419-222443.save.txt) 存檔2 [degrees-of-lewdity-iPhone-20240420-012632.save.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/15043780/degrees-of-lewdity-iPhone-20240420-012632.save.txt)
> > > > 
> > > > 
> > > > 复现方式是用存档1移动到丰收街么，
> > > > 我这里存档1移动到丰收街后显示的是
> > > > ![image](https://private-user-images.githubusercontent.com/43258604/324079398-da327054-bb6b-49f4-8ab7-9af63a955412.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NTc4MzQsIm5iZiI6MTcxMzc1NzUzNCwicGF0aCI6Ii80MzI1ODYwNC8zMjQwNzkzOTgtZGEzMjcwNTQtYmI2Yi00OWY0LThhYjctOWFmNjNhOTU1NDEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDAzNDUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjYzNkNjJlNDU3MmFlYWZhMWM3NjMwZmE3NDY0ZGRlN2E0ODE5MTYxM2MzZjQ4MWE4MThiZjUwNTM5MzUzOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Hdp7rEAgB-Xc72JkdqretksGjm0kpY4e9xbxeb_dhw8)
> > > > 似乎和你不一致呢，
> > > > 然后我再进行存档读档，但是我这边读出来的内容和存档时候的内容是一致的
> > > 
> > > 
> > > 請問你那邊測試的是在線版還是離線版？
> > 
> > 
> > 是离线版本呢
> 
> 我重新使用離線版本測試一次，問題依舊存在
> 
>  _.Clipchamp.mp4 
> 另外modloader載入時有跳出一項警告，不知道是否有關 ![image](https://private-user-images.githubusercontent.com/62329413/325085303-4927d001-9b33-4732-8baa-c275716937c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5Mzc5MTIsIm5iZiI6MTcxMzkzNzYxMiwicGF0aCI6Ii82MjMyOTQxMy8zMjUwODUzMDMtNDkyN2QwMDEtOWIzMy00NzMyLThiYWEtYzI3NTcxNjkzN2M2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDA1NDY1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1ZTk4NTI2ODg1MTcwYjU0NWNmOGJkNGNjNTY2MTBiYmEwYjZmODM2NTc3NGUzYzNmNzFlZDEzOTA5Y2RkNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mfXeFmglcuAmkMXeke8MHMWMOx7h1ovOTiLyJxw_Vvs)

我又用在线版试了试你的存档1（https://dol-lyra.github.io/dol.html）
在丰收街读档的时候，确实出现了这个情况。

但我也发现在线版是自带了几个MOD的，会不会是某个MOD的缺陷才导致的这个问题呢？
也许你需要反馈给模组作者修复呢

**Comment by willie9815** [comment]
> > > > > > 那關於另外一個存檔bug有確認到嗎，我覺得這個是比較嚴重的
> > > > > 
> > > > > 
> > > > > > 
> > > > > 
> > > > > 
> > > > > > 存檔2是存檔1移動到豐收街的存檔，但存檔2讀檔的內容卻不符存檔時的場景 存檔1 [degrees-of-lewdity-iPhone-20240419-222443.save.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/15043779/degrees-of-lewdity-iPhone-20240419-222443.save.txt) 存檔2 [degrees-of-lewdity-iPhone-20240420-012632.save.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/15043780/degrees-of-lewdity-iPhone-20240420-012632.save.txt)
> > > > > 
> > > > > 
> > > > > 复现方式是用存档1移动到丰收街么，
> > > > > 我这里存档1移动到丰收街后显示的是
> > > > > ![image](https://private-user-images.githubusercontent.com/43258604/324079398-da327054-bb6b-49f4-8ab7-9af63a955412.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NTc4MzQsIm5iZiI6MTcxMzc1NzUzNCwicGF0aCI6Ii80MzI1ODYwNC8zMjQwNzkzOTgtZGEzMjcwNTQtYmI2Yi00OWY0LThhYjctOWFmNjNhOTU1NDEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDAzNDUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjYzNkNjJlNDU3MmFlYWZhMWM3NjMwZmE3NDY0ZGRlN2E0ODE5MTYxM2MzZjQ4MWE4MThiZjUwNTM5MzUzOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Hdp7rEAgB-Xc72JkdqretksGjm0kpY4e9xbxeb_dhw8)
> > > > > 似乎和你不一致呢，
> > > > > 然后我再进行存档读档，但是我这边读出来的内容和存档时候的内容是一致的
> > > > 
> > > > 
> > > > 請問你那邊測試的是在線版還是離線版？
> > > 
> > > 
> > > 是离线版本呢
> > 
> > 
> > 我重新使用離線版本測試一次，問題依舊存在
> > _.Clipchamp.mp4
> > 另外modloader載入時有跳出一項警告，不知道是否有關 ![image](https://private-user-images.githubusercontent.com/62329413/325085303-4927d001-9b33-4732-8baa-c275716937c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5Mzc5MTIsIm5iZiI6MTcxMzkzNzYxMiwicGF0aCI6Ii82MjMyOTQxMy8zMjUwODUzMDMtNDkyN2QwMDEtOWIzMy00NzMyLThiYWEtYzI3NTcxNjkzN2M2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDA1NDY1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1ZTk4NTI2ODg1MTcwYjU0NWNmOGJkNGNjNTY2MTBiYmEwYjZmODM2NTc3NGUzYzNmNzFlZDEzOTA5Y2RkNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mfXeFmglcuAmkMXeke8MHMWMOx7h1ovOTiLyJxw_Vvs)
> 
> 我又用在线版试了试你的存档1（[https://dol-lyra.github.io/dol.html）](https://dol-lyra.github.io/dol.html%EF%BC%89) 在丰收街读档的时候，确实出现了这个情况。
> 
> 但我也发现在线版是自带了几个MOD的，会不会是某个MOD的缺陷才导致的这个问题呢，亦或是I18Nmod本身有问题？ 也许你需要反馈给模组作者修复呢

我測試的離線版是用這邊漢化組的版本下去測試的，所以應該只會有這邊的模組

**Comment by Kagamine-Rinrin** [comment]
> 我測試的離線版是用這邊漢化組的版本下去測試的，所以漢化組版本這邊的mod可能就有問題了

也可能是I18N的问题。@numbersir

**Comment by NumberSir** [comment]
存档找不到是个老生常谈的问题了，DoL 的存档系统经历过两次改动，不过理论上只要没有清除浏览器的全部缓存就不会丢失存档。

![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/52584526/93971ae5-e7dd-450a-a778-864126f6aeef)
打开存档界面，默认是新版存档系统，勾选最下方的 `Use old legacy save storage` 使用旧版存档系统


![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/52584526/1733adb7-c124-4ce4-89ed-69add8582424)

在旧版存档系统界面鼠标挪到上方的 `我的存档呢？(?)` 的蓝色问号处查看简要说明。

![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/52584526/beb3a293-40ee-40b4-9257-5c64446a7c14)
在旧版存档系统界面勾选最下方的 `启用 indexedDB` 使用新版存档系统。

如果在两个存档系统中都没找到那就确实是存档丢失了，建议定期导出存档。

**Comment by NumberSir** [comment]
> 那關於另外一個存檔bug有確認到嗎，我覺得這個是比較嚴重的
> 
> 存檔2是存檔1移動到豐收街的存檔，但存檔2讀檔的內容卻不符存檔時的場景 存檔1 [degrees-of-lewdity-iPhone-20240419-222443.save.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/15043779/degrees-of-lewdity-iPhone-20240419-222443.save.txt) 存檔2 [degrees-of-lewdity-iPhone-20240420-012632.save.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/15043780/degrees-of-lewdity-iPhone-20240420-012632.save.txt)

这不是汉化问题，首先原版能够复现，其次问题出现是因为一个巧合：

你在进入丰收街的时候恰好性奋达到最高值高潮了（判定条件1），然后游戏生成随机数 `$danger`（判定条件2）， 然后你再存的档；

而读档时性奋没有达到最高值，没有高潮（判定条件1），然后游戏生成随机数 `$danger`（判定条件2）;

因为判定条件1在前，判定条件2在后，且存档前和读档后判定条件1的值不同，因此判定条件2的值不同；而判定条件2会触发随机的街头事件，即那个有人开车要看你xx的事件，所以才会出现这个存档前读档后事件不一致的问题。

根本原因在于原版码农没写好这里的随机事件处理。

**Comment by willie9815** [comment]
> > 那關於另外一個存檔bug有確認到嗎，我覺得這個是比較嚴重的
> > 存檔2是存檔1移動到豐收街的存檔，但存檔2讀檔的內容卻不符存檔時的場景 存檔1 [degrees-of-lewdity-iPhone-20240419-222443.save.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/15043779/degrees-of-lewdity-iPhone-20240419-222443.save.txt) 存檔2 [degrees-of-lewdity-iPhone-20240420-012632.save.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/15043780/degrees-of-lewdity-iPhone-20240420-012632.save.txt)
> 
> 这不是汉化问题，首先原版能够复现，其次问题出现是因为一个巧合：
> 
> 你在进入丰收街的时候恰好性奋达到最高值高潮了（判定条件1），然后游戏生成随机数 `$danger`（判定条件2）， 然后你再存的档；
> 
> 而读档时性奋没有达到最高值，没有高潮（判定条件1），然后游戏生成随机数 `$danger`（判定条件2）;
> 
> 因为判定条件1在前，判定条件2在后，且存档前和读档后判定条件1的值不同，因此判定条件2的值不同；而判定条件2会触发随机的街头事件，即那个有人开车要看你xx的事件，所以才会出现这个存档前读档后事件不一致的问题。
> 
> 根本原因在于原版码农没写好这里的随机事件处理。

@NumberSir 那請問能否代為向原版回報，因為在4.5版本時這個bug並不存在
