### ISSUE TITLE
[0.4.6.7-chs-alpha2.0.0]载入存档游戏报错问题

### ISSUE THREAD

**Issue by wozhachengyanhua** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#344]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

如题，我在载入存档时游戏报错，已看问题321和330，但我的报错并不是NPC加载，求解

### 存档 / 代码

[存档码.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/15134276/default.txt)

### 截图

![Screenshot_20240427_023457_com huawei browser](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/155298780/7de9ba5a-1665-4358-b971-86e0ef79241c)
![Screenshot_20240427_023452_com huawei browser](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/155298780/06fd1940-36d0-44b9-bfc5-240c086a2032)

### 还有别的吗？

无

**Comment by Kagamine-Rinrin** [comment]
因为你这个档被mod污染过了，多了几个npc无法正确初始化所以会报错

**Comment by Kagamine-Rinrin** [comment]
而且人物本来在存档中的名字应该是英文，
但是你的人物列表里除了有'Avery', 'Bailey', '…… Wraith', 'Zephyr'这些正常NPC
还有   '泰勒', '凯西', '塞伦', '帕鲁提‘ 这些个mod里的NPC，这些不做适配直接塞进代码里当然会错误了

**Comment by NumberSir** [comment]
#321
