### ISSUE TITLE
[0.4.6.7-chs-alpha2.0.0]一处错误翻译

### ISSUE THREAD

**Issue by Sphaela** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#345]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 说说你看到的汉化文本内容？

![Screenshot 2024-04-27 at 17-02-01 Degrees of Lewdity](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/30744182/04e18185-2805-4172-a638-e7f9a11e1269)

### 有什么好的想法？

![屏幕截图 2024-04-27 170442](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/30744182/f242b94a-af8e-45b8-974d-7eefc8ea1b7f)

**Comment by Maenoko** [comment]
ruby改了
