### ISSUE TITLE
[0.4.6.7-chs-alpha2.0.0]一处翻译错字

### ISSUE THREAD

**Issue by unins000** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#346]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 说说你看到的汉化文本内容？

![屏幕截图 2024-04-28 012818](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/101944410/55270f93-3d32-42c3-843a-33abec8c4e6e)

### 有什么好的想法？

我**科室**很“美味”的哟。    应为：我**可是**很“美味”的哟。
个人判断应该不是因口音而导致的故意错误
![屏幕截图 2024-04-28 013606](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/101944410/e031f957-754c-42d6-9621-e6a303c98720)

**Comment by Maenoko** [comment]
ruby改了
