### ISSUE TITLE
科学课迟到显示多伦

### ISSUE THREAD

**Issue by sturnu3** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#35]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

想刷校长检查逃课遇Sirris事件，没遇到但迟到后显示的是多伦打断

### 存档 / 代码

[degrees-of-lewdity-hiko-20230905-184944.TXT](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12522503/degrees-of-lewdity-hiko-20230905-184944.TXT)

### 截图

![827](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/144119706/32045d68-0436-4437-b69e-815d82571deb)

**Comment by Eltirosto** [comment]
已修复，请等待新版本发布
