### ISSUE TITLE
[dol-0.4.7.2-chs-alpha1.0.0] 遇见事件加减能力值变成英语了

### ISSUE THREAD

**Issue by ujhfjosnfksd** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#350]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

汉化界面游戏时文字变成 例如“(1) 学习科学 | + Stress | + Science”了，之前是+科学+疲劳

### 存档 / 代码

[degrees-of-lewdity-20240503-215037.save(1).txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/15202155/degrees-of-lewdity-20240503-215037.save.1.txt)

### 截图

![Uploading 未标题-1.png…]()

左下角序号是4.7.2

**Comment by backlight141** [comment]
同翻译问题，悉尼的翻译变成了茜妮。永久更改吗还是翻译错误。

**Comment by ujhfjosnfksd** [comment]
![未标题-1](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/168848101/c1089e79-a94b-4523-be76-982a4ebb5036)
好像照片没传上去，补一下

**Comment by Kagamine-Rinrin** [comment]
> ![未标题-1](https://private-user-images.githubusercontent.com/168848101/327936898-c1089e79-a94b-4523-be76-982a4ebb5036.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NDc4MjAsIm5iZiI6MTcxNDg0NzUyMCwicGF0aCI6Ii8xNjg4NDgxMDEvMzI3OTM2ODk4LWMxMDg5ZTc5LWE5NGItNDUyMy1iZTc2LTk4MmE0ZWJiNTAzNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNFQxODMyMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZWJiMjAwNTNiMjdkMjAxZTkxNWZjMDk3YTUyOThhY2QwYmMzMTExYjY0NzVmZjZkYTAxYmY3M2Q2M2QwY2E0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XR7rsXvZASDfFyDsZ5VUFcY5062qYxmMMm73FNTmneg) 好像照片没传上去，补一下

这里的词条漏了，请等待更新。
