### ISSUE TITLE
[0.4.7.2-chs-alpha1.0.0] 在寄生蟲妊娠後期不再會不時大量增加性奋與压力？

### ISSUE THREAD

**Issue by luke72927** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#352]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这既不是对游戏报错的反馈，也不是对汉化文本改进的建议

### 说说你遇到的问题？

原本在寄生蟲妊娠的後期，會不時大量增加性奋(Arousal)與压力(Stress)，但現在這一性質似乎並未顯現出來，是在新版本被修改了嗎？

**Comment by Kagamine-Rinrin** [comment]
麻烦来个档

**Comment by luke72927** [comment]
補充，在v0.4.5.3-chs-alpha1.12.0時，在寄生蟲妊娠的後期會不時大量增加性奋
![v0 4 5 3-chs-alpha1 12 0](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/96789117/151bccbe-33f3-4ee8-9318-26d754ec6d41)
更進一步比較之後，發現最早從v0.4.6.6-chs-alpha1.0.0開始，變成只會在每天睡醒時增加性奋，以下的附圖是v0.4.7.2-chs-alpha1.0.0版本的截圖
![v0 4 7 2-chs-alpha1 0 0](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/96789117/f05da323-a8ac-46fb-8e53-92e6c1de09bf)

在原作的Blogger未發現相關說明，但也許是在改版為v0.4.6.6時所做的調整？
