### ISSUE TITLE
[v0.4.7.2-chs-alpha1.0.0] 丰收街存在许多未翻译内容

### ISSUE THREAD

**Issue by yuban01652** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#353]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 说说你看到的汉化文本内容？

![捕获](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/38140455/9a6be5d7-cf99-40ef-a338-477d6deb90e9)

### 有什么好的想法？

任意新开档即可见。需补全翻译

**Comment by Kagamine-Rinrin** [comment]
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/43258604/aef6ddf6-8b06-4a56-86ea-142ef5965bc4)
之前报过这个问题的呢，已经修复了的
请等待新版本发布

**Comment by yuban01652** [comment]
好的，谢谢

**Comment by yuban01652** [comment]
您好，该翻译在 [0.4.7.5 chs-alpha2.0.0] 似乎仍未修复？新开档可见，效果和主楼图一致，pub等未翻译

**Comment by wx348055736** [comment]
对于包括丰收街在内的一些漏翻现象，曾尝试自己修复，结果发现这部分漏翻内容的翻译数据是存在的且替换内容还有 pos、fileName 和 pN 的值大概是正确的，可能是实现替换功能的程序不太适用于当前游戏版本。
浏览器在加载游戏模组时控制台有报相关的错误。
![QQ图片20240512171631](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/69603006/7b9e0ecb-bf7e-46a9-ac99-66290d1e5861)

**Comment by ZeroRing233** [comment]
（我是围观群众二号）
楼上这张图再展开看看能发现是文本替换时错位了，但汉化组这个文本替换写得也太酷了，只能坐等大佬修复了...
<img width="1435" alt="文本错位反馈" src="https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/167677210/ddcf3155-400d-43b3-81ff-28cbc3de774d">

**Comment by wx348055736** [comment]
关于楼上的，找不到替换文本确实是错位，但是问题在于我根据 0.4.7.5 版的源代码文件测得的替换文本的 pos 和汉化模组中的是一致的，但是替换文本的功能却表示那个位置的文本是另一段内容，存在一些偏差，不知道这个偏差是如何导致的。
