### ISSUE TITLE
[0.4.7.5 chs-alpha2.0.0] 部分事件未汉化完全

### ISSUE THREAD

**Issue by yuban01652** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#356]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 说说你看到的汉化文本内容？

在被跟踪后返回事件
![捕获](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/38140455/a3e77cce-a692-4378-9dbd-15dc7508194a)

在潜伏者对战时
![捕获2](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/38140455/91d3fb07-1dbe-40df-a07c-3476038ae1c5)

衣柜中
![捕获3](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/38140455/12faf615-4155-4d43-9ed3-ae1cf952c2b1)

教学时的星星图片缺失（属性中星星正常）
![捕获4](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/38140455/39854b42-d8ed-4fef-bb09-95dcda346d11)

湖边考古工作站剧情
![捕获5](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/38140455/e97b00e6-db98-4100-95d1-3d93df38a639)

### 有什么好的想法？

补全汉化

**Comment by omvjro** [comment]
第二张图的“left”和第三张图的服装颜色已修复。剩下未翻译的部分原文还未抓取。学科图片可能要等图片包更新。
