### ISSUE TITLE
[0.4.7.5 chs-alpha2.0.0]海风咖啡馆厨师打搅事件报错

### ISSUE THREAD

**Issue by UphealLaw** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#357]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

打搅中途偶遇的bug，此时点直接迎来高超会进一步报错（图2）
返回上一步转而直接高超会正常进行不会触发bug

### 存档 / 代码

[degrees-of-lewdity-20240516-035757.zip](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/15326458/degrees-of-lewdity-20240516-035757.zip)

### 截图

<img width="1192" alt="dolbug2" src="https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/155638614/692f953e-124e-44e4-ada8-4b9e362633cc">
<img width="390" alt="dolbug3" src="https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/155638614/73ddc219-30f5-4a36-b3e9-df371bbb5903">

**Comment by NumberSir** [comment]
原版依然会出现，非汉化版问题
