### ISSUE TITLE
[0.4.7.5 chs-alpha2.0.0]博物馆-靠三角马演示赚钱错误

### ISSUE THREAD

**Issue by UphealLaw** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#358]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

显示金额与实际赚取金额不符，且文本未变色

### 存档 / 代码

[degrees-of-lewdity-fallen-20240520-064501.zip](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/15371036/degrees-of-lewdity-fallen-20240520-064501.zip)

### 截图

<img width="967" alt="dolbug4" src="https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/155638614/22d57a9d-3aa3-4aad-b44b-68596b02b8ec">
<img width="1140" alt="dolbug5" src="https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/155638614/8a64a6a1-b496-40a4-865e-08b562de230d">

**Comment by NumberSir** [comment]
原版问题，可能他们忘了显示时加上小数点
