### ISSUE TITLE
校长惩罚事件汉化

### ISSUE THREAD

**Issue by sturnu3** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#36]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议

### 说说你看到的汉化文本内容？

![828](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/144119706/51372caf-94d4-4c3c-b67a-af03083533b1)
![829](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/144119706/7fd61b59-8c41-4dcf-aa4b-f29b355dd0bd)

### 有什么好的想法？

“It's…okay”翻译成“可…可以的”或者“没…没关系的”，“可以了”不符合语境
“西里斯的女儿可能会自觉闭嘴”，原句“Sirris' daughter may be off-limits”，off-limits意为禁区/碰不得，或者“不可染指”，总之没有闭嘴的意思

**Comment by Eltirosto** [comment]
已改，请等待新版本发布
