### ISSUE TITLE
无法查看日志 0.4.7.5 chs-alpha2.0.1

### ISSUE THREAD

**Issue by 1Shirotori** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#361]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

无法查看日志

### 存档 / 代码

[degrees-of-lewdity-Fly-20240524-054459.save.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/15422979/degrees-of-lewdity-Fly-20240524-054459.save.txt)

### 截图

![IMG_6257](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/128384390/160a7e6d-8816-4545-9914-20af260dfacb)

**Comment by NumberSir** [comment]
#360
