### ISSUE TITLE
[0.4.7.5-chs-alpha2.0.2]贴图分离

### ISSUE THREAD

**Issue by ryou1016** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#363]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

会出现手和其他物品贴图分离的问题
咖啡店服务生、厨师，神殿的祈祷以及小摊的脱裤子选项都会出现此问题

### 存档 / 代码

[degrees-of-lewdity-20240602-003929.zip](https://github.com/user-attachments/files/15522563/degrees-of-lewdity-20240602-003929.zip)

### 截图

![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/148300019/ffc438f2-35e6-4016-a7c2-b21ed2c99167)

**Comment by NumberSir** [comment]
#332
