### ISSUE TITLE
[0.4.7.5-chs-alpha2.0.2]圖片無法正常顯示

### ISSUE THREAD

**Issue by NkeoPatch** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#364]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

無法加載任何以圖片形式存在的組件

### 存档 / 代码

[save.txt](https://github.com/user-attachments/files/15531801/save.txt)

### 截图

![Screenshot_20240603_172926](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/93478678/71681c25-d3e1-4038-853c-4a9ee7997ed4)
![Screenshot_20240603_172924](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/93478678/33b8c517-7c97-44e6-8ad0-303046bf9a56)

**Comment by NumberSir** [comment]
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/52584526/f0c3efd3-3978-436f-9b3d-12ee65c7c0d4)
你没下载图片包
