### ISSUE TITLE
0.4.7.5-chs-a2.0.2几个小问题

### ISSUE THREAD

**Issue by yundixx** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#365]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 说说你看到的汉化文本内容？

有一处舌头翻译成了手指
![2d87e7b0358d0fe971e60334d8ff4635](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/115039247/f33181a2-d7e9-4854-b3cb-1448d23e7ce0)
![98abe97cfc46f9c4e1f4f1fe08de3dc5](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/115039247/5a140f95-9feb-45e7-a7e6-cab71515de01)
另外，这里的own it应当翻译成宣称，承认，大方承认而不是抢过它
![dbe2bbd7ece238a42924325c2be2fb15](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/115039247/cd83232e-e9e9-4e74-a0ec-ea0afbd926c7)
![47273c83beefba81b507c0953d7909a1](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/115039247/d887b68e-8774-4371-95ba-aebd4e740465)
![d087ffd10a7109d866600dc1dc9ef294](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/115039247/3bef6e92-bf92-449d-a496-292a2d033590)
还有上图当中的flyover之前都是翻译成天桥的，走楼梯上立交桥也太怪了

**Comment by NumberSir** [comment]
已改
