### ISSUE TITLE
[v0.5.0.5-chs-1.0.0a]安卓版无法加载mod管理器

### ISSUE THREAD

**Issue by Satori114514** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#367]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

v0.5.0.5-chs-1.0.0a 安卓版游戏左下角没有mod管理器

### 存档 / 代码

无

### 截图

![11](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/107775309/19597cf3-bad7-495d-9317-9cd1ee20f38d)

**Comment by NumberSir** [comment]
无法复现，详细说明使用的系统，版本等

**Comment by Satori114514** [comment]
> 无法复现，详细说明使用的系统，版本等
华为手机mate30 安卓10
![00A83C1A6C21B4738E1EF55E22A684CD](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/107775309/ddbb98a2-4d12-43d3-81d1-933936e50fe1)

**Comment by NumberSir** [comment]
> > 无法复现，详细说明使用的系统，版本等
> > 华为手机mate30 安卓10
> > ![00A83C1A6C21B4738E1EF55E22A684CD](https://private-user-images.githubusercontent.com/107775309/339245133-ddbb98a2-4d12-43d3-81d1-933936e50fe1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyODUzNDAsIm5iZiI6MTcxODI4NTA0MCwicGF0aCI6Ii8xMDc3NzUzMDkvMzM5MjQ1MTMzLWRkYmI5OGEyLTRkMTItNDNkMy04MWQxLTkzMzkzNmU1MGZlMS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QxMzI0MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NmY1NDZmMDAzN2JjNWQzOTI4ZDg1MDBkN2Q3OTFjMGUxNTgxM2U0MzdkN2Y5MWZkNDk0MWE2OTcwOTk2NWRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bETILJuMW2Rb6DYCtA0WA4eIeojfocHL73DquPTQCL0)

polyfill 版本呢？也有同样的问题？

**Comment by Satori114514** [comment]
> > > 无法复现，详细说明使用的系统，版本等
> > > 华为手机mate30 安卓10
> > > ![00A83C1A6C21B4738E1EF55E22A684CD](https://private-user-images.githubusercontent.com/107775309/339245133-ddbb98a2-4d12-43d3-81d1-933936e50fe1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyODUzNDAsIm5iZiI6MTcxODI4NTA0MCwicGF0aCI6Ii8xMDc3NzUzMDkvMzM5MjQ1MTMzLWRkYmI5OGEyLTRkMTItNDNkMy04MWQxLTkzMzkzNmU1MGZlMS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QxMzI0MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NmY1NDZmMDAzN2JjNWQzOTI4ZDg1MDBkN2Q3OTFjMGUxNTgxM2U0MzdkN2Y5MWZkNDk0MWE2OTcwOTk2NWRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bETILJuMW2Rb6DYCtA0WA4eIeojfocHL73DquPTQCL0)
> 
> polyfill 版本呢？也有同样的问题？
polyfill 版本也没有mod管理器

**Comment by NumberSir** [comment]
你下载zip直接用html玩吧，多半是手机webview问题，但是华为更新webview很麻烦，不如直接玩html，或者在线版

**Comment by Brownsugarduck** [comment]
同样的问题发生在IQOO neo5s
![Screenshot_20240623_072323](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/88658724/d8ea953b-b2b5-4dbc-b1e7-e9fb661e602a)
