### ISSUE TITLE
[v0.5.0.5-chs-1.0.1a] 內衣(下裝)顯示問題 

### ISSUE THREAD

**Issue by nasekaoru202** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#369]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

進到衣櫃或是購買下裝畫面的時候會跳出警示框，內衣(下裝)的部分無法正常顯示

### 存档 / 代码

[Dol存檔碼.txt](https://github.com/user-attachments/files/15845609/Dol.txt)

### 截图

<img width="1915" alt="螢幕擷取畫面 2024-06-15 113739" src="https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/147237592/af23ede9-4ed1-469a-8c7d-05c2e4d3da69">

**Comment by nasekaoru202** [comment]
讀檔打開之後還是會跑出警示框以及無顯示內衣(下裝)問題q
<img width="1921" alt="螢幕擷取畫面 2024-06-16 121723" src="https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/147237592/a62e6a2b-3ba9-416b-8e62-3ae986ba6f83">

**Comment by NumberSir** [comment]
#368
