### ISSUE TITLE
［0.5.0.5-chs1.0.1a］温度提示汉化不完全，及个别文本疑似错误

### ISSUE THREAD

**Issue by XonlookerX** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#370]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 说说你看到的汉化文本内容？

![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/61648955/bf1cb28d-45be-4640-b68e-818262652c21)
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/61648955/eef079d7-c1a9-4b84-bc4b-8dc2e3d18bf6)

**Comment by XonlookerX** [comment]
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/61648955/9e14652d-24fc-40bb-82dd-6fb9d2db9f6c)
看起来应该没有这个“没”字

**Comment by omvjro** [comment]
都已修改，请等下次更新
