### ISSUE TITLE
[v0.5.0.5-chs-1.0.1a] 打开衣柜或者商店的内衣下部分会报错，并且穿不了

### ISSUE THREAD

**Issue by y5353030** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#371]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

0.5.0.6版本，我本地下载的游戏或者在线版都会报错
报错信息如下：
0.5.0.6 Error (:: Hallways): <>: cannot execute widget: 0.5.0.6 Error (:: Hallways): <>: cannot execute widget: 0.5.0.6 Error (:: Hallways): <>: cannot execute widget: 0.5.0.6 Error (:: Hallways): <>: bad conditional expression in <> clause: Cannot read properties of undefined (reading 'pregnancy')

### 存档 / 代码

这里是不是只能传图片，没法传.save文件啊，存档码太长传不上来

### 截图

![Snipaste_2024-06-18_10-30-50](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/49383525/cab34a91-aec3-4370-ab53-0c6266ec5b37)
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/49383525/1ceea215-d803-4a38-a4fb-b198981da059)

**Comment by NumberSir** [comment]
你这是 0.5.0.5 版本啊

**Comment by y5353030** [comment]
我截图的是0.5.0.5的图，但是在线版早上我也测试了一下，导入存档也有这个问题

**Comment by NumberSir** [comment]
有没有装其它mod
