### ISSUE TITLE
0.5.0.6-v2.17.2 版本裡衣櫃的上衣部分報錯

### ISSUE THREAD

**Issue by ahhiisme** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#373]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

打開衣櫃的上衣部分會無法顯示，如果點擊更換套裝切換顯示的話會報錯，換不了上衣

### 存档 / 代码

[N4IglgJiBcIQpgcwE73gZwLQHsBmmAbeAdw.txt](https://github.com/user-attachments/files/15882356/N4IglgJiBcIQpgcwE73gZwLQHsBmmAbeAdw.txt)

### 截图

![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/143791571/66635549-3ce9-4010-8d3c-f21ec708a6aa)

**Comment by NumberSir** [comment]
有没有装其它mod

**Comment by NumberSir** [comment]
不清楚是什么原因导致的，你的露肩洛丽塔裙的颜色缺失了导致的这个问题，对于这个存档打开浏览器控制台输以下代码可解决：

```
V.wardrobe.upper[24].colour = 0
```
