### ISSUE TITLE
为什么没有无Mod启动器的版本了

### ISSUE THREAD

**Issue by xzhxtl** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#375]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这既不是对游戏报错的反馈，也不是对汉化文本改进的建议

### 说说你遇到的问题？

我去年底在这里下载的版本直接汉化了,但隔了半年现在再下载发现还要在Mod管理器里添加汉化和图片,可是我使用了joiplay来玩游戏,这导致根本无法添加文件

**Comment by 404bako** [comment]
甚至无需提问：https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/issues/236

**Comment by xzhxtl** [comment]
那有没有办法在joiplay上也能添加mod,或者可以把汉化文本以及图片mod合并进带Mod管理器的版本？
