### ISSUE TITLE
[0.5.0.5-chs-alpha1.0.0]批量修复衣物bug

### ISSUE THREAD

**Issue by TillMist** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#376]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

pc有钱 显示花费0磅且存款不够

### 存档 / 代码

[新建 文本文档.txt](https://github.com/user-attachments/files/15915823/default.txt)

### 截图

![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/168953813/8388c799-339c-4d12-a636-5b476383cedb)

**Comment by NumberSir** [comment]
存档码文件发错了

**Comment by TillMist** [comment]
[存档码.txt](https://github.com/user-attachments/files/16115495/default.txt)
这个对了吗？移动端没有当时的原存档所以是重新回孤儿院衣柜触发了一下这段

**Comment by NumberSir** [comment]
是原版问题

**Comment by NumberSir** [comment]
#10
