### ISSUE TITLE
[0.5.0.6-(ML-v2.17.2)-(chs-2.0.0a)]  金属触手的特征词翻译，尤其是“带标签的”（labelled）

### ISSUE THREAD

**Issue by EdminZ** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#378]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 说说你看到的汉化文本内容？

汉化的替换文本错误：“labelled”——"条纹的"（本应是“带标签的”）
图1：汉化版原文（第一条触手）
图2：英文原文（第一条触手）
![cn ver](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/111834235/894eb2da-e8ea-4e28-b056-5a6b438771d4)
![eng ver](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/111834235/a7db36cd-5e59-4d52-b4b9-3fe2d82a5d56)

### 有什么好的想法？

修改对应翻译，对触手、金属触手、苍白触手与植物人遭遇战的文本进行校对。

### 其他内容

考虑到这关系到成就“宿主动物学家”的达成（需要获得所有寄生虫及其变种——包括机械触手），很有必要对该翻译进行修正。
另，没有了解过替换代码的运行，不知道是对应文本缺失随机选取了文本补位还是严重的翻译错误。

**Comment by omvjro** [comment]
已修改为“带标签的”，其他部分会陆续校对，谢谢反馈。
