### ISSUE TITLE
神殿内文本翻译缺失

### ISSUE THREAD

**Issue by 1235789gzy1** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#38]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

神殿内战斗页面 女NPC长袍上衣以及贞操带未能翻译

### 存档 / 代码

后缀由 .save 修改而来 （看起来github并不喜欢原本的.save后缀） 
存档位于第二页的第12栏
[test1.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12549029/test1.txt)

### 截图

![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/52618207/eaa6e18c-ec63-4956-9545-7fc1a9115087)
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/52618207/29fa774b-c6fb-490d-836d-7faef78d9fa2)

**Comment by 1235789gzy1** [comment]
看起来我似乎选择了一个错误的tag，抱歉。

**Comment by Eltirosto** [comment]
文本描述已汉化，动作选项还在查找需汉化内容

**Comment by Eltirosto** [comment]
已汉化，请等待新版本发布
