### ISSUE TITLE
[0.5.0.6-chs-2.0.0a]异装罗宾+性玩具导致的童贞堕天使

### ISSUE THREAD

**Issue by ACE-DustofStars** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#380]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

当触发异装罗宾在学校剧情，随其一同进入学校医务室并进入嘿嘿嘿环节时，使用假阳具会导致系统认为天使玩家失去贞洁从而转变为堕天使（尽管仍然保持贞洁特质）。由于实际上未失去贞洁特质，这应当被认为是一个漏洞。

### 存档 / 代码

[bug反馈.txt](https://github.com/user-attachments/files/15945096/bug.txt)

### 截图

![Screenshot_20240623_225338_Degrees of Lewdity](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/173618896/de200957-428e-49f7-941a-2c132e33bf74)
![Screenshot_20240623_225348_Degrees of Lewdity](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/173618896/304d7a91-d535-4f0c-bc0f-0aa28900a4cd)

**Comment by NumberSir** [comment]
疑似原版bug
