### ISSUE TITLE
【0.5.0.6-chs-alpha2.0.0】上学的那个五角星图片不显示

### ISSUE THREAD

**Issue by wuyuzegang** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#382]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

上课和图书馆这里都不显示，不知道别人是不是也不显示

### 存档 / 代码

N4IglgJiBcIQpgcwE73gZwLQHsBmmAbeAdwjABcBPEAGhHXIENz4ZQwA7BADxgBY66NFFgBzgDoBXAAyyATAACAgQESAWgHops6Xw7bZAZgB0APQBUAYIMBGABwHp8AKQBegKEBGgJMAhgIQAmgAhAH8A/gDk4uIAl8EAcgCswAAqAA8QAOKRAD8AQbZ8SgDCACsA8bYQAMUAkgAbxABXAN+SAFuRAEYAvgCZ0o5yuQACABPiyLbwAIIAj5YAVgAl5sMASwAj4hwAZwANyAAnAGyRQzKyfACx/sT9ALMAygBdFQB+ALvrV7KhjhsmAAjgAXuroJYAVoAVcCABkACQAabZpAAEjbcABCAE2AGQ2AAisW4AApPPMALK9NTEUIAWpuZWOACilgAs5wAPdsdkiAGJEFkAJ0AdPEIFsAE5uiUAHzygADCQZYti6WaAFyGgLdgB29IAXggAA+ABe4ACHpgAPABphoAdgUjngAFUAM8AA9ylE9JQ2pxlMIATwBRRzSDkAefGAH5HN1WktQTVEOJ8AB+6DogDq8YAOwBpACVAFWAD7GSgAZpqACajeWADV5gAaMQAa6MANdohq2U6zABHtsrAGy1I4nXIyksAEmsyJZJ34gDa3GMAG4AN0ACKWAD6APsAO9ocHgBCYMHXoHIFCIMBAABkwN1kIxkJQAAQAJXgDgmAIX8SmwSRgPgZBLwAN2/MBGG6Ih0DYegmGQcgiWYVhoFOQwnWlJ07CdGxTmkGw6EfABbeBniYaiAAcYBsYjTiSaQ6GIeBmAAC2ggB5boljQjhGFol8CDARBePIEoCAgiBUMEDhsGIGBOPAABjXDQAIRgAGtcM03AIOAxhOA03o6FMxANLobBYOgrTGAYDTjHsKjv0QeByAEpzkBctzoGkDziOkdjpEMORpCdU4+Fi6U6Go7BgN4ghKFSeAmOg5hJFQVDoHvEBqJgJKQHIO8bGlYwnSSGh7GMOw7AalrWI8wwGtOYw5FOBqkmMQw2r4YwkkomwTHihqbGMPhOpquQ5BoJ1jGkJbuqSTruukeqBqSJ0aAG6QkpG05KJGmwlsmgQTDImgRqSAQBulJaVsMSi7GMU4kpsULYum2a+supqBBsEbFv6r6uuMaUfs+giAF1rNAUroF+qiqvhg72ulNqVqSPGPJ+7q2u60HtvGgbTiWmwBohsGms6hm5oakbdAauRVppziVtxmgatnAG+Gxkw5HGkbpXqibZtBmbpSZ0K+BpmblZhtrObihqTCSKWRsMJmBpscaTD4WXaux0KbCRhG6CMyhGOwThyHQWZkBgoqHzAWiGHE5i8II3GoqdNbKJAeCCEkYzkYqr2MAYv38MIuwIvwii6HDyOYDkaOaLj32YET3HaeauxQ4z3DDBz2OfaYguA7sMXyLO9PGAjqOaE97347rpO5E205S5btus6rrv8/9pPDDm5Oy9bzPoGzjuY7H2uJ9xqeOLTsO59wmxR7z1fC7sAj9cH7fh7R/ea4T+uCL4ZrZ4vvel9z6+e9xpX7Gb8/5+kK/u7XnYJWTpoqP3ns/TuB8b5Jz4PhXqYCK7/3HkfPgsMB4IKsi/auACj5jUut/cuI8sEr2gbjJIMU7AEJ3jASuxCoHvzsPtHQGDoC0MgW/QB+0xpb0IdAPgSDD71wJroPgLC/50I4bg6Uc0qFPwEaQyhhFqYsMXuwnB9dZwJTPrw8RajkEaIImRFhEDl70MAaXJ0TpRFD3AfIhhpciLaOoZfCR6ik7H2imLGxu87HmNxug7xRC9GCKTtKa4TiL6qNMZI+uYSYrWJ/u3YJCjJbUy8YkoJ0S3G4xyVPFRvjC5hMukkWRtjXH6MInEua6SdEFIDmEwwkseHOKia/bJ0ojakQSbwkxbSKmw1YroCJZTknvxemREpxi6mVLkI06UpTcKtOwf0l6A9dBiOmbDXqREanOP4eUkJWyLHDNwvs0Za95am3sCwthWSVlDQ6bsuRBzSHSMIvffJLyxkcQ6ScmhmzJZi1nFMr5FzHrHT+S485hSdYRW6XsgFZ1SKQt0Xcw58zhaGGaZExF5C8mBKhWi15pxZzjIJaivp6KB7zIWSxAFwdRFPN/vS96hhaWEspa8yxU9IW3M5WMxhQ0mU+KRnQRirl0CMB8gABVQLBF8iJW4EGIIwSgykQDivQJKnyL5nhaV4tgbAoF3yfm/NQLyiBCrrhtiAAA+neEAZI5VgCctAeA4cACUl5IIIFwJweAUAbXYEYo+VKhVQAcHddBBIkgEBUiApIQquBW5CDoIwSQ5BsCSqckSMAkrkIBpgMmggqb6AGuICURgIawCpSytwSq0ByDIEjnQLSClyC8U4IgSt1bUowCbS2+gkB4DdG/PRZghUQBSWohQQtghh2juQKkWOL5M3MVbdgaio65KpSbUaydX4yDYEvBhHy5BAgQWQEIAguB+3NvgIILSyAjUEEArRLd0Ei0pofSVKtVJHLZSAg2gdP7qJVtfEgRgWlqDQGLaWsDjEqTfiMler9JbQNVtSMGtDpavZSowCxDdW7mB1DAz5QqodujYAgJQYgyAKBdtI/hwqIH50EANZHcgLBwxiQLSIVjFVGAcFI4gHjSEiD8fvV5DgHAu1ib43ewd6AF3flmLJsDoaOAsak1O7ALlNNqbw5p7Tg7kKcAMnJ3jEnFM/q0pu7dhmNM1q0zhn9vFW64HklmgN8nrOwe/a29zX4tIsGQO+GS5BfOFsbTpqSEXngO3IHF2S7klpTukrJLIh6wBAfcqHZL5AsgKXUiFDydACsADF9INs0gV8CxGas9XKxl8gqQKvgQUu7UKaWwPcHHSwQq9Vf19YwMp1K/WCNozoJ2hg2AfzgWAs+ktrm6AcEkExRgIg4M/sjcQPM34IDPu6HRKgz4YuDsTfABI35n3ECQ8gIyDbtuCAs4xfrebHxaXQAtv1yAnN9v8+hwQ5aiQjskIgQCXBoKfsB6Wxi8BGLw+QAlr8lBc3oEYvpGD9BGKo/VXZrgm70Do8x6ql8PsuAHcvG27z2IM2Zo4P+7oYAzvPZAAAL0NajX6mk1sfvo7gSgtqgLiei6HNplAzslRZxQM1l4jUQBp1pAyK2Y6MTIPmqXt6xUSvw+BSCDa4B5tF1AMVWPc6q6bRZPyAUscVbmxp1dovLwIG6ODjXzvYCVSovxCSRVHXOtde61uXq6A+vgH6yNga6AQBwvbv7zAXzs94pgEoCRLyau1fAJD3A8yQA7Q6p17qXXwDdZ671UPI+FptZn/D75I2IngC1wvgfS/B4IKHkA4eq/R5AAB5AWP6/wEb83/3RfYIl7LyHivvr/W9+U6778Q+R8RZb8XoP5ew+V7nyAGvuufL2+As8MA7PcLrgD+vtvm+u/b6j7vhytvVWH/IMf0/a+J8b+n1v2fd+bUL5Hd+M/q/mfhfh/lfl/jfj/tXjZLui+JeNxHxNBO6OrjhDZnQKgLgEQCFs5iZj+smrxKgBwPxBQKrj5FDsgNiNRtjtriAATr9tRLmq3NgIgMgbWkhF5kIKrjOtwAGratup2hwIgLamnragkLMFSOGK5tZFeG7nZCFA5MJPACFgAGrQRjYcBoSSAoEsBeYdqTYlI2Q8TOyEYgAqrICHbYDHYUZpZaSJqZrUQdZzaFQCA352bUSmSYSe5pYY5KGIQEC2o056GDaBauSPhUA0IvacCOHuyhy44i4cDQZCRLBKHkCATipgDuw9aXbrZqaPjAiRwUZ9QgAcCMRaS6H8QUZprqbMA4EmFxGIBiQJGUCzCwSOyx4JG7wtyICcCMB5i+SRpaoREaqoANFCbQYVZgC8BTYgC4D5SybkD5QVyCDw5aR+HlGTa0zTYWTIATFTGhzwCUDwBpHbH8A2TiRLGmEHbx46TugcAKTK4mFPorrTGoCtzKHfjoC7EmEzpapdolCdoEAQDPAWYcDREUbSHZrwCqFXq1H+6hRHRfT35TqhH7bmFHZ0Ttovjh7IC2paFI6XiIDnEpQIAviqQJ4ECXhOzPr2QVQZpzZ+EmGcAUAlFaRuHiqPjM5SThHTGBECFCFaGx4sB1HfiuSzq4naGdHFGlHXa0QQDQnqFZxm6qow6gBkEIDuwzGXhCBTGalpqI48RfgdE0nw6yaFSaTwTdFiTGlAR5rKZv7TGfg8QMB2mLJ0BUZcZE4n6SmjoEAlounGnPqqSQQBmpRmThogD8Q0kzaYIgBqnQR8FUEvg0EE4QCbqq4T7ICWkUAwagBCatxoF95fgUnnY/omks64QCYWk9HFkCYsBMSs4BYRlCYQAGqAldoFkWaDElnSFUY0ZZQ5RfgLGoA0L4xJBETgoDyLTzIHQgC9mS5gD5GQCiRKEq7QCqmGo0lCC0QaHyHFEpHfgxn0YRbfiozrnHq7lblAQ0mRohYHkhTSFEC4AYSnmxkbkXmAY7m877ldbSEdoZZoSIBvmaSXmfmrbfkxnun2EAVAWCAfnXngX3lUTrbUQ5mvnnnAVwW7k3kYQxn6pxzQXoWwXbnwW3k/lnE6QEWbmYVfmkUxnuYZGUXvnEVYUIXiIzFoANpnlUXMU0U4WIXbyWmMAQTOzDqMUYU8VgW0X8VVlWlrloXcVXksVSVsVlnhmAWEX0DUWSV8VsVCaJpiVEWKW8V3lsUpQZq8QGWaUSV7nKW9DSGcBOTARzaoXamZpqpsDSEplE4eU9lKroDhjcAfaq64CoDK4oSkFATqm2pVrw4ilGmwA0Fxk4kxUGljHwC2rJohZOF3igC4DZRMnzEwYxQmRQaZoamACLyoAIbKIA0ceVM6smhVLEsg5FZVL4gAzpqADw+oAAvxgAFUqAA5ETVUvHVQVdmTAENpla1bAIACya5VgA/qmABleoNblflQ1aNbuRNXNi+IAMfKgARX5LXsX1VMncklVZUamAA87oAI76+1w1q1x1LVm1sAgA1u6ADb1oAPGB11K1R1RVzVMxpVD1IAgAyvKADR6h9YdY1dAJgJLPdRqYADEBgAkQHlWAB98aDSNXdb9adS+IAP+agA/UpkjcA2CAAHaoALfRgA4aaAABRoAL8BgAMAGADlcoAPiugAIW6AASpoADnmXqtVn14NxV0NL4gAhBaACw5oAJsRKNt1MGJ1k1IAgAKWmAAC7oAMYR/NgA+nIU2ADQ7oAAxKgAyPmADusSLV9TSRtRqTLfLUrWrYAM5ygA/EaADkmoAPA6Ot4N4t/1gAA4GAAXCWSNIM4AzYAPfKgAg5GADhzuzUNZzWtfbRqYAHBmgAfGYM2ADVcQDYAEG2gAZHk1U2o3W614ToyxmRXxkpVxU6S2rEAUAcbkC2r94IEamJUZ3JX6nZ3pV50drCVF0BQl0ZV/WoYewHWo3fXB0vhVW21rU8482wCdW9UDUc1g1rXjXN0vgzULU91o363bV7Uj3t160T2wCXUz1i390gAvXvWL2i1Zw/Vz2wDA3r0wCQ3j0Y2wDw1I0n3rUr0gA4142E2k2U202M2s3+3LWj3clYqd2wCADQcoAKMRN9v9Ut0tgAoYqAAnEcbRrdrbvSnbTCA4AB8RgATOkM3m3AOb3e1R2x0J29BJ2B1UC535113F0GkwCUKaRJW2oOwMCLGklwRSo9EBVBUllio2n+WBXBRs5I46Ql4QB8GvHOlemKkarORN5OT8OQWen2nPyzmuRXbSolBoSqU0kyWMA0mOmhHoAIDoBaQ0l4XBS1alU1EA61YR4drNk0lHmyTuZcA0l6VmnJTCUWW7lJU0k6NPG9qgUzGSC+mg66P0ZeM0mcBCC2H0Zo246hnBm7mRNBkuZyWRm7nRn8WqX+m7maNCP2maRSPURpPZN+V5NsOmkeMaOCPkAlNJM8Q3guOaT8Stwdq9abkgl2YKT5Q0ksBGVpoQC+M1Z0BUkaU+FKG8SqUYAuTw6bnw5DNqOjNVrGTLFoD6oOMzPjO7lUArPAVMDxWaQpRaahb2PYFOQxkJCKPvjBTFSLMMBrWgAqOwAMOCVwFVH6W3MPl6YmM7nAAQkWa+nhrSGxNhkeVURfgUBWqiqgAXNhGoU3MgB3M9EPMgAONwEvP6bOYAv0BfPLZrm/OBn/OYuAvW4gvRzgtXOiOmlwtqNwsIvPPlavOaaovoDos/NirYuQSMsVRAvGFFSgu0HuaXPcnXPsNkuMOyXQuPOTqDW6bIsA4fORHfOot/MsuotW7At3hctEt8skt5qCv3O3OiuIvUuSvvOfMs4YvSvDFRPxOmtKscvWqEs8sQvKMCs6sCWwtOuUvQtItvN0sMtyvMsWu/nssEs2rYhOnkCnMNrn6pl2StqJ5irSTwFGo0GpkECMQCGXhSTs5U5ulkNunYAHmtqvFDmsDTZOFFszHYC8BbHEAq4brqTLHDowQ2oslhvykosLx0DHNp7nE5UauTq8lzrOvCuqSRoEnl0vilQx6jOBO0uwAtHQTmoxxJa4SzmJr+papgYaF9NaZKH5RrWmE8TVtmtxNjsZ7sNpOdQ9sVMgCABZyoALOJcNgASxaXg5OFNyPfMvsZMiVZNullOXsm1TVPtlPaOjMvh/tanNNGqXovjECdpClURoDeObY9OMnzHBOLYaVrNLu8TrZCYnrNqGPUuHO7mpmoy1Z2FWP4ablMBClOtW7Yc0kHHwCOFtOwDuan4UlbEZFMcamk6Ph87ISpSm7cuhHEtQswvCuXhuvitiSowgCzs/gZ47to12ZuxaHTuaT1GNHQY+tICafNGtGQBpVjXmkZFZnqt5k1k6Zzb5mw6lk2kNlA4DvWds62MtkK7tk2dwf1m4Rs6dlJrfpYvmvhmJMgCABrcpeMk6F+F2oS+GF9Nl7DF+F17NererACF4AFeBgAj7qXjrsviADsroAF1yT72A2OuXgAltrZeKUgAFeAA3cjVdHFC324J+S7AEO6W247AOO1eAE2AEE7ANiBZEQPO2EVLi5KgEwChpSVu2E7uwgQe/KzuSVCe6aWk2lqpZe4ACxpgAcMFFcem5PCPpMFP7fZOAdHffshu/v/tndaMXdgecAtOQewDQezonrwf2PdM3jIckHTH9PtP2yYfYcbtstke7kKSEeaTEc0kRz4cgBfg6oXlUdLulUl64fppgb0eHFceSQta/goAHHhfbGY+wCfhqSA9quQuOsiuOcUtrZivSHScvj9flnzuMSKcb20FzbNq9fqcjG6faejFNEtFtGGdow/UZmmeoXmcFlWfFncN2feeNlqMy+NkuetlkCCGW7ZSY7y8Oe+dSFMuBdoTBexcRmaupdRct2RdxcyfG+dq5PXgpeheZfZc4ewAFdFclflfJSVc1fivCV+rWvFGGT9tgZECg7JpIeGEh/wBh/pofc2p9vhlCCG5R8x8R9d76nuwRpduwDoCdqYSTcsAoC92yAvPcSZ+B9+5ssQRCCoabuF/hMwaXR/yeUVGG6NdalW4OzxM2tLwNftr8RNdCvqMtepRtejsdcu6Ts9fTsgDYj0Z5sLtS7E96GgQk+fqbuhOs+SSGoGTqrzfHtFO2n7erfsMbfbc5u7fvuHdfuzknc38fs3dXfOmP9ot3cQfMemEwelsdMIfvcNqhxHVUOe6X7iswjIA9cOwPWrABncZpkQekA9AhR3h6oEaOX4OjruQY6E9YyqAK8hx2QCYCGAX4YgMdjdiUB+OdjEIry3J6ksnWzXSnpJzp7iQGe8/GCGKi367llOnPNTkyx05jEcyWLHgQL307tEKKIvYzpmRTq5kxISvBztL1Vxll7OpaRXqrhV5ud1eHnCqJrwUE/pdeNnALnEyC5LsbepvS3hGWi5m8reCXK3slxi5O9koLvKroVxzYe8KuC3H3nZV74U92+XRF1sUVH4jtyCB/Lrp4xn7/FvwUkb/k+CXbCD4Av4OzFBgsob9t2DfF8L5E7RfYM8vrQIak2P6H8gOujF8Ftx272Er+b7U7rfxDbvsf2wHWAKByf7OwX+9LN/q0w1JPdYOGgzpvCz/6fd/+dfakqsz+4vgsOOXQFvAN0yEdMAadCHnAOh6w85m6EZAfCwObf9UBaPdARj3f4alY8D2X8MhEzi4DMBlpHyCwKE6UCHW1AynrQIk4089WFfF8KEIHw5YFOyQ9gRz1U6ttueAgrTri2GKfC9OQveKn3TDgmcJB8LKQVLyLIFl5BFZHTEoNYZNkuAqvdzmzjrJa9VcOg7bHoJxagAjeiXSdDbzMEmDbelgk3nbxvQ2Csudg1wY4NnLFc8unvEqN73y61dpCfvZVv7jEhGRBOKfCPLH29wHVW40fHkWn2iFIkE+aEJPi+BFFh4M+okbPnADSq/hc+GRPkU7CQDPCecpfFUhXyiEKjc+c2YwnXzVHF9m+gWfCrAC8HoQvwXfAlh4POEWjaBrXfweqUCEeMp2rbEANhBIHsdF+S7NtJIG6C/g1+xwkJkkN3apCwA6Q/Xkewn65Cz2uQy9oAFKAq9g+yKHSM5hPpP0mUI/aVDzu1QkALUPKHXc8xBYxoQkQ2FQcv+L3DoYhw+7fcUOu5H7v0NAFDCcOIw6HqDzmFTDSOMwxARswWEo80BmkDAeWNgC49529FPASONv4k9qcdrEThTzE7D86B1wqlrcNgCeifw3olns8M0gcC3hpjbgfzy+GmsNOvAwXgZwBGi9gR4NSQU50bKyD1BUI9MkP2kGloVBbZNQciM0Ha9S06I/zlGKxGmDiREXfERbyMHW9EupIh3ulwpG/oqR7vOkS4Ly5Mi6uto4wfaKH6kk/BdAdrotwnbddeuHoubDgJ9EvgeMiAKSLn1/AsB4h6/cAFNzYEgBwxkYw9mZCyGnt9u57NbnmItqAB35RTEX9ihWY6/umLv6iTcx+QmoZd0LHP9ix0k0sfdw/6tDv+r3XcjWJ6H0SvuAAtDiAP+7DCge7Y6AUR1gHdjemMPXsYIAR4vgkehzPFoOLoDDjmhko5DDsOHj7CpxqAQTmTzOHGDFx1PJ5u61WyMD1xxEwHtuKDoboVOXPQ8bz2+GnjBB/wkQYCLF4gjJecIh8bL1kxaDvBYI9Qe+LV5yEvxXnNEbaT16sSFWCTQwbiOAkEjwJwEpLvb3JHO94JTgxCV7ypHMiHIGaf3lakD6cjneofIUR90j4CjU+w0jQbROOGZpiAHAVIMFgPbTTQSL6A8vH376TZQAEor3DxDwrHC8SWo6Tkuxok7TIg6AX8JBDAAeFOuqoovtyQ1HUsy+soyvkdP4jIATpio/SMrnVTXT1RJfFvmaNoJrTBOBAqtGGhVb1dPBgMvySP2HY4Tx+eEoIW6IBwgBwwCAQHsN3+5QRgxDE54bpmwC78Mh5rdict04nxi8xgAdJ8LaAkmkZf2EmlD7+Yk0phJL0ZSSAOFQhoeBycmPdKxcHasV0LrFfdNIjYzSBh0GHgC2xZkjsTAJI7lZRhswyjv2LsmrChx6wzmRqnMz49OOU45CFBgPbeS5KonHKUuKuEBSpOwU5GajKeERT2eUUrgT8KPF8CYpZ4oQcLzEHi80IaUgTA+IExPj1BsI5zs2URFqDay34kqV2QxGwV60xXVlvNwMH1S8R5veORYPMEkjrBqXWwXBOQkITXe9I5ig4OZHgzzhjow2S+AtG4TE2U/QiVkGICS5WxpEnPgakYhGQEcdEkMdN25J7tDIBM6MbqR7YvtuJkk3wTDOplCT7+IkxmVo326XQ6hl7QAPHagAfHk0GZtVmUWIHnzzF5t3MsarOUlVidyocdSahwFm9D0OAwljmLIMkSyjJ4PEyTLJ7Fw8+x1HSnrRyVkOSVZD3GHv2wnGYCzK6AednrP5bnCoZy4k2QwJk5Vya5YUtgbuNeHRS7ZsUk8TzydmJTd4V48QTeNBF3iZBEIx8XL2fGCVXxbmAOaoMKmNkUR2UkAH+PQyYiKp2IpdoAE9NaqbAHoXTYCRTCkkS+FYW29U5IAWhenJy4D1qRVGbHG1RzmVc2qKE9wf/PQmQzi50MsfgEJjEIzp+7oxVMgHxJURIhkovTK1USFtzscjQ30l3LYkKLsh9pL

### 截图

![Screenshot_20240625_155052_com vrelnir DegreesOfLewdity](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/34293098/e75186d0-eb7b-4dde-8d6c-915a68c91623)

**Comment by wuyuzegang** [comment]
![微信图片_20240626085631](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/34293098/6e9418a7-d0d1-4a01-be2c-e513e81d7c15)

**Comment by 404bako** [comment]
这存档码发送方式真是人才啊……你下次可以保存到文档里发送，粘贴不全的
顺便星星是最近几个版本老生常谈的问题了，汉化组说是modloader的问题，在修

**Comment by NumberSir** [comment]
存档码不全，下次直接发送 txt 文件

**Comment by wuyuzegang** [comment]
> 这存档码发送方式真是人才啊……你下次可以保存到文档里发送，粘贴不全的 顺便星星是最近几个版本老生常谈的问题了，汉化组说是modloader的问题，在修

兄弟知道在哪找新版的攻略吗？跟老版比改的东西太多了，有点玩不明白

**Comment by NumberSir** [comment]
#362
