### ISSUE TITLE
[v5.0.6-chs-2.1.0a]裁缝修复衣服后又把我穿的内衣撕了

### ISSUE THREAD

**Issue by Riderdmyf** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#384]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

总共被撕了2次，都是这一件运动内衣，上一次我sl之后到公园把内衣脱掉了，才没被撕，这次又遇见了，不知道是什么原因。
![QQ截图20240702090713](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/41277853/f9a58069-5190-43b6-8bb7-4ed869975ab3)
![QQ截图20240702090722](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/41277853/13e48934-b900-4d64-875a-11e1215f5302)
![QQ截图20240702092347](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/41277853/1ebaa36b-e755-47db-9e42-933a618405ed)

### 存档 / 代码

[degrees-of-lewdity-拿玛-20240702-091428.zip](https://github.com/user-attachments/files/16060480/degrees-of-lewdity-.-20240702-091428.zip)

### 截图

![QQ截图20240702093618](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/41277853/7c1c08bd-09f4-46e5-abae-4bec5a5de296)
没有跳出红字，不知道这一张图行不行...

### 还有别的吗？

我导出的存档位置在购物中心1楼，只要上楼去裁缝店修衣服就100%会被撕掉运动内衣了

**Comment by Capaletric** [comment]
同遇到了，贡献一下其他视角
最新版游戏+以模组形式加载的BESC美化。在换上磨损的衣物时提示衣物出错，穿着这件衣服去裁缝处修复导致内衣爆掉
之前曾有一次外衣+内衣一起爆掉的情况，但已覆盖无法复现
![5QVTJ1V@ Y2H~U76Q1G5_SN](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/174432831/60800ecd-a963-4ba3-8d6a-791ce9af66b8)
![2](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/174432831/4bbe4722-13bb-4dff-b958-e9ec29e0070f)
![3](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/174432831/8d4ab6c1-e491-415b-bf4e-219eea54696b)
[degrees-of-lewdity-Capaletric-20240702-174034.zip](https://github.com/user-attachments/files/16066087/degrees-of-lewdity-Capaletric-20240702-174034.zip)

**Comment by Riderdmyf** [comment]
> 用过和衣服耐久度有关的mod或言灵吗

楼中另一位朋友的情况我不清楚，我平时用的是[https://github.com/sakarie9/DoL-Lyra/releases/tag/v0.5.0.6-2.1.0a-0701](url)这一位的besc+csd+sideviewbj的版本，没有用过其它的mod或者言灵，我把我在这里上传的存档导入到纯净的v5.0.6-chs-2.1.0a中试过（就是截图里的那张完整截图），也会出现这个情况

**Comment by Capaletric** [comment]
> 用过和衣服耐久度有关的mod或言灵吗

没有用过。实验后发现与出错的服装无关（脱掉出错服装依然会爆内衣），且疑似只影响上装（修衣时穿着的下装未受影响）

**Comment by Riderdmyf** [comment]
> 同遇到了，贡献一下其他视角 最新版游戏+以模组形式加载的BESC美化。在换上磨损的衣物时提示衣物出错，穿着这件衣服去裁缝处修复导致内衣爆掉 之前曾有一次外衣+内衣一起爆掉的情况，但已覆盖无法复现 ![5QVTJ1V@ Y2H~U76Q1G5_SN](https://private-user-images.githubusercontent.com/174432831/344971295-60800ecd-a963-4ba3-8d6a-791ce9af66b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMTM0ODAsIm5iZiI6MTcyMDAxMzE4MCwicGF0aCI6Ii8xNzQ0MzI4MzEvMzQ0OTcxMjk1LTYwODAwZWNkLWE5NjMtNGJhMy04ZDZhLTc5MWNlOWFmNjZiOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QxMzI2MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYmNlZjE0YzU4YzRkMzVhZjliZGM0YjUxNmMyYjk1YTJjYWZkM2FkNWJmYWUxNzgyNWRiMGNlM2JmMzU2NDFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BfaCo4dLDnM_Ctkr1ghs-tKCv7vkGoQeumZsHWR0gHI) ![2](https://private-user-images.githubusercontent.com/174432831/344971430-4bbe4722-13bb-4dff-b958-e9ec29e0070f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMTM0ODAsIm5iZiI6MTcyMDAxMzE4MCwicGF0aCI6Ii8xNzQ0MzI4MzEvMzQ0OTcxNDMwLTRiYmU0NzIyLTEzYmItNGRmZi1iOTU4LWU5ZWMyOWUwMDcwZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QxMzI2MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yN2Y1NzYyMjhiMWExNjFjMjQ2MjgxYjFkYTk1ZDA0NmRkYmMwZGFlYTQ3YjY2Y2M0ZGNkNzU2ZDAxOWRmNTRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VQZplQicwmYx14hnf3Mqy9kUs6llNqOLRUKgUy5agGA) ![3](https://private-user-images.githubusercontent.com/174432831/344972077-8d4ab6c1-e491-415b-bf4e-219eea54696b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMTM0ODAsIm5iZiI6MTcyMDAxMzE4MCwicGF0aCI6Ii8xNzQ0MzI4MzEvMzQ0OTcyMDc3LThkNGFiNmMxLWU0OTEtNDE1Yi1iZjRlLTIxOWVlYTU0Njk2Yi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QxMzI2MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZmUyN2U4NTliZGYwOTVlNGNiY2I5YzAwMDI1YjBjMzQ3MmFiYzNiYzYzZTJjZTFhYzYwYzdlNzVkYjgwZjMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.p6qR-tltJA7I8f_Ce7PtLU2dEJ0HIpRuXZoC5Yr7Rkc) [degrees-of-lewdity-Capaletric-20240702-174034.zip](https://github.com/user-attachments/files/16066087/degrees-of-lewdity-Capaletric-20240702-174034.zip)

话说，我在最新版里也遇到你截图里的那个意外问题了，那种同时包括上装和下装的衣服，如果只有其中一部分损坏了，另一部分是完整的，然后选择“寄出所有已损”的方式寄给裁缝的话，貌似就只有损坏的部分会被寄出去，等你再拿回来穿的时候就会报这个错...我的连体泳衣和女巫服都中招了（捂脸）

**Comment by Capaletric** [comment]
> > 同遇到了，贡献一下其他视角 最新版游戏+以模组形式加载的BESC美化。在换上磨损的衣物时提示衣物出错，穿着这件衣服去裁缝处修复导致内衣爆掉 之前曾有一次外衣+内衣一起爆掉的情况，但已覆盖无法复现 ![5QVTJ1V@ Y2H~U76Q1G5_SN](https://private-user-images.githubusercontent.com/174432831/344971295-60800ecd-a963-4ba3-8d6a-791ce9af66b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMTM0ODAsIm5iZiI6MTcyMDAxMzE4MCwicGF0aCI6Ii8xNzQ0MzI4MzEvMzQ0OTcxMjk1LTYwODAwZWNkLWE5NjMtNGJhMy04ZDZhLTc5MWNlOWFmNjZiOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QxMzI2MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYmNlZjE0YzU4YzRkMzVhZjliZGM0YjUxNmMyYjk1YTJjYWZkM2FkNWJmYWUxNzgyNWRiMGNlM2JmMzU2NDFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BfaCo4dLDnM_Ctkr1ghs-tKCv7vkGoQeumZsHWR0gHI) ![2](https://private-user-images.githubusercontent.com/174432831/344971430-4bbe4722-13bb-4dff-b958-e9ec29e0070f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMTM0ODAsIm5iZiI6MTcyMDAxMzE4MCwicGF0aCI6Ii8xNzQ0MzI4MzEvMzQ0OTcxNDMwLTRiYmU0NzIyLTEzYmItNGRmZi1iOTU4LWU5ZWMyOWUwMDcwZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QxMzI2MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yN2Y1NzYyMjhiMWExNjFjMjQ2MjgxYjFkYTk1ZDA0NmRkYmMwZGFlYTQ3YjY2Y2M0ZGNkNzU2ZDAxOWRmNTRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VQZplQicwmYx14hnf3Mqy9kUs6llNqOLRUKgUy5agGA) ![3](https://private-user-images.githubusercontent.com/174432831/344972077-8d4ab6c1-e491-415b-bf4e-219eea54696b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMTM0ODAsIm5iZiI6MTcyMDAxMzE4MCwicGF0aCI6Ii8xNzQ0MzI4MzEvMzQ0OTcyMDc3LThkNGFiNmMxLWU0OTEtNDE1Yi1iZjRlLTIxOWVlYTU0Njk2Yi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QxMzI2MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZmUyN2U4NTliZGYwOTVlNGNiY2I5YzAwMDI1YjBjMzQ3MmFiYzNiYzYzZTJjZTFhYzYwYzdlNzVkYjgwZjMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.p6qR-tltJA7I8f_Ce7PtLU2dEJ0HIpRuXZoC5Yr7Rkc) [degrees-of-lewdity-Capaletric-20240702-174034.zip](https://github.com/user-attachments/files/16066087/degrees-of-lewdity-Capaletric-20240702-174034.zip)
> 
> 话说，我在最新版里也遇到你截图里的那个意外问题了，那种同时包括上装和下装的衣服，如果只有其中一部分损坏了，另一部分是完整的，然后选择“寄出所有已损”的方式寄给裁缝的话，貌似就只有损坏的部分会被寄出去，等你再拿回来穿的时候就会报这个错...我的连体泳衣和女巫服都中招了（捂脸）

感谢提醒！我没有送修而是选了自动重购，除了吸血鬼上装，睡袍也出过这样的错，检查发现衣柜不知为何有一件完整的睡袍和一件碎了的睡袍。一直不知道衣服为什么会变成这样，现在感觉可能是和你遇到的情况类似的原因？谢谢！

**Comment by Riderdmyf** [comment]
> > > 同遇到了，贡献一下其他视角 最新版游戏+以模组形式加载的BESC美化。在换上磨损的衣物时提示衣物出错，穿着这件衣服去裁缝处修复导致内衣爆掉 之前曾有一次外衣+内衣一起爆掉的情况，但已覆盖无法复现 ![5QVTJ1V@ Y2H~U76Q1G5_SN](https://private-user-images.githubusercontent.com/174432831/344971295-60800ecd-a963-4ba3-8d6a-791ce9af66b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMTM0ODAsIm5iZiI6MTcyMDAxMzE4MCwicGF0aCI6Ii8xNzQ0MzI4MzEvMzQ0OTcxMjk1LTYwODAwZWNkLWE5NjMtNGJhMy04ZDZhLTc5MWNlOWFmNjZiOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QxMzI2MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYmNlZjE0YzU4YzRkMzVhZjliZGM0YjUxNmMyYjk1YTJjYWZkM2FkNWJmYWUxNzgyNWRiMGNlM2JmMzU2NDFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BfaCo4dLDnM_Ctkr1ghs-tKCv7vkGoQeumZsHWR0gHI) ![2](https://private-user-images.githubusercontent.com/174432831/344971430-4bbe4722-13bb-4dff-b958-e9ec29e0070f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMTM0ODAsIm5iZiI6MTcyMDAxMzE4MCwicGF0aCI6Ii8xNzQ0MzI4MzEvMzQ0OTcxNDMwLTRiYmU0NzIyLTEzYmItNGRmZi1iOTU4LWU5ZWMyOWUwMDcwZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QxMzI2MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yN2Y1NzYyMjhiMWExNjFjMjQ2MjgxYjFkYTk1ZDA0NmRkYmMwZGFlYTQ3YjY2Y2M0ZGNkNzU2ZDAxOWRmNTRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VQZplQicwmYx14hnf3Mqy9kUs6llNqOLRUKgUy5agGA) ![3](https://private-user-images.githubusercontent.com/174432831/344972077-8d4ab6c1-e491-415b-bf4e-219eea54696b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMTM0ODAsIm5iZiI6MTcyMDAxMzE4MCwicGF0aCI6Ii8xNzQ0MzI4MzEvMzQ0OTcyMDc3LThkNGFiNmMxLWU0OTEtNDE1Yi1iZjRlLTIxOWVlYTU0Njk2Yi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QxMzI2MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZmUyN2U4NTliZGYwOTVlNGNiY2I5YzAwMDI1YjBjMzQ3MmFiYzNiYzYzZTJjZTFhYzYwYzdlNzVkYjgwZjMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.p6qR-tltJA7I8f_Ce7PtLU2dEJ0HIpRuXZoC5Yr7Rkc) [degrees-of-lewdity-Capaletric-20240702-174034.zip](https://github.com/user-attachments/files/16066087/degrees-of-lewdity-Capaletric-20240702-174034.zip)
> > 
> > 
> > 话说，我在最新版里也遇到你截图里的那个意外问题了，那种同时包括上装和下装的衣服，如果只有其中一部分损坏了，另一部分是完整的，然后选择“寄出所有已损”的方式寄给裁缝的话，貌似就只有损坏的部分会被寄出去，等你再拿回来穿的时候就会报这个错...我的连体泳衣和女巫服都中招了（捂脸）
> 
> 感谢提醒！我没有送修而是选了自动重购，除了吸血鬼上装，睡袍也出过这样的错，检查发现衣柜不知为何有一件完整的睡袍和一件碎了的睡袍。一直不知道衣服为什么会变成这样，现在感觉可能是和你遇到的情况类似的原因？谢谢！

哈哈哈，我也是意外发现的，因为我把连体泳衣设定成预设的泳装了，在某天我把损坏的衣服寄给裁缝之后，在上游泳课准备换衣服的时候，就发现这件连体泳衣只剩半截了，导致我只能跑去悉尼那买了身新的（

**Comment by NumberSir** [comment]
疑似原版问题
