### ISSUE TITLE
[0.5.0.6-v2.18.3]加载后图片包提示警告

### ISSUE THREAD

**Issue by RL3461** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#386]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

在仅加载 ModI18N-0.5.0.6-chs-2.1.0a.mod 和 GameOriginalImagePack-0.5.0.6.mod 的情况下Mod加载器提示 GameOriginalImagePack-0.5.0.6.mod 缺少 banner.png

### 存档 / 代码

未进入存档

### 截图

![Screenshot_20240703_020527_com vrelnir DegreesOfLewdity](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/151621585/4eac223c-bd53-480f-8f19-45057c11d7e4)

**Comment by NumberSir** [comment]
不影响游戏正常进行，可以忽略 warning 提示
