### ISSUE TITLE
[v5.0.6-chs-2.1.0a]发现了2处未翻译的文本

### ISSUE THREAD

**Issue by Riderdmyf** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#388]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 说说你看到的汉化文本内容？

![QQ截图20240704201839](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/41277853/13411a5d-d4c6-48f0-b8e2-119760bf3824)
此处为在神殿中与悉尼进行遭遇战时
之前误用了带mod版本的截图，现已更换为[v5.0.6-chs-2.1.0a]纯净版的截图
[漏翻处的存档.txt](https://github.com/user-attachments/files/16098662/default.txt)

![QQ截图20240705101034](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/41277853/d5a85a7e-6d5a-4ee3-93d5-a2ed192488b4)
此处为罗宾在校园内遭受惠特尼霸凌时
[罗宾处存档.txt](https://github.com/user-attachments/files/16104114/default.txt)

### 有什么好的想法？

辛苦大大们啦~

**Comment by omvjro** [comment]
两处已修改，谢谢反馈

**Comment by Riderdmyf** [comment]
> 两处已修改，谢谢反馈

好耶！感谢！
