### ISSUE TITLE
Hospital Parasite 事件 点击 "免费手术" 报错

### ISSUE THREAD

**Issue by Lyoko-Jeremie** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#39]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

![图片](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/6566869/39522f7b-82fe-429b-b3a8-d05d353cd4a7)

如图，我查了一下官方英文原版的的代码，Hospital Parasite这个脚本文件里面没有引用变量`farm.milking`，目测应该是汉化的时候手抖出了错。

### 存档 / 代码

[degrees-of-lewdity-t-20230908-112641.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12555223/degrees-of-lewdity-t-20230908-112641.txt)

### 还有别的吗？

我正在写 [Cheats Mod](https://github.com/Lyoko-Jeremie/Degrees-of-Lewdity_Cheats-Mod)，这个存档开局就修改了全部数值，所以也不确定是不是作弊引起的，但我目测应该不会是

**Comment by Eltirosto** [comment]
这个问题在原版中也能复现，非汉化版问题。但无法确定是原版问题还是你的模组修改数值的问题，建议在未修改数值情况下尝试复现。
