### ISSUE TITLE
0.5.0.6-chs-2.1.0a   穿过运河前往公寓区被堵时，翻译有误。

### ISSUE THREAD

**Issue by Moliyi** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#390]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 说说你看到的汉化文本内容？

![2b7c2d18debd96506727a154c5dddbeb](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/51506057/ebee8c7f-6df3-45ba-abfb-a10e568d82ad)

**Comment by omvjro** [comment]
请问指的是截图正文第一段吗？已修改为：你把圆润的男人从你身边推开。他差点摔倒，但还是一脸坏笑。“这两天我没法信任你了，”他摇了摇头，“但你也没有违禁品。走吧。”
