### ISSUE TITLE
性别错误，对修女错误使用“他”

### ISSUE THREAD

**Issue by sgj123456** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#391]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 说说你看到的汉化文本内容？

![Screenshot_20240725-222226_Via](https://github.com/user-attachments/assets/770cefa4-944a-4331-b034-a1c5365ec01f)

**Comment by BluexBerry6475** [comment]
英文的They/Them沒有性別之分 基本問題不大
