### ISSUE TITLE
[v.0.5.*]建议将游戏和wiki中的“软体怪物吞食”改为“软丸吞”

### ISSUE THREAD

**Issue by AEEESEEEA** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#392]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 说说你看到的汉化文本内容？

“软体怪物吞食”

### 有什么好的想法？

在我对维基丸吞页面进行简单修改翻译的过程中我发现了这个问题。

以下是我已经翻译的内容：

> 已经确定的是，主开发者Vrelnir对软丸吞有些纠结。他对软丸吞的欣赏就像他对触手的欣赏一样。尽管如此，他表示偏好硬核丸吞的玩家会对游戏中得到的东西感到失望。
> 
> 软丸吞和硬核丸吞的区别在于，硬核丸吞涉及到被丸吞者的完全消化——最坏的情况下会涉及被丸吞者的死亡。Vrelnir并不喜欢这样。软丸吞的重口程度要轻得多，被丸吞者不会被消化，只是被整个吞下。
> 
> 原文为：The difference between soft and hard vore is that hard vore involves full digestion of the participant - worst cases involve death of the participant. Vrelnir is not a fan of this. Soft vore, however, is much more lighter. There is no digestion of the participant involved, only that they are swallowed whole.
> 
> 最初，该开关被简单地命名为“丸吞”。在[Version 0.2.14中有一个微妙的变化，开关被重新命名（为软丸吞），以适应游戏中的丸吞情况。
> 

这里看第二条，所谓的Soft Monster Vore不是“软体怪物”的意思，而是“轻口味（软、非硬核）怪物丸吞”的意思。

https://zh.wikipedia.org/wiki/%E5%90%9E%E9%A3%9F%E6%80%A7%E6%84%9B%E5%A5%BD
维基百科也可佐证，不过wiki采用的是“柔性”soft、“烈性”hard的说法，以供参考。

我已经修改了wiki丸吞页面除标题外的内容，如果认为可以的话，可以将wiki页面标题一并修改。

感谢汉化组的付出。

**Comment by NumberSir** [comment]
wiki待改
