### ISSUE TITLE
[0.5.*]建议将游戏中文本“石楠树”或“石楠”改为“帚石南”

### ISSUE THREAD

**Issue by AEEESEEEA** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#393]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 说说你看到的汉化文本内容？

游戏中的“石楠树”and“石楠”。

> 你正身处荒原中。 一大片延伸到远方的石楠树出现在你面前，而农场在另一个方向，远处可以看见的是大海。 云层低垂，山顶笼罩在浓雾之中。
> 
> 你看到在一条通向石楠树的小路旁有一个标志，上面写着：“危险，请勿靠近。”

### 有什么好的想法？

根据wiki，

> Upon entering the moor, the player will get a notice that a great plain of heather stretches before them. A Heather is a **purple** Eurasian flower that grows abundantly in moorlands and heathlands. They usually grow as many small flowers attached to a stalk.

此处的“石楠”说的是紫色小灌木Heather帚石南，不是Photinia石楠。译者可能望文生义结合了石楠花的某种特性理解成了石楠树，但实际上荒原既然是一望无垠少有树木的地方，显然是不可能有石楠树的，更不可能是“一大片延伸到远方的石楠树”。

由于帚石南有非常明显的象征意义——会产蜜的大片紫色花朵，其花蜜可能是荒原淳药的主要来源，在此建议做严格区分，并予以强调。以下为学名来源。

https://www.plantplus.cn/info/%E5%B8%9A%E7%9F%B3%E5%8D%97

**Comment by 404bako** [comment]
（路过）感觉贴维基会更直观一点。顺便春药的事，游戏里不是有诡异的花来着
https://zh.wikipedia.org/wiki/%E5%B8%9A%E7%9F%B3%E6%A5%A0
![Z$%DGF(MCDF%PBV~308AYH0](https://github.com/user-attachments/assets/054e8ff0-cf8d-48e1-86f7-588e98fd75ea)
