### ISSUE TITLE
没有mod管理器

### ISSUE THREAD

**Issue by Qkat9** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#394]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

部分手机进去后左下角没有mod管理器

### 存档 / 代码

no

### 截图

![Screenshot_20240727_105404_com tencent mobileqq](https://github.com/user-attachments/assets/b6fdc5c8-90db-4267-9be4-3f33394ec090)

### 还有别的吗？

no

**Comment by NumberSir** [comment]
https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/issues/348#issuecomment-2252781532

> 用 [Kiwi 浏览器](https://kiwibrowsercn.github.io/) 启动游戏，打开控制台看看输出是什么
