### ISSUE TITLE
缺少banner及膚色顯示異常(版本:v5.0.6-chs-2.1.0a)

### ISSUE THREAD

**Issue by blackteawww** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#397]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

下載最新版本遊戲、漢化包及圖片包(版本:v5.0.6-chs-2.1.0a)，使用Mod管理器新增mod後(沒有裝其他mod)，刷新頁面跑出一串提示文字，顯示缺少banner.jpg。
若繼續讀取之前的遊戲存檔，會發現遊戲畫面右半部的膚色都變成白色，例如:在羅賓房間脫掉衣服的選項小圖示、遭遇戰時的pc膚色(但這個問題在出現缺少banner提示之前，就已經有了，於版本0.5.0.5)。
已嘗試過重新安裝遊戲、重新安裝mod，遊戲裡的性能設定也全部開啟，也嘗試過在圖片包中(資料夾:img/misc)新增banner.jpg，但還是出現一樣的狀況。

這是我第一次使用問題回報功能，如果有遺漏了什麼請見諒，若能補充提供需要的資訊我會盡力提供，謝謝!

### 存档 / 代码

[報錯存檔.txt](https://github.com/user-attachments/files/16402726/default.txt)

### 截图

![image](https://github.com/user-attachments/assets/f20c148b-6e6f-43b4-a7b2-2bb7ee09ef58)
![image](https://github.com/user-attachments/assets/1c895137-da01-4f79-ad3a-1ab96dc3eb6b)

**Comment by blackteawww** [comment]
補充一下，玩的是下載到電腦的網頁版，因為報錯的時候顯示文字太多，所以將代碼用成txt檔上傳。

**Comment by NumberSir** [comment]
缺失 banner 的警告是因为游戏更新了标题图片的显示方法导致的，实际上游戏内一切正常，不用自行添加图片。

**Comment by NumberSir** [comment]
无法复现肤色变白的问题，也可能是新版本已经修复了
