### ISSUE TITLE
[v0.5.1.3-chs-1.0.0a]日志报错

### ISSUE THREAD

**Issue by FLCnhzmry** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#398]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

存档在安卓平台由Lyra-0.5.0.6-7.1版本整合包导出存档码，再由汉化原版加载，
存档加载进入时无报错，但是点击日志时会报错
在Lyra整合包中日志显示无问题，使用存档码导入pc网页版也会有相同报错

### 存档 / 代码

[报错存档.txt](https://github.com/user-attachments/files/16469531/default.txt)

### 截图

![33bbc80f9e473977d5db1d5331a77cd](https://github.com/user-attachments/assets/0b1e2ed2-4058-4483-aa33-7fdd3e30a7b7)

**Comment by FLCnhzmry** [comment]
后来又发现博物馆也有显示报错

**Comment by omvjro** [comment]
应该是存档以前用Mod添加了古董导致，解决方法：在控制台运行如下代码：
```js
V.museumAntiques.antiques = Object.fromEntries(Object.entries(V.museumAntiques.antiques).filter(([k]) => Object.keys(T.museumAntiqueText).includes(k)))
```
这是修改后不报错的存档：
[degrees-of-lewdity-20240807-092306.txt](https://github.com/user-attachments/files/16517149/degrees-of-lewdity-20240807-092306.txt)

建议向Mod作者反馈。

**Comment by FLCnhzmry** [comment]
> 应该是存档以前用Mod添加了古董导致，解决方法：在控制台运行如下代码：
> 
> ```js
> V.museumAntiques.antiques = Object.fromEntries(Object.entries(V.museumAntiques.antiques).filter(([k]) => Object.keys(T.museumAntiqueText).includes(k)))
> ```
> 
> 这是修改后不报错的存档： [degrees-of-lewdity-20240807-092306.txt](https://github.com/user-attachments/files/16517149/degrees-of-lewdity-20240807-092306.txt)
> 
> 建议向Mod作者反馈。

感谢，联系之前设置已命名NPC也有过报错（后来按照GitHub上的方法解决了），应该是以前装过世界拓展模组的原因˚‧º·(˚ ˃̣̣̥᷄⌓˂̣̣̥᷅ )‧º·˚以后再也不敢加这种添加了很多东西的mod了

**Comment by FLCnhzmry** [comment]
> 应该是存档以前用Mod添加了古董导致，解决方法：在控制台运行如下代码：
> 
> ```js
> V.museumAntiques.antiques = Object.fromEntries(Object.entries(V.museumAntiques.antiques).filter(([k]) => Object.keys(T.museumAntiqueText).includes(k)))
> ```
> 
> 这是修改后不报错的存档： [degrees-of-lewdity-20240807-092306.txt](https://github.com/user-attachments/files/16517149/degrees-of-lewdity-20240807-092306.txt)
> 
> 建议向Mod作者反馈。

感谢，联系之前设置已命名NPC也有过报错（后来按照GitHub上的方法解决了），应该是以前装过世界拓展模组的原因˚‧º·(˚ ˃̣̣̥᷄⌓˂̣̣̥᷅ )‧º·˚以后再也不敢加这种添加了很多东西的mod了

**Comment by whrfssb** [comment]
请问一下大佬，这种问题再加载一次存档码仍会出现这种问题有什么解决方案吗

**Comment by whrfssb** [comment]
请问一下大佬，错误修改之后再加载一次存档码仍会出现这种问题有什么解决方案吗

**Comment by omvjro** [comment]
> 请问一下大佬，错误修改之后再加载一次存档码仍会出现这种问题有什么解决方案吗

#412
