### ISSUE TITLE
[0.5.0.6]已命名NPC设置报错

### ISSUE THREAD

**Issue by Fuyuhana** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#399]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

游戏设置内已命名NPC设置更改报错，使用的是Lyra美化包中[0.5.0.6-Lyra-2.1.0a-besc-wax-csd]版本，之前游玩旧版本的时候不会报错，但是后面跟着更新就不行了，尝试过卸载相关npc的mod也没办法解决

### 存档 / 代码

传不了save文件对不起...orz

### 截图

![Uploading 屏幕截图 2024-08-03 184614.png…]()

**Comment by omvjro** [comment]
你的图片没上传成功orz
存档可以把存档代码复制到txt文件中，或修改save文件后缀名为txt后上传

**Comment by Fuyuhana** [comment]
> 你的图片没上传成功orz archive可以把存档代码复制到txt文件中，或修改save文件后缀名为txt后上传

啊不好意思！没注意到图片上传😢
[degrees-of-lewdity-1-20240803-184200.txt](https://github.com/user-attachments/files/16488684/degrees-of-lewdity-1-20240803-184200.txt)

**Comment by omvjro** [comment]
应该是Mod问题，但还是把你这个存档改了，大概不报错了，最好跟Mod作者反馈一下哦。
[degrees-of-lewdity-1-20240805-222917.txt](https://github.com/user-attachments/files/16499028/degrees-of-lewdity-1-20240805-222917.txt)

**Comment by Fuyuhana** [comment]
> 应该是Mod问题，但还是把你这个存档改了，大概不报错了，最好跟Mod作者反馈一下哦。 [degrees-of-lewdity-1-20240805-222917.txt](https://github.com/user-attachments/files/16499028/degrees-of-lewdity-1-20240805-222917.txt)

啊啊啊这样啊，感谢！！orz
