### ISSUE TITLE
身体纹身显示不出来

### ISSUE THREAD

**Issue by whosthegi** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#4]
### 说说你遇到的问题？

[degrees-of-lewdity-1-20230821-163925.zip](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12394070/degrees-of-lewdity-1-20230821-163925.zip)

![screenshot20230821](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/142786624/a843230c-2766-4a26-be56-4fb81d3dc4d8)

**Comment by Eltirosto** [comment]
如果是英文存档是正常情况，纹身数据是随着存档走的，洗掉纹身再重新纹上就正常显示了
