### ISSUE TITLE
衣柜全部送修后收回时打开衣柜报错

### ISSUE THREAD

**Issue by Aliceven** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#40]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

选择将衣柜里所有衣服送修 次日打开衣柜收回时出现红屏报错

### 存档 / 代码

[存档.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12560913/default.txt)

### 截图

![Screenshot_20230908_222601_com vrelnir DegreesOfLewdityWE](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/127491982/edf71d6b-4b52-4226-9caf-dc9cf6a8adaa)

### 还有别的吗？

返回重进就是正常的衣柜了

**Comment by Eltirosto** [comment]
原版问题，已向作者反馈
