### ISSUE TITLE
[v0.5.1.3-chs-1.0.0a]艾弗里相关涂鸦的汉化

### ISSUE THREAD

**Issue by Ydm2** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#402]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 说说你看到的汉化文本内容？

![$FZ2S~UU(49CV17(4CV(R02](https://github.com/user-attachments/assets/fa31ae98-17b2-481c-92d8-ded2e1ad3167)

### 有什么好的想法？

奖杯→战利品；垄断品→禁脔

### 其他内容

战利品一词的来源：![ESZJE7L(BLV7DOOS LX(YPJ](https://github.com/user-attachments/assets/587ac288-5886-4550-a062-6e5397580299)

**Comment by NumberSir** [comment]
讨论后不予修改：

> 个人感觉过度解读了，这俩词大概是trophy和monopoly，trophy出的时候还没有打牌剧情，从词意来说，trophy代表了Avery对外炫耀pc的展示心态，而monopoly本身是金融专业常见的垄断企业一词，用在Avery身上即代表ta是Businessman又代表ta对PC的占有欲望，翻成另一个词完全失去了原意
