### ISSUE TITLE
[v0.5.1.3-chs-1.0.0a]我陷害惠特尼被警察逮捕上頸首枷以後，他就再也沒出現過了

### ISSUE THREAD

**Issue by Brandoyifang** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#403]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

我的主角在生下孩子前放逐凱拉爾讓他被警察逮捕，後來栽贓了惠特尼，他被警察逮捕後就沒再出現過了，數學課跟學校屋頂都遇不到他，去艾利克斯農場開墾農田也完全停留在雜草叢生的進度，請問這是不是凱拉爾被放逐後導致的BUG？還是因為我沒把惠特尼從頸首枷救出來導致？

### 存档 / 代码

[目前.txt](https://github.com/user-attachments/files/16576907/default.txt)

### 截图

![1](https://github.com/user-attachments/assets/d2160027-3d7e-4e9b-98ac-8c7a37d55246)
![2](https://github.com/user-attachments/assets/c4196a25-5e2f-4583-8901-55dac6a9440b)

### 还有别的吗？

就算去地下妓院也不會看到惠特尼，我試過了

**Comment by Brandoyifang** [comment]
> ### 在提问之前...
> * [x]  我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
> * [x]  我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
> * [x]  我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
> * [x]  我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]
> 
> ### 问题描述
> 我的主角在生下孩子前放逐凱拉爾讓他被警察逮捕，後來栽贓了惠特尼，他被警察逮捕後就沒再出現過了，數學課跟學校屋頂都找不到他，去艾利克斯農場開墾農田也完全停留在雜草叢生的進度，這是不是凱拉爾被放逐後導致的BUG？
> 
> ### 存档 / 代码
> [目前.txt](https://github.com/user-attachments/files/16576907/default.txt)
> 
> ### 截图
> ![1](https://private-user-images.githubusercontent.com/178123798/356921792-d2160027-3d7e-4e9b-98ac-8c7a37d55246.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0Mjk4MTQsIm5iZiI6MTcyMzQyOTUxNCwicGF0aCI6Ii8xNzgxMjM3OTgvMzU2OTIxNzkyLWQyMTYwMDI3LTNkN2UtNGU5Yi05OGFjLThjN2EzN2Q1NTI0Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMlQwMjI1MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMmNhMzM1NWVlMWRjZmM4MTI3M2Y0YTY5MWViYzNiNDg3NmNmNzQ2OGRjYWFkMTAyMjFkM2E0YzgxYzc1OGU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qQ-b9_XXP_Q1Jlr425JOSUIDBv2osbRci27Q5mjxsts) ![2](https://private-user-images.githubusercontent.com/178123798/356921808-c4196a25-5e2f-4583-8901-55dac6a9440b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0Mjk4MTQsIm5iZiI6MTcyMzQyOTUxNCwicGF0aCI6Ii8xNzgxMjM3OTgvMzU2OTIxODA4LWM0MTk2YTI1LTVlMmYtNDU4My04OTAxLTU1ZGFjNmE5NDQwYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMlQwMjI1MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOTM2MjMxM2NjMWQ1ODc5ODg3ZWI4ODA2YjBmZGMzOWQzMDhjZmVmYjM0YjdkNjM2MDI4ZTYyOTI5NjdjMzgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-0QH9-FbWR5weVfg87uwiaU33zxa8z9bX_BWwLosExU)
> 
> ### 还有别的吗？
> 就算去地下妓院也不會看到惠特尼，我試過了

**Comment by SnowJesseYu** [comment]
我这里也出现了这个问题，上頸首枷之后的行动应该不会影响

**Comment by ReyADis** [comment]
遇到同样的问题，是颈手枷时间结束重置时会检测服刑者名字，翻译为中文的“惠特尼”后重置Whitney状态为闲置的代码无法触发导致其一直处于颈手枷状态，通常事件就统统无法触发了
