### ISSUE TITLE
v0.5.1.3-chs-1.0.0a翻译错误

### ISSUE THREAD

**Issue by yanm66** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#404]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 说说你看到的汉化文本内容？

![Screenshot_20240814_000254](https://github.com/user-attachments/assets/42a32811-7a9f-43d1-b773-ee4d04c8417a)
[degrees-of-lewdity-312-20240814-002415.zip](https://github.com/user-attachments/files/16602708/degrees-of-lewdity-312-20240814-002415.zip)

### 有什么好的想法？

![IMG_20240814_004633](https://github.com/user-attachments/assets/65154450-5c0b-4785-844e-888ddd709e06)

**Comment by omvjro** [comment]
请问指的是“school shirt”吗？已修改，请等更新。

**Comment by yanm66** [comment]
> 请问指的是“school shirt”吗？已修改，请等更新。

![IMG_20240816_000636](https://github.com/user-attachments/assets/d1d6dace-0c63-4677-842f-db95871e0aa7)
👉👈没说清楚，指的是名字这翻成你了

**Comment by omvjro** [comment]
> > 请问指的是“school shirt”吗？已修改，请等更新。
> 
> ![IMG_20240816_000636](https://private-user-images.githubusercontent.com/97488321/358295760-d1d6dace-0c63-4677-842f-db95871e0aa7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MjE0MzAsIm5iZiI6MTcyMzgyMTEzMCwicGF0aCI6Ii85NzQ4ODMyMS8zNTgyOTU3NjAtZDFkNmRhY2UtMGM2My00Njc3LTg0MmYtZGI5NTg3MWUwYWE3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDE1MTIxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmZjQzMTQ5NWQ1ODgzODI2MDJmY2ZjNjEwOTRhYzQzZmE2MTZmNmY3MjczZDAxNWQ2M2Q5ZDFkZWRjMDc0YzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IgTVs9iwOy9Ruw-iRf433hiVK24mUSvkRlfhFXHZ15w) 👉👈没说清楚，指的是名字这翻成你了

好的好的，这个也修改了，谢谢反馈。
