### ISSUE TITLE
【v0.5.1.3-chs-1.0.0a】颈手枷报错

### ISSUE THREAD

**Issue by MorningLights** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#406]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

8月1号更新版本
pl上颈手枷后报错

### 存档 / 代码

[save.txt](https://github.com/user-attachments/files/16622599/save.txt)

### 截图

![Uploading Screenshot_2024-08-15-15-21-27-22_c3a7877071fa066085f34e47f499198f.jpg…]()

### 还有别的吗？

在这之前，警察将pl送上颈手枷时也会报错(回溯一步能看到)

**Comment by MorningLights** [comment]
![IMG_20240815_154548](https://github.com/user-attachments/assets/85261697-b91d-4066-8cff-29675710ef6f)
截图可能没上传上来，补一张(第一次用github不太懂QAQ)

**Comment by omvjro** [comment]
应该是原版bug，请等原版更新。
![dc](https://github.com/user-attachments/assets/0ea02c0a-fcb9-49d2-9f7b-37067c79cb8d)
