### ISSUE TITLE
【0.5.1.3-chs-1.0.0a】猫转化在跳舞舔毛时出现报错选项

### ISSUE THREAD

**Issue by toritorisuki** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#407]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

游戏本体及汉化版本：0.5.1.3-chs-1.0.0a
该版本发布页虽提及舔毛bug的修复，但经过测试，英文原版游戏未报错，加载汉化的游戏仍然显示如下报错：
0.5.1.3 Error (:: Dance Job Stage Dance): <<danceeffects>>: cannot execute widget: 0.5.1.3 Error (:: Dance Job Stage Dance): <<=>>: bad evaluation: Unexpected token ':'

### 存档 / 代码

[报错页面.txt](https://github.com/user-attachments/files/16628509/default.txt)

### 截图

![IMG_1517](https://github.com/user-attachments/assets/1c70acad-7d24-4c16-8adf-7d0cc6706d56)

**Comment by NumberSir** [comment]
#401
