### ISSUE TITLE
【v0.5.1.3-chs-1.0.0a】雪夜天气缩略图不显示

### ISSUE THREAD

**Issue by MorningLights** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#408]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

如题，雪夜(准确来说是下午8点往后)时左侧缩略框内天气图像异常

### 存档 / 代码

[picture error.txt](https://github.com/user-attachments/files/16640742/picture.error.txt)

### 截图

![IMG_20240817_030540](https://github.com/user-attachments/assets/0cd46400-7a48-483f-8c69-c870ed6c0c1e)

### 还有别的吗？

只要一到傍晚下雪就会这样(应该不是汉化bug，不过咱想看看vrelnir知不知道这个bug)
加载的mod只有图片包和汉化包
谢谢你们的无私付出!

**Comment by MorningLights** [comment]
另外，奇怪的是深夜降雪的缩略图却是正常显示
也许只是特定时间的缩略图有问题？
![IMG_20240817_032136](https://github.com/user-attachments/assets/cbd6a638-979e-46a0-9ec5-1b34c2861905)

**Comment by NumberSir** [comment]
原版问题，游戏里没有这个图片所以显示不出来
