### ISSUE TITLE
在酒吧接受米奇委托时出现红色报错框

### ISSUE THREAD

**Issue by Eleus7** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#41]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在酒吧向米奇提出永久提升社交名气时，米奇委托的销毁摄影室照片任务出现了红色报错框

### 存档 / 代码

[bug存档.zip](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12563042/bug.zip)

### 截图

![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/144487675/3cc40629-a889-41b9-af3f-eb9ed068029a)

**Comment by Eltirosto** [comment]
已修复，请等待新版本发布。
