### ISSUE TITLE
v0.5.1.3-chs-1.0.0a猫舞步报错cannot execute widget和bad evaluation: Unexpected token

### ISSUE THREAD

**Issue by CRSWMYHJ** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#410]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

游戏本体及汉化版本呢：v0.5.1.3-chs-1.0.0a
我没有安装任何Mod，是在网页端游玩的。
虽然版本更新中说“修复了与猫舞步相关的问题”，但是我还是遇到了这个Bug。
在多瑙河街庄园跳舞选择 舔毛 的时候出现了这个错误。

### 存档 / 代码

[degrees-of-lewdity-20240820-105806.zip](https://github.com/user-attachments/files/16668307/degrees-of-lewdity-20240820-105806.zip)

### 截图

![123](https://github.com/user-attachments/assets/9a776a57-9408-4235-b062-994ee386a3fc)

### 还有别的吗？

无

**Comment by NumberSir** [comment]
#407
