### ISSUE TITLE
v0.5.1.3-chs-1.0.0a日志报错

### ISSUE THREAD

**Issue by whrfssb** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#412]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

日志报错
按照#398可以暂时解决但是重新用save文件加载仍报错
求去除存档mod信息的方法

### 存档 / 代码

[degrees-of-lewdity-全成就-20240813-154309.txt](https://github.com/user-attachments/files/16726644/degrees-of-lewdity-.-20240813-154309.txt)

### 截图

![屏幕截图 2024-08-23 173256](https://github.com/user-attachments/assets/6e7c47e7-283f-40ec-a203-501eb1566a7c)

### 还有别的吗？

感谢大佬无私付出

**Comment by omvjro** [comment]
不好意思，之前没有及时回应。控制台修改后，需要走一步让存档记住，不然导出后还是原来的数据，下面是修改好的存档：
[degrees-of-lewdity-全成就-20240823-231049.txt](https://github.com/user-attachments/files/16730601/degrees-of-lewdity-.-20240823-231049.txt)

**Comment by whrfssb** [comment]
谢谢大佬——————
