### ISSUE TITLE
【0.5.1.3-chs-1.0.0a】博物馆演示三角马不给钱

### ISSUE THREAD

**Issue by 283952** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#415]
只有观众的小费，最后的一千不会给
![Screenshot_20240826_205530](https://github.com/user-attachments/assets/bf10ed3f-15a7-4f87-bfae-44ab2c0ca3d7)
![Screenshot_20240826_205539](https://github.com/user-attachments/assets/3a10bc65-b941-47a1-8b1e-de5698e37a82)
![Screenshot_20240826_205543](https://github.com/user-attachments/assets/1d7973ef-db5c-4548-a202-0696a9435a58)

**Comment by omvjro** [comment]
代码中未发现问题，方便提供存档吗？

**Comment by 283952** [comment]
[存档码.txt](https://github.com/user-attachments/files/16752544/default.txt)


> 代码中未发现问题，方便提供存档吗？

**Comment by NumberSir** [comment]
原版问题，显示金额与代码值相差一百倍
