### ISSUE TITLE
v0.5.1.3-chs-1.0.0a 猫舞步相关问题

### ISSUE THREAD

**Issue by Pewds233** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#418]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

游戏为未使用mod的纯净汉化版，在进行猫舞步动作时报错并在后续选项中丢失了猫舞步的选项

### 存档 / 代码

[degrees-of-lewdity-20240901-130159.zip](https://github.com/user-attachments/files/16827368/degrees-of-lewdity-20240901-130159.zip)

### 截图

![I97HXM@1}DLBZJW`SF~4$VE](https://github.com/user-attachments/assets/97b4ca4e-5d7e-47d5-abe2-272638b31264)

### 还有别的吗？

猫化程度为65，报错后可能会丢失选项也可能仍然存在

**Comment by NumberSir** [comment]
#407
