### ISSUE TITLE
【0.5.1.3-chs-1.0.0a】监狱买衣服不发货

### ISSUE THREAD

**Issue by 283952** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#419]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

所有衣服买了都不发货，牙齿也扣了

### 存档 / 代码

[存档码.txt](https://github.com/user-attachments/files/16828273/default.txt)

### 截图

![Uploading Screenshot_20240901_174318.jpg…]()

**Comment by omvjro** [comment]
疑似原版问题。
![discord](https://github.com/user-attachments/assets/cba016d4-604e-4774-90ce-7726e99942a2)
