### ISSUE TITLE
与悉尼在神殿doi时文本报错

### ISSUE THREAD

**Issue by Eleus7** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#42]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

与悉尼在神殿进行到第二轮时出现了报错，报错持续了两回合
使用的是正常的1.4汉化版本

### 存档 / 代码

[bug存档.zip](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12566339/bug.zip)

### 截图

![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/144487675/6ed8235a-a818-442d-99fa-a9c9e7b9296d)

**Comment by Eltirosto** [comment]
已修复，请等待新版本发布。
