### ISSUE TITLE
关于最新更新的图片包和语音包，游戏版本为最新的0.5.1.3

### ISSUE THREAD

**Issue by DankerBobcat127** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#420]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

最新图片包GameOriginalImagePack-0.5.1.3.mod.zip，有两个黄色的警告代码，能解决一下吗？玩游戏的时候也弹出过报错，好像还有那个嗯语音包，好像也说弹出了报错，就是那个在那个妓院的那边，马上就把图片发在那个截图上，黄色的是图片包的警告，然后游戏里报错的是那个汉化包

### 存档 / 代码

我用的是手机APK

### 截图

![Uploading Scree
![Uploading Scr
![Up
![Uploading Scre
![Upl
![Screenshot_20240902_164550](https://github.com/user-attachments/assets/3ebb25c8-1a49-482c-a046-732e2a875de3)
oading Screenshot_20240902_164148.jpg…]()
enshot_202
![Screenshot_20240902_164555](https://github.com/user-attachments/assets/61ee876c-8cfc-43b5-90f0-50c2b0f13bdb)
![Screenshot_20240902_174052](https://github.com/user-attachments/assets/5e0b8abe-4f21-4ad2-b3c3-51c2e11dd674)
40902_164414.jpg…]()
loading Screenshot_20240902_164355.jpg…]()
eenshot_20240902_164351.jpg…]()
nshot_20240902_163958.jpg…]()

### 还有别的吗？

暂时没了

**Comment by omvjro** [comment]
图片全部没有上传成功。黄色警告不影响游戏运行，搞ModLoader的大佬好像说过不用管。
