### ISSUE TITLE
旧版本存档在新版本存在日志报错问题

### ISSUE THREAD

**Issue by yinleirenlxy** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#422]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

[0.5.1.3]旧存档的日志界面在日志界面存在报错问题

### 存档 / 代码

[degrees-of-lewdity-20240902-210811.txt](https://github.com/user-attachments/files/16837921/degrees-of-lewdity-20240902-210811.txt)

### 截图

<img width="1074" alt="微信图片_20240902205413" src="https://github.com/user-attachments/assets/e5c6dc6e-461b-468a-ae1f-02028887f925">
<img width="1074" alt="微信图片_20240902205429" src="https://github.com/user-attachments/assets/6564ea15-e10b-4052-b4b2-49ef7278780e">

### 还有别的吗？

只在日志界面出现问题，其余可以正常游玩，而且数学竞赛这些事件在当天醒来也会有提示

**Comment by omvjro** [comment]
是否安装过Mod？若有，请参考https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/issues/398、https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/issues/321

**Comment by yinleirenlxy** [comment]
> 是否安装过Mod？若有，请参考#398 、 #321
没有添加过mod

**Comment by yinleirenlxy** [comment]
> > 是否安装过Mod？若有，请参考#398 、 #321
> > 没有添加过mod
[degrees-of-lewdity-20240905-233731.txt](https://github.com/user-attachments/files/16896987/degrees-of-lewdity-20240905-233731.txt)

**Comment by yinleirenlxy** [comment]
> > 是否安装过Mod？若有，请参考#398 、 #321
> > 没有添加过mod



> > > 是否安装过Mod？若有，请参考#398 、 #321
> > > 没有添加过mod
> > > [degrees-of-lewdity-20240905-233731.txt](https://github.com/user-attachments/files/16896987/degrees-of-lewdity-20240905-233731.txt)

这是我的存档，只用过官方的汉化包和图片包
没有用过其他mod，但确实在博物馆会有错误弹窗，但是用控制台修改报错了，一年多的存档了，还望大佬救我

**Comment by yinleirenlxy** [comment]
我没加过其他模组啊

**Comment by yinleirenlxy** [comment]
https://github.com/user-attachments/files/16896987/degrees-of-lewdity-20240905-233731.txt

**Comment by yinleirenlxy** [comment]
这个是我的存档

**Comment by omvjro** [comment]
北极星/世界拓展也算Mod

**Comment by omvjro** [comment]
还是帮你改了，日志不再报错了，还有问题再说
[degrees-of-lewdity-20240909-153833.txt](https://github.com/user-attachments/files/16927092/degrees-of-lewdity-20240909-153833.txt)

**Comment by yinleirenlxy** [comment]
谢谢你Thanks♪(･ω･)ﾉ
