### ISSUE TITLE
[v0.5.1.3-chs-1.1.0a]高学校异装癖名声时更衣室事件文本问题

### ISSUE THREAD

**Issue by CocLucia** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#423]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 说说你看到的汉化文本内容？

![IMG_20240904_220910](https://github.com/user-attachments/assets/98994adc-ef30-4390-8ff4-799217136f8c)
![IMG_20240904_220923](https://github.com/user-attachments/assets/e1217820-c88c-4569-856f-e58029ca7487)
![IMG_20240904_222925](https://github.com/user-attachments/assets/46ed5ca6-606d-46e4-9087-23f8a4fa7061)
![IMG_20240904_222936](https://github.com/user-attachments/assets/8077d49d-7c5f-486e-9f65-c585d6082924)
[男扮女装更衣室前存档码.docx](https://github.com/user-attachments/files/16872238/default.docx)
[女扮男装更衣室前存档码.docx](https://github.com/user-attachments/files/16872247/default.docx)

### 其他内容

高学校异装癖名声时游泳课前坚持进入异性更衣室时能够触发的该事件中说自己就是喜欢穿异性装束选项里的文本可能有误，男扮女装时说的是喜欢穿男装，而女扮男装时说的是喜欢穿女装，与实际情节不符

**Comment by omvjro** [comment]
原版问题，请等原版更新
