### ISSUE TITLE
 [0.5.1.3-chs-1.1.0a]汉化版中，艾弗里四人打牌约会的倒酒环节，做出正确选择但无法影响四人的牌技

### ISSUE THREAD

**Issue by gengaixingming** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#424]
### 在提问之前...

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

版本： 0.5.1.3-chs-1.1.0a
加载模组：① GameOriginalImagePack-0.5.1.3.mod
                  ② ModI18N-0.5.1.3-chs-1.1.0a.mod

问题：
如下很多图所示，p1-p3（en1-en3）为直接打开html网址，没有加载任何模组下，英文未汉化版的文本内容，即使我看不懂英文也能根据颜色和符号判断出来我选对了酒类，降低了这四个人的牌技；
但是，如p4-p6（ch1-ch3）所示，我在加载了汉化模组之后，中文汉化版在选择了与英文相同的选项后，没有降低牌技的提示，艾弗里甚至还减了好感和亲密

备注：
1.在汉化后的艾弗里打牌约会环节中，我尝试过为他们四个都选同一种酒类，但结果依然是这四个人哪个都对pc的选择不满意【
2.apk和html两个版本我都试过，都有这个问题
3.我不确定这是否我个人的存档遗留问题

### 存档 / 代码

[0.5.1.3.txt](https://github.com/user-attachments/files/16897027/0.5.1.3.txt)

### 截图

![en 1](https://github.com/user-attachments/assets/e2636f43-9c06-43fb-9d6a-935daf18f4f1)
![en 2](https://github.com/user-attachments/assets/5cd052e6-768f-4ae8-b5b8-2b6eaf42a2ed)
![en 3](https://github.com/user-attachments/assets/7efcfab3-00d4-498d-ada4-8dfbc1a00b68)
![ch 1](https://github.com/user-attachments/assets/bd575b72-fe18-43ba-aa1c-bb085b8be235)
![ch 2](https://github.com/user-attachments/assets/87b492ad-47ad-495e-b229-6b18182f4d2c)
![ch 3](https://github.com/user-attachments/assets/e315e25a-de86-4c47-a457-002699963514)

### 还有别的吗？

在这一系列操作中我并未加载任何其他非官方模组

**Comment by Brandoyifang** [comment]
我也有這種問題，我有試過0.5.2.6英文版本的，可能等到下一次更新就會修復吧

**Comment by omvjro** [comment]
汉化把同时参与判定和显示的文字汉化了导致的，已修改，谢谢反馈。
