### ISSUE TITLE
【成就】和【成就加点】中部分成就的翻译不一致

### ISSUE THREAD

**Issue by trlaitioer** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#43]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议

### 说说你看到的汉化文本内容？

游戏版本0.4.1.7-chs-alpha1.4.0

第九个成就加点需要解锁【Walk Like An Angel】和【Falling, Falling, Falling...】两个成就
在【成就-转化】中，这两个成就分别被翻译为【如天使般降临】【坠落，堕落，直至地狱…】
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/80169082/8d094dab-4b19-477e-8160-8dd005787614)
在【成就加点】的提示中，这两个成就分别被翻译为【像天使一样走路】【堕落，坠落，直达地狱…】
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/80169082/02d24262-be05-4b46-a8d1-346a8fd6ca21)

第一个成就翻译差距较大，第二个成就翻译有细微差别。
在英文0.4.1.7中两处文本一致，皆为【Walk Like An Angel】和【Falling, Falling, Falling...】

同理，第五个成就加点需要解锁【Aquanaut】，【成就-统计】中翻译为【波塞冬】，提示中翻译为【鱼人】

**Comment by Eltirosto** [comment]
已统一，请等待新版本发布
