### ISSUE TITLE
[v0.5.2.8-5.1.0a-0930]·作弊+CSD+SUSATO分支-镜子转换心境报错&洗澡结束的界面角色贴图出现问题

### ISSUE THREAD

**Issue by SevenHDoll** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#433]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

使用贵发布站下载的[v0.5.2.8-5.1.0a-0930]·作弊+CSD+SUSATO分支zip版本，在pc端的firefox浏览器Version 130.0.1 (64-bit)上游玩时
使用妓院镜子进行心境：换换心情出现报错；在后续回到孤儿院房间进行尝试的途中又发现洗澡结束后选择离开/自慰的画面里，左上角主角贴图出现问题，并且自己房间内的镜子使用心境选项也出现报错

### 存档 / 代码

[degrees-of-lewdity-20241004-000751.txt](https://github.com/user-attachments/files/17247018/degrees-of-lewdity-20241004-000751.txt) 
[degrees-of-lewdity-20241003-235758.txt](https://github.com/user-attachments/files/17247035/degrees-of-lewdity-20241003-235758.txt)

### 截图

![image](https://github.com/user-attachments/assets/24d400dc-370f-4def-9574-ec991c936639)
![image](https://github.com/user-attachments/assets/0a4b0d7f-d469-483b-9151-24c104e4b5d0)

### 还有别的吗？

新开的存档，但是继承过旧存档的成就数据

**Comment by omvjro** [comment]
Mod内容，请先向Mod作者反馈。

**Comment by SevenHDoll** [comment]
> 请问发布站是指[Lyra整合](https://dol-lyra.github.io/hub/)吗？该站并非汉化组网站，出现问题的疑似为Mod内容，请先向Mod作者/[整合包仓库](https://github.com/DoL-Lyra/Lyra/issues)反馈。

好的

**Comment by omvjro** [comment]
https://github.com/DoL-Lyra/Lyra/issues/53
