### ISSUE TITLE
使用的版本是0.5.2.8-v2.20.1有没有其他的贴图包我想换一个提速包 这个实在是太难看了

### ISSUE THREAD

**Issue by manbck** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#434]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

为什么导入贴图之后是这样的？感觉很不好看还有没有其他的？

### 存档 / 代码

[存档.txt](https://github.com/user-attachments/files/17295675/default.txt)

### 截图

![Screenshot_2024-10-08-23-36-22-602_com vrelnir dol_debug](https://github.com/user-attachments/assets/3997d39d-d35a-40b7-8efb-d8924002c721)

### 还有别的吗？

如果有其他的贴图的话能不能发出来？

**Comment by manbck** [comment]
没有人回复我没法处理吗？

**Comment by NumberSir** [comment]
？
