### ISSUE TITLE
【v0.5.1.3-1.1.0a-0902】由于安装其他美化服装导致衣柜上装不显示，但无法返回旧存档删除

### ISSUE THREAD

**Issue by tutuzi618** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#435]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

因为我安装了其他美化服饰，但是上次游戏存档坏了，我把游戏重装，导致了那些美化没有了，打开衣橱上装就不显示了，但是我已经保存的存档全部都有这个问题，所以无法回到旧存档删除，想向老师们求一个通过代码一键删除衣柜内全部服饰的办法

### 存档 / 代码

[存档.txt](https://github.com/user-attachments/files/17328047/default.txt)

### 截图

![Screenshot_20241010_185143_com_vrelnir_DegreesOfLewdity_lyra_MainActivity](https://github.com/user-attachments/assets/b57abf72-0517-4c86-8841-9d851547f966)

**Comment by NumberSir** [comment]
在电脑端浏览器中打开游戏载入存档，按 F12 进入开发者模式，在控制台中输：
```javascript
for (let key in V.wardrobe) {
    if (key === "space") continue;
    V.wardrobe[key] = V.wardrobe[key].filter((elem) => {
        return elem.variable !== 'naked';
    })
}
```
并回车，关闭衣柜再打开就好了。

**Comment by NumberSir** [comment]
[degrees-of-lewdity-撅撅之王-20241012-010455.txt](https://github.com/user-attachments/files/17345615/degrees-of-lewdity-.-20241012-010455.txt)
修改后的存档
