### ISSUE TITLE
v0.5.2.8-chs-5.1.0a 新版本神殿入会时，角色性别器官文本错误

### ISSUE THREAD

**Issue by Wingcrae** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#436]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 说说你看到的汉化文本内容？

[degrees-of-lewdity-20241012-023441.zip](https://github.com/user-attachments/files/17346314/degrees-of-lewdity-20241012-023441.zip)
![批注 2024-10-12 023427](https://github.com/user-attachments/assets/dac811dd-6abd-48e8-b5be-a9deeac03768)
角色性别为男，入会时贞洁检查时，文本是女性器官文本

**Comment by omvjro** [comment]
已修改，谢谢反馈。
