### ISSUE TITLE
[v0.5.2.8-5.1.0a-0930] 作弊菜单翻译问题

### ISSUE THREAD

**Issue by Zed660033** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#438]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 说说你看到的汉化文本内容？

1.在 外观- 液体 中现翻译“史莱姆”应修改为“黏液”
![5e12af17bca924d61b0e24649f06bce](https://github.com/user-attachments/assets/e036215f-eb16-4357-b79e-276e86bbbb73)

2.在解锁狼群恋爱对象后，下方的等级/地位未翻译
![efbcf70aa7897d102e780e9dbd18d24](https://github.com/user-attachments/assets/27468d34-d991-48f2-83f4-48cf91cd2d2a)

**Comment by omvjro** [comment]
谢谢反馈，已修改。
