### ISSUE TITLE
悉尼sex报错

### ISSUE THREAD

**Issue by slvai13** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#44]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

堕落悉尼取下一半贞操带或者没取下贞操带的状态下，pc在神庙0721加入触发sex场景或商场购买泳衣pc选择靠近悉尼触发sex场景有概率报错，报错显示
0.4.1.7-chs-alpha1.4.1 Error (:: Sydney Temple Sex): <<actionsman>>: cannot execute widget: 0.4.1.7-chs-alpha1.4.1 Error (:: Sydney Temple Sex): <<generateActionsMan>>: cannot execute widget: 0.4.1.7-chs-alpha1.4.1 Error (:: Sydney Temple Sex): <<feetActionInit>>: cannot execute widget: 0.4.1.7-chs-alpha1.4.1 Error (:: Sydney Temple Sex): <<feetActions>>: cannot execute widget: 0.4.1.7-chs-alpha1.4.1 Error (:: Sydney Temple Sex): <<feetgrabnew>>: cannot execute widget: 0.4.1.7-chs-alpha1.4.1 Error (:: Sydney Temple Sex): <<set>>: bad evaluation: Unexpected identifier 'replace'
测试版本为alpha1.4.1 版本，如果切换到alpha1.3.0版本错误消失,报错不是百分百触发，新建存档后能重现bug
在做完悉尼事件的毕业存档测试几次好像没有触发这个bug？

### 存档 / 代码

[存档码.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12582904/default.txt)
复现bug存档
[存档2.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12582924/2.txt)
原存档

### 截图

![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/144761812/0f18ba0b-06ef-4636-ae85-7ad1a54ffa33)
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/144761812/0809f862-c566-4127-b9f6-693eed3c875c)

**Comment by Eltirosto** [comment]
已修复，请等待新版本发布
