### ISSUE TITLE
v0.5.2.8-chs-5.1.0a 蛞蝓事件翻译润色问题

### ISSUE THREAD

**Issue by Moliyi** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#440]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 说说你看到的汉化文本内容？

翻译有些问题：蛞蝓的触手撕扯着你的赤裸，想要进到你的娇嫩的阴道下方。 它受伤了，但还是继续对抗材料。
![d4fc02964069a04c319c10b7b6f6e536](https://github.com/user-attachments/assets/7b655ce8-f73d-4792-a4b4-36d14e38d29f)

**Comment by omvjro** [comment]
请问是否安装过添加服装的Mod？这可能是装过Mod没删干净导致的。

**Comment by NumberSir** [comment]
原文是
`
The <CREATURES> tears at your <GENITALS>, trying to get to your <BODYPART> beneath. It hurts itself against the material.
`
- `<GENETALS>`有时是贞操带，未穿戴贞操带时为`“赤裸”(naked)`，不便修改。
- 后一句“对抗材料”原文如此，暂未想到有更好的翻译内容。
