### ISSUE TITLE
0.5.2.8-chs-5.1.0a 译名导致陷害颈手枷事件结束判定出错问题

### ISSUE THREAD

**Issue by ReyADis** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#441]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

送惠特尼至颈手枷后$pillory.tenant.special.name在翻译后改为“惠特尼”而非“Whitney”使得解除服刑时的判定后C.npc.Whitney.state未能由“pillory”返回“active”，将导致之后惠特尼缺席绝大多数日常活动的问题，包括Leighton因翻译为“礼顿”也会同样出错，导致解救文本变为一般路人对话和好感度不会增加，截图为名字不同导致判定错误的结果区别

### 存档 / 代码

[惠特尼.zip](https://github.com/user-attachments/files/17529332/default.zip)

### 截图

![QQ20241026-145659](https://github.com/user-attachments/assets/50e47696-b9cf-48e8-8ffb-af9e959330c6)
![QQ20241026-145745](https://github.com/user-attachments/assets/8f972a6a-16be-486a-8c5e-9abd306edc92)

**Comment by omvjro** [comment]
已修改，谢谢反馈！
