### ISSUE TITLE
请问为什么之前还是汉化的网页突然变成纯英了？

### ISSUE THREAD

**Issue by MillianaEP** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#442]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这既不是对游戏报错的反馈，也不是对汉化文本改进的建议

### 说说你遇到的问题？

是这样的，昨天下午刚进行了网页版游玩，但是当天晚上回去到现在汉化版就消失了，不知道如何复原
同时也想询问怎么才能在ios系统的平板上下载游戏，尝试了很多最后保存下的文件不知道怎么打开

**Comment by MillianaEP** [comment]
稍微补充一下这样——-我本人是留学生 目前在加拿大 这个会有影响吗

**Comment by NumberSir** [comment]
点左下角模组管理器看有没有开安全模式，开的话关掉，刷新页面
