### ISSUE TITLE
v0.5.2.8-chs-5.2.0a 有未翻译的文字

### ISSUE THREAD

**Issue by Moliyi** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#443]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 说说你看到的汉化文本内容？

冬天跳舞跳大了，晕过去被哈珀捡到，这一段汉化有没翻译的文字
![f8475335f894cd7d6bf0f4ee1fb31bef](https://github.com/user-attachments/assets/8384b5fb-fd61-4668-9fad-b98f6583143d)

**Comment by omvjro** [comment]
已修改，谢谢反馈。
