### ISSUE TITLE
【DoL-0.5.2.8-Lyra-5.2.0a】存档加载时人物显示及特徵报错

### ISSUE THREAD

**Issue by AnnAnn1017** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#446]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 问题描述

![報錯](https://github.com/user-attachments/assets/3973b660-cc5d-4602-88a1-89313c97ea8e)
大佬们好！
如图所示，我目前使用家用电脑，在 Microsoft Edge 浏览器（HTML 形式）上游玩该游戏。

但是，当我尝试切换到其他美化版本、加载存档加载到原版，或者更换设备游玩时，
发现在加载存档后，人物显示及特征部分会出现报错。
参考之前 Issue 的问答内容，我怀疑可能是由于 MOD 冲突导致的。

我已经通过 DevTools 检查过 NPC 的相关部分，但似乎问题并不是由 NPC 引起的。

值得注意的是，在相同的 MOD 环境下，
早期的某些存档却可以正常加载并不会报错。
因此我想请教，这个问题可能的根源是什么？是否有解决方法或修复建议呢？

非常感谢大佬们的帮助！如有需要，我可以提供更多相关信息。

以下是我当前加载的 MOD 列表：
![MOD](https://github.com/user-attachments/assets/0068be3b-1e70-42d9-947f-6df8a5f3b1f4)

### 存档 / 代码

有报错问题的存档如下：
[degrees-of-lewdity-New-20241123-184220.txt](https://github.com/user-attachments/files/17879403/degrees-of-lewdity-New-20241123-184220.txt)

使用一样的MOD游玩，却没有报错问题的存档如下：
[（沒問題）degrees-of-lewdity-New-20241121-010308 .txt](https://github.com/user-attachments/files/17879406/degrees-of-lewdity-New-20241121-010308.txt)

### 截图

![報錯截圖](https://github.com/user-attachments/assets/34afba09-f99f-4a0f-b9ed-c92f71ae938b)

### 还有别的吗？

我发现我的HTML端Mod管理器版本为 v2.26.2
但是目前我有尝试加载并出现报错的网页版
Mod管理器版本为 v2.26.1

不知道跟这个是否有关係呢?
（感觉机会应该不大？）

**Comment by omvjro** [comment]
请优先向Lyra（https://github.com/DoL-Lyra/Lyra/issues）及Mod制作者反馈。

**Comment by mirrormirroronwall** [comment]
晒痕报错，可能是衣服mod导致。在选项-性能中关闭服装晒痕，或使用美白言灵

**Comment by AnnAnn1017** [comment]
> 晒痕报错，可能是衣服mod导致。在选项-性能中关闭服装晒痕，或使用美白言灵

关闭晒痕后可正常运行，谢谢您们的回复！
