### ISSUE TITLE
v0.5.2.8-chs-5.2.0a 汉化翻译错误

### ISSUE THREAD

**Issue by bwhmtyp** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#447]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议
- [X] 我在标题开头写明了当前使用的版本号，比如 [0.4.2.7-chs-alpha4.0.0]

### 说说你看到的汉化文本内容？

在艾利克斯农场第一次被攻击后，与艾利克斯对话翻译错误，说以→所以
[degrees-of-lewdity-1-20241127-173242.txt](https://github.com/user-attachments/files/17932219/degrees-of-lewdity-1-20241127-173242.txt)

![wechat_2024-11-27_173255_867](https://github.com/user-attachments/assets/dfbee350-57c9-4cfa-934b-34d2b86a2d73)

**Comment by omvjro** [comment]
已修改，谢谢反馈。
