### ISSUE TITLE
i18n.json是怎么提取出来的呢？

### ISSUE THREAD

**Issue by newbie-forever** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#449]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这既不是对游戏报错的反馈，也不是对汉化文本改进的建议

### 说说你遇到的问题？

我想把汉化导入DoLP，但是由于位置没有对齐所以很多本来翻译过的地方都是英文状态，想着自己对齐一下

**Comment by omvjro** [comment]
可以先参考：https://github.com/NumberSir/vrelnir_localization
具体可以问一问@NumberSir

**Comment by NumberSir** [comment]
> 可以先参考：https://github.com/NumberSir/vrelnir_localization 具体可以问一问@NumberSir

核心代码在 `src/project_dol.py` 和 `src/parse_text.py` 里。
