### ISSUE TITLE
【BUG】被骚扰事件报错【已定位第98401行】

### ISSUE THREAD

**Issue by trlaitioer** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#46]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

神殿宿舍-打扫卫生-答应并去寻找卷轴
0.4.1.7-chs-alpha1.4.1版本

### 存档 / 代码

[degrees-of-lewdity-20230914-201819.zip](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12608711/degrees-of-lewdity-20230914-201819.zip)

### 截图

![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/80169082/b90dd261-6e39-479a-8e09-c877e1765703)

### 还有别的吗？

用控制台修改过一次money，应该不影响

**Comment by trlaitioer** [comment]
圣诞舞台剧结束后和悉尼调情，看样子触发的应该是同一类BUG
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/80169082/40c2c8aa-e96e-4c14-a8de-ff34fbe544d7)
[degrees-of-lewdity-20230915-111155.zip](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12615226/degrees-of-lewdity-20230915-111155.zip)

**Comment by trlaitioer** [comment]
控制台看了下报错，应该是第98401行
`&lt;&lt;set _feetaction[&quot;把你的脚抵在&quot; + $NPCList[$feettarget].pronouns.his + &quot;的&quot; + $NPCList[$feettarget].chastity.vagina.replace(&quot;chastity&quot;,&quot;贞操&quot;).replace(&quot;cage&quot;,&quot;笼&quot;).replace(&quot;belt&quot;,&quot;带&quot;).replace(&quot;anal shield&quot;,&quot;护肛板&quot;)replace(&quot; &quot;,&quot;&quot;) + &quot;上&quot;] to &quot;vaginagrab&quot;&gt;&gt;`
护肛板后面的replace前缺少一个.
可以搜索 )replace( 来定位

**Comment by Eltirosto** [comment]
已修复，请等待新版本发布。
