### ISSUE TITLE
apk版本在横向玩时，侧边栏弹出后会遮挡主页面

### ISSUE THREAD

**Issue by lzl1lzl** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#47]
### 说说你遇到的问题？

希望侧边栏弹出后，主页面的文字可以重新排班，防止被侧边栏遮挡。
就像下面浏览器中这样。
![Screenshot_20230914_201630](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/145020981/ce4089a9-d2ad-4f94-8bf9-c837d85053fe)

**Comment by Eltirosto** [comment]
非汉化版问题。

而且虽然官方文档中提供了自行构建 apk 的建议，但 apk 版本非官方计划支持的版本，关于 apk 版存在的非游戏内容问题，甚至 apk 版存在的一切问题短期内都可能不会有任何修复的可能。
