### ISSUE TITLE
有关身体涂鸦无法正确调用text文件中的图片相关问题

### ISSUE THREAD

**Issue by aliya2333** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#48]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议

### 说说你看到的汉化文本内容？

分别使用了原版0.4.1.7和alpha1.4.1汉化版本进行对比，原版中的一部分身体涂鸦在bodywriting中的text里有单独的文件夹，写在身上时会和默认的词条有所区别，但在汉化版本会变为默认的text而无法显示其独有内容，请问是否有后续进行修正的计划？
![IMG_20230915_005903](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/144807127/548d8ffa-5936-4a05-80cc-558fd953f49e)
![IMG_20230915_010125](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/144807127/3a763e1d-809e-47e8-bb82-289054fb3831)

**Comment by Khaos423** [comment]
是如何放得这么大的

**Comment by Eleus7** [comment]
试了一下，浏览器页面缩放直接放大即可

**Comment by Khaos423** [comment]
放大我也做不到题主这么清晰

**Comment by NumberSir** [comment]
很久之前已修。
