### ISSUE TITLE
【Bug】神殿宿舍打扫被骚扰时报错

### ISSUE THREAD

**Issue by TheLostAlice** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#49]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在神殿宿舍打扫时被骚扰时发生了报错，不知道什么原因导致的所以不知道怎么复现，目前只知道出错前经历过血月幽灵事件以及幽灵回忆时间（都不是第一次经历），以及出错前回溯功能出过红色感叹号（当时重启了下就没事了，所以没截图）

### 存档 / 代码

[DolBug.zip](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12617544/DolBug.zip)

### 截图

![屏幕截图 2023-09-15 164355](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/145109849/2f066c28-08e7-409f-b68e-83303b8097d5)

**Comment by trlaitioer** [comment]
和 #46 一样

**Comment by Eltirosto** [comment]
已修复，请等待新版本发布
