### ISSUE TITLE
游戏刚开局部分未汉化内容

### ISSUE THREAD

**Issue by fengqilantian** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#5]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议

### 说说你看到的汉化文本内容？

如图，刚开始进入游戏，左侧人物描述有英文，右侧选项2有个Pyjames英文单词
![QQ图片20230821213056](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/44064179/a29c8858-ff00-4236-98be-978b887c516e)

**Comment by NumberSir** [comment]
已修复，请等待新版本发布
