### ISSUE TITLE
和悉尼的自愿遭遇也会触发npc通用对话

### ISSUE THREAD

**Issue by aliya2333** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#50]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

测试版本为汉化alpha1.5.0和alpha1.3.0
呃可能是之前汇报bug时文字描述的部分被漏看了，因为我只发了和罗宾的图，但是和悉尼的自愿遭遇也会同样触发npc的通用对话，仍然是退回到1.3.0恢复正常。且不确定是否还有其他角色也存在此问题……这个bug是在1.4.0版本开始出现的，可能要麻烦汉化组检查了

### 存档 / 代码

[save.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12622060/save.txt)

### 截图

![IMG_20230916_010208](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/144807127/e3b7bdcb-8f9b-45c2-b49f-be57068bd92e)
![IMG_20230916_010225](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/144807127/7810fc07-4572-4217-a703-a718bb780180)
![IMG_20230916_010303](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/144807127/fb271b85-9f30-46fa-86fe-caf949c73c9c)

**Comment by NumberSir** [comment]
已修复，请等待新版本发布。

触发bug的原因是汉化过程中将输出的空格 `text_output = " "` 改为了空字符串 `text_output = ""`，但源码中直接用 `if text_output` 判断是否调用路人逻辑。
