### ISSUE TITLE
孤儿院浴室用榨乳器榨乳报错

### ISSUE THREAD

**Issue by TheLostAlice** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#51]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

虽然报了错但还是能继续玩下去。

### 存档 / 代码

[Dol1.5.0Bug.zip](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12641029/Dol1.5.0Bug.zip)

### 截图

![屏幕截图 2023-09-16 233414](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/145109849/afa944d7-c3e0-4ed5-ab8f-424f3f52bf35)

**Comment by TheLostAlice** [comment]
现在已经变成了只要用榨乳器就报错，但不影响用。

**Comment by Khaos423** [comment]
实际上是拿起无色性玩具就报错

**Comment by Eltirosto** [comment]
已修复，请等待新版本发布
