### ISSUE TITLE
在舞蹈室更换舞蹈服报错

### ISSUE THREAD

**Issue by ultrakgh** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#52]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在舞蹈室的更衣室更换舞蹈服后会报此错误，版本为dol-0.4.1.7-chs-alpha1.5.0，没有打过mod或做任何修改，在alpha 1.4.1版载入存档没有复现这问题。

### 存档 / 代码

[degrees-of-lewdity-20230917-021056.zip](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12641412/degrees-of-lewdity-20230917-021056.zip)

### 截图

![bug](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/145224631/188e2ee5-748d-4307-b3e6-cd74a1a38cde)

**Comment by knepts** [comment]
我也出现这个问题了，虽然不影响正常使用，但不知道为什么报错。

**Comment by Eltirosto** [comment]
已修复，请等待新版本发布
