### ISSUE TITLE
圣诞表演排练剧情出现文本错误

### ISSUE THREAD

**Issue by TheLostAlice** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#54]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如图所示，这里的英文处本应该是凯拉尔。

### 存档 / 代码

[Desktop.zip](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12643734/Desktop.zip)

### 截图

![屏幕截图 2023-09-18 051902](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/145109849/ff6e449d-d42b-4fd8-8dbc-119889da39ae)

**Comment by Eltirosto** [comment]
已修复，请等待新版本发布。
