### ISSUE TITLE
咖啡館打工文本错误

### ISSUE THREAD

**Issue by ducklord50** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#55]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如图所示

### 存档 / 代码

[degrees-of-lewdity-lv1-20230917-221222.zip](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12644801/degrees-of-lewdity-lv1-20230917-221222.zip)

### 截图

![Screenshot 2023-09-17 221004](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/145316556/bd97bcd9-0277-487d-addd-ff7ca990da70)

**Comment by Eltirosto** [comment]
已修复，请等待新版本发布。
