### ISSUE TITLE
森林选项报错

### ISSUE THREAD

**Issue by knepts** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#56]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

森林选项有概率出现报错

### 存档 / 代码

[save.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12645174/save.txt)

### 截图

![Screenshot_2023-09-18-14-25-23-819_com vrelnir DegreesOfLewdityWE](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/142622380/be74c176-5767-47fe-a827-a4f7615eb740)

### 还有别的吗？

1.5.1进行森林相关选项出现

**Comment by Eltirosto** [comment]
已修复，请等待新版本发布。

**Comment by Eltirosto** [comment]
[@issue/55][issue55]
[issue55]: https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/issues/55
