### ISSUE TITLE
妓院富人区工作战斗页面报错

### ISSUE THREAD

**Issue by whangb11** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#57]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

妓院富人区工作，进入战斗页面几回合后报错

### 存档 / 代码

[savfile.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12651844/savfile.txt)

### 截图

![Screenshot_20230919-013721~2](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/71579712/3cd5a5ca-deaa-46f3-b165-abdf240bb3e5)

**Comment by Eltirosto** [comment]
无法复现，需要更多信息。
