### ISSUE TITLE
在森林最深处探索时报错

### ISSUE THREAD

**Issue by Eleus7** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#59]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题

### 存档 / 代码

[报错.zip](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12671084/default.zip)

### 截图

![(J_FH7C6`ISA@7EKN0_MD)X](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/144487675/2629da5c-1d4d-4ec8-8c26-e00bf1292af6)

**Comment by Eltirosto** [comment]
已修复，同 [@issue/55](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/issues/55)
