### ISSUE TITLE
关于惠特尼周日酒吧拼酒事件中的翻译建议

### ISSUE THREAD

**Issue by Eleus7** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#60]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议

### 说说你看到的汉化文本内容？

在惠特尼酒吧事件中有描写一段，惠特尼叫人去吧台拿了一叠照片过来并与pc各自分享了一份
![5 1D2 BD@}2D5$BJ6$C MED](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/144487675/9dbbf9c4-67dc-4e3d-af66-1049c4e9e88f)

### 有什么好的想法？

原文中的照片是shots，根据事件发生地点在酒吧，以及之后的干杯对话来看，这里的shots指的并不是照片，而是酒吧内可以一口喝完的子弹杯装烈酒
![%TAYB3E0)1}JLN $)) Z5AS](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/144487675/a53fdf72-cbb7-46e7-8e8b-07d127dfed7d)

根据这点，我的朋友对这段进行了重新翻译，希望汉化组可以参考一下

惠特尼向他身边的一个纤瘦男孩耳语。他跌跌撞撞地离开自己的位置并跑向吧台。
你被从后面抓住，拎起来转了一圈。惠特尼就这么将你放回他的腿上，他得意的笑脸映入眼帘。“这次的绝对能干翻你，”他说，“不过你都习惯了。”【原文是fuck you up，似乎是一句双关，努力还原了一下】
那个纤瘦男孩托着一盘子弹杯过来了。惠特尼拿了一杯给你，再拿一杯给自己。“干杯。”【【这是周日酒吧拼酒事件主要让人疑惑的部分。shot确实有照相的意思，但这里应该是指国外特有的高浓度酒用的小型酒杯，国内普遍翻译为子弹杯，在此使用这个译名给汉化组提供参考。】】

**Comment by Eltirosto** [comment]
已改，请等待新版本发布
