### ISSUE TITLE
关于惠特尼周日酒吧拼酒事件中的翻译建议2

### ISSUE THREAD

**Issue by Eleus7** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#61]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议

### 说说你看到的汉化文本内容？

在惠特尼周日酒吧拼酒事件中关于这段姿势描写

![D AH1UG87PV 7AUH}W@ 0N](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/144487675/cda2af90-638b-48ed-8982-111b22bd8a57)

### 有什么好的想法？

![5TJ)WYS${DM{25_ %NKM5@L](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/144487675/34914813-75ee-4991-bc18-3cc0d5824385)

汉化组翻译是没有问题的，但是在姿势描写上我的一位朋友提出了润色建议，希望翻译组可以参考一下

你往下坐，用臀瓣夹住他的龟头并跟上他的动作。
你不太确定他能否隔着自己的运动裤感受到（你的动作）。直到一声呻吟溜出。他赶紧喝了一口酒，但仍吸引了一些旁人的注意。
你用力地挤压他笨重的阴茎，而后从他的腿上滑落下来。让你意外的是，他稳住了你，不过让你和他的腹股沟保持了一段距离。【这段动作实在是挺复杂的，拉着朋友一起研究了一会儿理顺了，再看汉化组的翻译，其实问题也不是很大，】

**Comment by Eltirosto** [comment]
已改，请等待新版本发布。
