### ISSUE TITLE
狀態欄中疼痛與自控消失

### ISSUE THREAD

**Issue by chair4500** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#62]
### 说说你遇到的问题？

版本號Degrees of Lewdity 0.4.1.7-chs-alpha1.5.1

我的存檔中的狀態欄**沒有自控與疼痛兩樣數值**
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/145570559/97cc2627-e817-4013-a9ef-ca3ff4baed48)
且**在非自願遭遇中沒有顯示任何紅色的反抗選項**，除了挑釁和要求停下，因為要求停下總是有用我就一直沒注意，今天才意識到自己打不了人（

在墮落悉尼的祈禱室事件中第二次以上的遭遇選擇反抗時
也沒有紅色選項出現
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/145570559/2c6f362b-5f52-4bc9-b803-ff86a9325803)

這時候選擇「要求停下」會讓悉尼的動作停止、戰鬥動畫中的剪影也會消失，就像普通非自願遭遇中對方聽話停下一樣
pc還是可以行動和高潮，**但遭遇卡在無法結束的狀態**

**Comment by chair4500** [comment]
同個存檔拿去英文版最新版也有一樣

> ### 说说你遇到的问题？
> 版本號Degrees of Lewdity 0.4.1.7-chs-alpha1.5.1
> 
> 我的存檔中的狀態欄**沒有自控與疼痛兩樣數值** ![image](https://user-images.githubusercontent.com/145570559/269297667-97cc2627-e817-4013-a9ef-ca3ff4baed48.png) 且**在非自願遭遇中沒有顯示任何紅色的反抗選項**，除了挑釁和要求停下，因為要求停下總是有用我就一直沒注意，今天才意識到自己打不了人（
> 
> 在墮落悉尼的祈禱室事件中第二次以上的遭遇選擇反抗時 也沒有紅色選項出現 ![image](https://user-images.githubusercontent.com/145570559/269298161-2c6f362b-5f52-4bc9-b803-ff86a9325803.png)
> 
> 這時候選擇「要求停下」會讓悉尼的動作停止、戰鬥動畫中的剪影也會消失，就像普通非自願遭遇中對方聽話停下一樣 pc還是可以行動和高潮，**但遭遇卡在無法結束的狀態**

**Comment by chair4500** [comment]
沒事了，好像是因為我開到簡單模式，請幫我刪除本次回報，謝謝，抱歉打擾了

**Comment by HSSkyBoy** [comment]
不倡議刪除issues
且或許有跟你一樣的小笨蛋看到後可能會反應過來
