### ISSUE TITLE
森林商店处快速探索报错

### ISSUE THREAD

**Issue by search7** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#63]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

森林商店处快速探索报错

### 存档 / 代码

[dol报错.zip](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12674262/dol.zip)

### 截图

<img width="1920" alt="Snipaste_2023-09-20_22-20-20" src="https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/57584557/a708317f-7652-4f1d-a9a8-d39f91d95fce">

### 还有别的吗？

森林商店处快速探索*N小概率触发

**Comment by Eltirosto** [comment]
已改，同 [@issue/55](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/issues/55)
