### ISSUE TITLE
农场帮艾利克斯收快递 文本修正建议

### ISSUE THREAD

**Issue by search7** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#64]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议

### 说说你看到的汉化文本内容？

<img width="1920" alt="Snipaste_2023-09-20_23-24-30" src="https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/57584557/8fc755d3-e888-4034-96a0-166dd1e05612">
<img width="1920" alt="Snipaste_2023-09-20_23-25-40" src="https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/57584557/5bf0d09f-56c4-499e-b1a7-839660c9da1d">

### 有什么好的想法？

收快递时打开的第二个是“盒子”而非“房间”

**Comment by search7** [comment]
[degrees-of-lewdity-S-20230920-233537.zip](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12674949/degrees-of-lewdity-S-20230920-233537.zip)
附存档

**Comment by Eltirosto** [comment]
已修改，请等待新版本发布。
