### ISSUE TITLE
生下金属触手后，点击查看笔记本报错

### ISSUE THREAD

**Issue by 46ZSLSLO6** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#65]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

生下金属触手后，点击查看笔记本报错，在生下金属触手前没有出现报错问题。

### 存档 / 代码

[degrees-of-lewdity-20230921-163355.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12682276/degrees-of-lewdity-20230921-163355.txt)

### 截图

![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/89512918/9e25384b-5f91-451b-a992-a1a66f47113e)
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/89512918/8fd38a54-cf14-4d36-aaba-9dbd78e96ecb)

**Comment by Eltirosto** [comment]
已修复，请等待新版本发布。
