### ISSUE TITLE
文本错误：荒野搜索

### ISSUE THREAD

**Issue by 46ZSLSLO6** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#66]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议

### 说说你看到的汉化文本内容？

![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/89512918/1093a210-fa09-4b9b-9a0f-522df6b09dbf)

### 有什么好的想法？

直到他f离你很远，你才会感到舒适。
该行中英文字符“f”未删除。

### 其他内容

我不清楚最新版本是否修正了该问题。

**Comment by Eltirosto** [comment]
已修改，请等待新版本发布。
