### ISSUE TITLE
未翻译文本：在公园穿高跟鞋锻炼

### ISSUE THREAD

**Issue by 46ZSLSLO6** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#68]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议

### 说说你看到的汉化文本内容？

![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/89512918/c4f8bcfd-f195-47e3-a5d1-ae2523028f32)
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/89512918/33a372fb-70fe-4574-be3d-f6e044c20106)
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/89512918/ff71ad5b-0403-4749-bb2d-8220ee4d73d7)
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/89512918/0b0f8e53-41b9-4abf-b0cc-692bb2d8e23a)
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/89512918/5fd53496-a986-45bb-b982-1c3115fde271)

### 有什么好的想法？

在公园穿高跟鞋锻炼显示的部分文本未翻译。

### 其他内容

不确定是否涵盖了所有可能出现的文本。

**Comment by Eltirosto** [comment]
已修，请等待新版本发布
