### ISSUE TITLE
未翻译文本：和狼崽互动

### ISSUE THREAD

**Issue by 46ZSLSLO6** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#69]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议

### 说说你看到的汉化文本内容？

![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/89512918/ad084f1e-bdd2-427c-aa5b-2682db9dc41d)
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/89512918/4998c8ad-3a67-4b90-807a-a0474599a41a)

**Comment by Eltirosto** [comment]
已修，请等待新版本发布
