### ISSUE TITLE
两个文本错译

### ISSUE THREAD

**Issue by MC-Qim** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#7]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议

### 说说你看到的汉化文本内容？

-  根据原版内容，pc黎明在森林湖检查倒影时，文本不应为"淹没在鲜血中"，黄昏时"完美无瑕，带着黄昏的琥珀余晖"中不存在"完美无瑕"

![1](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/142801523/d541fb95-54b4-4261-87c6-248694292647)
![2](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/142801523/7ab197e7-308b-4896-9bfc-f1a22baf5dd7)

- 惠特尼的寄生虫剧情有一个错字

![3](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/142801523/038d3125-9675-45f4-80fd-c5176362a71d)

### 有什么好的想法？

"淹没在鲜血中"，可以改为"晨曦的余辉给你披上了一层琥珀色的光环"
"完美无瑕，带着黄昏的琥珀余晖"可以改为"夕阳的余辉给你披上了一层琥珀色的光环"

**Comment by NumberSir** [comment]
已修改，请等待新版本发布
