### ISSUE TITLE
[chs1.2.5]全声望满之后的地下特殊称号The Boy/Girl应当和The Orphan一样加上传说两字

### ISSUE THREAD

**Issue by Kaitwolf** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#70]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议

### 说说你看到的汉化文本内容？

![)BPP5U2KH77LXBGQ4S1QA2Q](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/89610603/2321ca18-e857-4868-888d-85938c341612)

### 有什么好的想法？

这玩意也算是特殊称号了，怎么想也不该是翻译成普通女孩/男孩吧

**Comment by Eltirosto** [comment]
已修改，请等待新版本发布。
以后请使用最新版反馈问题
