### ISSUE TITLE
未翻译文本：摄影工作室做模特

### ISSUE THREAD

**Issue by 46ZSLSLO6** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#71]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议

### 说说你看到的汉化文本内容？

![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/89512918/f8862d5b-b34d-4ebe-8ba7-67913e805c2a)

**Comment by Eltirosto** [comment]
已修，请等待新版本发布
