### ISSUE TITLE
翻译改进：二十一点作弊

### ISSUE THREAD

**Issue by 46ZSLSLO6** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#73]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议

### 说说你看到的汉化文本内容？

![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/89512918/f2927e48-1978-4d52-bfb7-2f9c03d2b1d8)
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/89512918/47a83e87-541a-4282-ae05-e3604d90ad11)
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/89512918/1a3a828b-4ed0-4184-aa05-3efbdf7ca672)

### 有什么好的想法？

我不太确定图1中这个“你可以从牌堆的顶部识别出3日 卡片。”具体指的是什么，我没有读过原文，我推测是“你可以识别出牌堆顶部的三张牌。”或者“你可以识别出牌堆顶部的第三张牌。”

图2，图3中“卡组”应该替换成“牌”。

**Comment by Eltirosto** [comment]
已改，请等待新版本发布
