### ISSUE TITLE
数学课上与惠特尼调情翻译错误 意识 写成了 意思

### ISSUE THREAD

**Issue by Imokodesu** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#74]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议

### 说说你看到的汉化文本内容？

![GCVH 3UMDK~~7L0U0 7{0KI](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/145891190/aff4fe7a-b2aa-4977-8f70-9c37c8ce3ac1)
[degrees-of-lewdity-002-20230925-130853.zip](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12711315/degrees-of-lewdity-002-20230925-130853.zip)

**Comment by Eltirosto** [comment]
已修，请等待新版本发布
