### ISSUE TITLE
悉尼无法破处的问题（前后）

### ISSUE THREAD

**Issue by 0423allenallen** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#75]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

无论多少次跟悉尼do（不是在祈祷室），最后悉尼总是会说出第一次被破的那一句"我们有麻烦了。。。。太粗心了。。。"(无论你透了她的前面还是后面)。之后她的第一次又原封不动的回去了相当于是我怎么都破不了悉尼第一次了，这发生在我和悉尼被发现，在祈祷室被抽打后重新获得了誓言。

### 存档 / 代码

[新建 文本文档.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12723325/default.txt)

### 截图

[Desktop.zip](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12723293/Desktop.zip)

### 还有别的吗？

任何情况下和悉尼do后，悉尼第一次依旧留着

**Comment by Eltirosto** [comment]
这是正常游戏流程，不是bug

**Comment by Khaos423** [comment]
准确说这句话是悉尼结束后说的，并非破处所说的话。看统计就知道已经夺取与否。
