### ISSUE TITLE
存档消失且无法导入1.6.0版存档

### ISSUE THREAD

**Issue by MarieilS** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#76]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如标题，汉化1.7.0更新后，打开网页时旧存档消失，点击导入存档则显示“ALERT：Save is from the wrong game.Aborting.”无法正确导入。
打开1.6.0版存档还在，且导入存档的操作也无问题。

### 存档 / 代码

[degrees-of-lewdity-20230928-231010.save.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12765905/degrees-of-lewdity-20230928-231010.save.txt)

### 截图

![QQ截图20230929212347](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/146449365/1d77978a-54f9-4b36-9d4a-772bd59bb8b0)
![QQ截图20230929212358](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/146449365/b0a25813-257f-449a-9d9e-e36cd4900dee)

**Comment by Eltirosto** [comment]
已修复，请更新 `alpha1.7.1`
