### ISSUE TITLE
科学课性骚扰事件报错

### ISSUE THREAD

**Issue by Eleus7** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#77]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如图

### 存档 / 代码

[科学课性骚扰事件报错.zip](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12768930/default.zip)

### 截图

![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/144487675/32103853-078f-4b7b-8b8b-6981db768b4f)

**Comment by trlaitioer** [comment]
第429909行，将Sirris前后的引号 `‘` 替换成 `&quot;`
不是孤例，更多的等修复吧
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/80169082/eef44a59-a916-45fe-9ed2-4abdaadc060f)

**Comment by NumberSir** [comment]
已修复，请等待新版本发布
