### ISSUE TITLE
在卧室照镜子并检查皮肤时报错

### ISSUE THREAD

**Issue by Eleus7** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#78]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如图

### 存档 / 代码

[在卧室检查皮肤时报错.zip](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12769311/default.zip)

### 截图

![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/144487675/146c82e7-ae6c-422c-bff5-5ad4dcf9ff60)

**Comment by trlaitioer** [comment]
第187833行，将 **恋爱对象** 改成 **Love Interests** 即可消除报错

**Comment by NumberSir** [comment]
同 [@issue/77](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/issues/77)
