### ISSUE TITLE
如何讓npc生小孩

### ISSUE THREAD

**Issue by WhiteCloud0106** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#79]
### 说说你遇到的问题？

我剛玩這遊戲不久，選了男性做主角，有讓凱拉爾、羅賓等人懷孕，但他們好像不會有其他反應？
我調過npc的懷孕時間至最短，並且也等待了一整個孕期，統計裡顯示“任何時間”，但是也已經過了好幾天了。
想問問我該怎麼做？

**Comment by NumberSir** [comment]
你好，非汉化版相关问题请前往 [英文维基](https://degreesoflewdity.miraheze.org/wiki/Pregnancy) 搜索，或在 [中文维基](https://degreesoflewditycn.miraheze.org/wiki/) 上查找有没有对应的汉化内容。
