### ISSUE TITLE
如何裝載模組？

### ISSUE THREAD

**Issue by HSSkyBoy** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#80]
### 说说你遇到的问题？

如何在安卓簡中版(APK)中添加模組？
雖然原版可玩性已經很好

**Comment by trlaitioer** [comment]
https://github.com/sakarie9/DOL-CHS-MODS
请

**Comment by HSSkyBoy** [comment]
非常好模組，愛來自國家中心(愛心)

**Comment by NumberSir** [comment]
> ### 说说你遇到的问题？
> 如何在安卓簡中版(APK)中添加模組？ 雖然原版可玩性已經很好

由于游戏引擎自身的限制，实现模组加载还有很大的困难。
目前正在开发关于辅助模组编写和模组加载的脚本，感兴趣可以看看：

辅助编写：https://github.com/NumberSir/DOL-Mod-Created-Helper
模组加载：https://github.com/Lyoko-Jeremie/sugarcube-2-ModLoader

可以用这个加载器加载的模组有格式要求

---

如果对其它独立模组感兴趣可以看：https://dolmods.net/ 不过尚无汉化版

---

如果想安装修改/添加游戏内贴图的美化模组，只需下载贴图文件替换原有的 `img` 文件夹即可

---

关于修改 `apk` 文件，可以使用如 `MTool (MT管理器)` 一类的 apk 编辑/签名工具打开 apk 然后替换文件 (apk 本质上就是个特殊的压缩包)

**Comment by HSSkyBoy** [comment]
（我是專門破解安卓遊戲的）
非常感謝如此詳細的說明，我在我要去試試了:)
