### ISSUE TITLE
侧边栏时间出示过前

### ISSUE THREAD

**Issue by HSSkyBoy** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#81]
### 说说你遇到的问题？

https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/122550437/afbae437-0592-4646-84a2-7083e977f4a6

時間應在狀態欄收回去後再顯現
否則很奇怪，像很卡頓

**Comment by NumberSir** [comment]
非汉化版问题，是原游戏问题，已向作者反馈。
