### ISSUE TITLE
历史考试时温特名字没翻译

### ISSUE THREAD

**Issue by HSSkyBoy** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#83]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议

### 说说你看到的汉化文本内容？

![Screenshot_20230930_234605_com vrelnir DegreesOfLewdityWE_edit_158087981705562](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/122550437/c4bf8ffe-4e15-4e73-b2ab-e47ad22b3184)

[存檔碼.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12775068/default.txt)

### 有什么好的想法？

Winter's
温特的

**Comment by NumberSir** [comment]
已翻译，请等待新版本发布
