### ISSUE TITLE
APK中文缺漏

### ISSUE THREAD

**Issue by HSSkyBoy** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#84]
### 说说你遇到的问题？

正式版打包出的apk的resources.arsc中，有一句“Press BACK again to exit”，也对应游戏中的双击返回，但为什么这句话并没有翻译？安卓版本中，只要单击右键就会弹出这个toast

**Comment by NumberSir** [comment]
请发截图 / 存档

**Comment by NumberSir** [comment]
另外 apk 中的“右键”指的是？双击返回又指的是？

**Comment by HSSkyBoy** [comment]
恕我並未詳細說明
“右鍵”是指手機的返回鍵
“雙擊返回”就是“Press BACK again to exit”的大致意思
這句話只要在APK(安卓)版本的任意界面，單擊右鍵就會出現
這句話是在打包出的apk中的resources.arsc出現的

**Comment by NumberSir** [comment]
这个并非游戏内容，是打包时使用的 apk 框架自带的。只有用虚拟按键（右键）返回时会出现，用手势返回时不会出现。

**Comment by NumberSir** [comment]
已汉化，将适配 `dol-0.4.2.7-chs-alpha4.0.0` 及以后的版本
