### ISSUE TITLE
属性中狗应为狼

### ISSUE THREAD

**Issue by HSSkyBoy** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#85]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议

### 说说你看到的汉化文本内容？

![Screenshot_20231001_101916_com vrelnir DegreesOfLewdityWE chsmods](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/122550437/62e517fe-5c66-4f6b-ab51-40047d3b0bd4)

### 有什么好的想法？

属性中是狗，但我此时是狼化，这是否有误

**Comment by NumberSir** [comment]
原文如此，不是汉化错误。
