### ISSUE TITLE
帮助主管处的翻译错误

### ISSUE THREAD

**Issue by HSSkyBoy** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#86]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议

### 说说你看到的汉化文本内容？

![Screenshot_20231001_101916_com vrelnir DegreesOfLewdityWE chsmods](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/122550437/a4cc39ba-ee46-4045-b46f-39e016058794)

### 有什么好的想法？

下去应该改为拒绝
虽然我记得以前好像就是拒绝

**Comment by NumberSir** [comment]
发错图了，请修改

**Comment by HSSkyBoy** [comment]
![Screenshot_20231001_110416_com vrelnir DegreesOfLewdityWE chsmods](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/122550437/9e27e5d2-1845-4317-97e8-26a8c51293d0)

竟然發錯圖了:(

**Comment by NumberSir** [comment]
已修改，请等待新版本发布。
