### ISSUE TITLE
1.7.1汉化版翻译问题

### ISSUE THREAD

**Issue by kaze-0** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#87]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

1.7.1汉化版本，在接受查理给的工作后，身上沾有粘液时以猫转化选择“舔舐”选项，出现：
`你擦拭着自己，从你的<< [function]("neck","脖子").replace("tummy","肚子").replace("chest","胸").replace("face","脸").replace("hair","头发").replace("feet","脚")>>`

### 存档 / 代码

无法上传.save文件，改为txt
[degrees-of-lewdity-2nd-20231001-171429.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12776785/degrees-of-lewdity-2nd-20231001-171429.txt)

### 截图

![SXEN2N(}7AO(4AMZP1KZ2LN](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/30644021/cb1fcc7f-d785-4b4a-9a5a-88d79c3156d2)

**Comment by NumberSir** [comment]
已修复，请等待新版本发布
