### ISSUE TITLE
照镜子看皮肤报错

### ISSUE THREAD

**Issue by shanmujiuya** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#88]
### 在提问之前...

- [ ] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [ ] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [ ] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

1.7.0版本时是好使的，更新后报错了，开新档照镜子没问题，旧档不行

### 存档 / 代码

[Uploading Degrees of Lewdity.txt…]()

### 截图

![Screenshot_2023-10-02-13-27-57-52_7772ada461b89c699132e33396e4e395](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/146629759/aa1aaa94-fc35-4876-be1d-37616ab02e9a)

### 还有别的吗？

麻烦了，感谢

**Comment by NumberSir** [comment]
已修复，请等待新版本发布。
