### ISSUE TITLE
理发店约会错误

### ISSUE THREAD

**Issue by qb0071011** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#89]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

和悉尼在购物中约会进理发店后，为他挑发型的部分出错了无法选择。

### 存档 / 代码

[存档码.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12781512/default.txt)

### 截图

![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/146717169/2e62eb70-d59f-4cef-8881-68867620cfb3)

**Comment by NumberSir** [comment]
已修复，请等待新版本发布
