### ISSUE TITLE
环顾博物馆，温特的话没有汉化

### ISSUE THREAD

**Issue by w1847766036** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#9]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议

### 说说你看到的汉化文本内容？

![Screenshot_2023-08-22-18-30-46-31_7772ada461b89c699132e33396e4e395](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/142893991/c8bde3d2-ce93-4ce6-bd0d-acd19ae16ea9)

**Comment by Eltirosto** [comment]
已汉化，请等待新版本发布
