### ISSUE TITLE
汉化1.7.1alpha版本 战斗中图片显示出错

### ISSUE THREAD

**Issue by NormanDSG** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#90]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

汉化1.7.1alpha版本 海滩测量遭遇战中战斗动图出错

### 存档 / 代码

[degrees-of-lewdity-20231002-225158.zip](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12783716/degrees-of-lewdity-20231002-225158.zip)

存档在压缩包内

### 截图

<img width="1277" alt="屏幕截图 2023-10-02 225506" src="https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/143474611/8a095229-7f52-4a0a-9cc6-7f0ac9191abb">

**Comment by NumberSir** [comment]
非汉化版错误，已向作者反馈。
