### ISSUE TITLE
数学考试瑞沃名字未译

### ISSUE THREAD

**Issue by HSSkyBoy** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#91]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议

### 说说你看到的汉化文本内容？

![Screenshot_20231003_113618_com vrelnir DegreesOfLewdityWE chsmods](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/122550437/df66c277-3a2c-4148-bb3a-917db26dce41)

未儲存存檔碼

### 有什么好的想法？

River's
瑞沃的

### 其他内容

前面歷史考試老師名稱也沒翻譯，所以我懷疑語文（英語）和科學可能也沒翻譯

**Comment by NumberSir** [comment]
已汉化，请等待新版本发布

**Comment by NumberSir** [comment]
[@issue/83](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/issues/83)

**Comment by NumberSir** [comment]
> 歷史考試和數學考試有啥關繫😢

没事，就标注一下是同一个原因导致的问题
