### ISSUE TITLE
关于货物售卖的翻译错误

### ISSUE THREAD

**Issue by HSSkyBoy** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#92]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我确定这是对汉化文本内容的建议

### 说说你看到的汉化文本内容？

![Screenshot_20231003_133112_com vrelnir DegreesOfLewdityWE chsmods_edit_136394748261999](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/122550437/b5a2a698-7011-49f4-849a-70ea7162a327)

[存檔代碼.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12788904/default.txt)

### 有什么好的想法？

詢問應該改為給予

**Comment by NumberSir** [comment]
已修改，请等待新版本发布。
