### ISSUE TITLE
無法使用鏡子書寫

### ISSUE THREAD

**Issue by Gularo** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#93]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

無法使用鏡子的書寫功能

### 存档 / 代码

0.4.1.7-chs-alpha1.7.1 Error (:: Mirror): <<mirrorDisplay>>: cannot execute widget: 0.4.1.7-chs-alpha1.7.1 Error (:: Mirror): <<mirrorSkin>>: cannot execute widget: 0.4.1.7-chs-alpha1.7.1 Error (:: Mirror): <<set>>: bad evaluation: Cannot set properties of undefined (setting '黑狼的婊子')
<<mirrorDisplay>>

### 截图

![1696348722512](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/33481209/c5486550-8f62-4ddc-891d-22fbf5255908)

**Comment by NumberSir** [comment]
同 [@issue/88](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/issues/88)，已修复，请等待新版本发布。
