### ISSUE TITLE
学校蠕虫战斗漏翻

### ISSUE THREAD

**Issue by XyMinxin** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#94]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

学校蠕虫战斗漏翻

### 存档 / 代码

我喜欢 那些纷纷攘攘的蠕虫 wiggling 在你的小穴上面!
我喜欢 那些纷纷攘攘的蠕虫 wiggling 在你身体里面!
我喜欢 那些纷纷攘攘的蠕虫 wiggling 在你的软弹的屁股里面!

### 截图

![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/100689349/19e12770-9296-487a-a5f2-0752684bf2a9)

**Comment by NumberSir** [comment]
已修复，请等待新版本发布。
