### ISSUE TITLE
罗宾变装任务线报错

### ISSUE THREAD

**Issue by 4567569** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#95]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

![Screenshot_20231004_153941](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/146926422/da8b07ca-91df-4c67-9c1d-e1d7aa5b7490)
罗宾变装任务线的周末前往海滩帮助卖柠檬水部分，在遇到难缠的顾客选择干涉时报错。游戏为发送前最新的0.4.1.7chs1.7.1版本。

### 存档 / 代码

[存档.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12800846/default.txt)

### 截图

![Screenshot_20231004_153941](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/146926422/d6838143-8b9e-4e8b-96ef-5b515d6def4f)

### 还有别的吗？

上传的存档打开直接选择干涉即可出现报错提示
[存档2.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12800924/2.txt)
存档2为此日开始时的起床时的存档，供测试。

**Comment by NumberSir** [comment]
已修复，请等待新版本发布。
