### ISSUE TITLE
Windows Defender报毒dol-0.4.1.7-chs-alpha1.7.1.apk

### ISSUE THREAD

**Issue by kusadact** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#96]
### 说说你遇到的问题？

在github上下载(dol-0.4.1.7-chs-alpha1.7.1.apk)文件会导致Windows Defender报毒，并清理掉
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/96968352/de75da5f-5868-44f7-993a-bb1a587e23f9)
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/96968352/09fe6255-87dc-487d-896a-0ac400544bac)
使用浏览器:edge 117.0.2045.47
操作系统:Windows 10 22H2

**Comment by NumberSir** [comment]
![image](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/52584526/60a8d949-3f40-4095-9b6a-dcdcb3e5ec7e)

善用搜索引擎。

**Comment by kusadact** [comment]
呃，我想表达的是这个安装包会报毒的问题，而不因为这个Windows Defender报毒而导致无法下载的问题

**Comment by xiaoweiXX** [comment]
一般汉化版或者破解版多多少少都会报毒，要不你下个英文原版试试还报不报毒（英文原版还报毒也说明不了什么，小游戏或者个人攒出来的软件报毒概率挺大）
