### ISSUE TITLE
1.7.1幽灵部分漏翻

### ISSUE THREAD

**Issue by sgsfz** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#97]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如图

### 存档 / 代码

[degrees-of-lewdity-foobar-20231005-124221.save.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12812353/degrees-of-lewdity-foobar-20231005-124221.save.txt)

### 截图

![dol1](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/147022009/bf4a0acc-2fb8-4564-8adb-e818cb4d29ff)
上面这个是触发场景，存档选哪个都一样
![dol2](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/147022009/40fbb28b-c21b-4ef0-8f42-4d7616a3f755)

**Comment by NumberSir** [comment]
已修复，请等待新版本发布。
