### ISSUE TITLE
关于 0.4.1.7-chs-alpha1.3.0 版本往上，在安卓手机上无法启动游戏的问题

### ISSUE THREAD

**Issue by Meow0x7E** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#98]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

当我尝试将版本 [0.4.1.7-chs-alpha1.3.0](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/releases/tag/0.4.1.7-chs-alpha1.3.0) 更新到 [v0.4.1.7-chs-alpha1.7.1](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/releases/tag/v0.4.1.7-chs-alpha1.7.1) 后游戏无法正常启动，会产生大量报错信息。将游戏卸载后重新安装无法解决。
我的设备可运行的版本是 [0.4.1.7-chs-alpha1.3.0](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/releases/tag/0.4.1.7-chs-alpha1.3.0) 以及更早版本。[v0.4.1.7-chs-alpha1.4.1](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/releases/tag/v0.4.1.7-chs-alpha1.4.1) 到 [v0.4.1.7-chs-alpha1.7.1](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/releases/tag/v0.4.1.7-chs-alpha1.7.1) 均无法运行。

设备信息:

```
设备型号: ASK-AL00x
版本号: 9.1.1.212(C00E112R6P1)
                    GPU Turbo
EMUI 版本: 9.1.1
Andorid 版本: 9
```

详细报错信息:

```
Error: <<print>>: bad evaluation: StartConfig is not defined
<<print StartConfig.version>>
```

```
Error: <<if>>: bad conditional expression in <<if>> clause: StartConfig is not defined
<<if StartConfig.versionName>> <<print StartConfig.versionName>><</if>>
```

```
Error: <<if>>: bad conditional expression in <<if>> clause: StartConfig is not defined
<<if StartConfig.sneaky>> SNEAKY<</if>>
```

```
Error: <<print>>: bad evaluation: StartConfig is not defined
<<print StartConfig.version.slice(1)>>
```

```
Error: <<set>>: bad evaluation: StartConfig is not defined
<<set l10nStrings.errorTitle = StartConfig.version + " Error" + ($passage ? ` (:: ${$passage})` : "")>>
```

```
Error: <<set>>: bad evaluation: Time is not defined
<<set Time.set()>>
```

```
Error: <<gameStartOnly>>: errors within widget code (Error: <<set>>: bad evaluation: Time is not defined; Error: <<if>>: bad conditional expression in <<if>> clause: StartConfig is not defined; Error: <<if>>: bad conditional expression in <<if>> clause: StartConfig is not defined; Error: <<set>>: bad evaluation: StartConfig is not defined; Error: <<set>>: bad evaluation: StartConfig is not defined; Error: <<npcNamed>>: error within widget code (Error: <<generateNPCNameHairAndEyeColors>>: errors within widget code (Error: <<set>>: bad evaluation: State is not defined; Error: <<set>>: bad evaluation: State is not defined; Error: <<set>>: bad evaluation: State is not defined; Error: <<set>>: bad evaluation: State is not defined; Error: <<set>>: bad evaluation: State is not defined; Error: <<set>>: bad evaluation: State is not defined; Error: <<set>>: bad evaluation: State is not defined; Error: <<set>>: bad evaluation: State is not defined; Error: <<set>>: bad evaluation: State is not defined; Error: <<set>>: bad evaluation: State is not defined; Error: <<set>>: bad evaluation: State is not defined; Error: <<set>>: bad evaluation: State is not defined; Error: <<set>>: bad evaluation: State is not defined; Error: <<set>>: bad evaluation: State is not defined; Error: <<set>>: bad evaluation: State is not defined; Error: <<set>>: bad evaluation: State is not defined; Error: <<set>>: bad evaluation: State is not defined; Error: <<set>>: bad evaluation: State is not defined; Error: <<set>>: bad evaluation: State is not defined; Error: <<set>>: bad evaluation: State is not defined; Error: <<set>>: bad evaluation: State is not defined; Error: <<set>>: bad evaluation: State is not defined; Error: <<set>>: bad evaluation: State is not defined; Error: <<set>>: bad evaluation: State is not defined; Error: <<set>>: bad evaluation: State is not defined; Error: <<set>>: bad evaluation: State is not defined; Error: <<set>>: bad evaluation: State is not defined; Error: <<set>>: bad evaluation: State is not defined; Error: <<set>>: bad evaluation: State is not defined; Error: <<set>>: bad evaluation: State is not defined; Error: <<set>>: bad evaluation: State is not defined; Error: <<set>>: bad evaluation: State is not defined; Error: <<set>>: bad evaluation: State is not defined; Error: <<set>>: bad evaluation: State is not defined)); Error: <<clothinginit>>: error within widget code (Error: <<clothing_arrays>>: errors within widget code (Error: <<script>>: bad evaluation: V is not defined; Error: macro <<wardrobesUpdate>> does not exist)); Error: macro <<skinColorInit>> does not exist; Error: <<set>>: bad evaluation: Cannot read property 'neck' of undefined; Error: <<updateFeats>>: errors within widget code (Error: <<set>>: bad evaluation: Cannot convert undefined or null to object; Error: <<for>>: bad conditional expression: Cannot read property 'length' of undefined); Error: <<setupFeats>>: error within widget code (Error: <<set>>: bad evaluation: Cannot read property 'Broodmother Host' of undefined); Error: <<run>>: bad evaluation: window.createInventoryObject is not a function)
<<gameStartOnly>>
```

```
Error: <<initsettings>>: error within widget code (Error: macro <<startingPlayerImageReset>> does not exist)
<<initsettings>>
```

```
Error: <<settingsStart>>: error within widget code (Error: macro <<updatehistorycontrols>> does not exist)
<<settingsStart>>
```

### 存档 / 代码

[degrees-of-lewdity-save0-20231005-201605.txt](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/files/12819376/degrees-of-lewdity-save0-20231005-201605.txt)

### 截图

![Screenshot_20231005_214033_com vrelnir DegreesOfLewdityWE](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/133293581/d08bd500-c97c-4dcc-b3a1-f8a69d2bf9ce)
![Screenshot_20231005_214037_com vrelnir DegreesOfLewdityWE](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/133293581/c13178ca-33d6-44af-baf5-cff6bad5a73c)
![Screenshot_20231005_214044_com vrelnir DegreesOfLewdityWE](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/133293581/a3d5840c-854d-4ab5-8883-3f7fba5a7b52)
![Screenshot_20231005_214108_com vrelnir DegreesOfLewdityWE](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/133293581/73fcd9bb-5e46-46ff-b245-bacb6e9b1699)

**Comment by NumberSir** [comment]
请更新手机的 webview2 后重试

**Comment by Meow0x7E** [comment]
无法在系统应用商店中找到 `Huawei WebView` 并更新。从 Google Play 中安装了 `Android System WebView` 后无法在开发者设置中的 `WebView 实现 `中找到对应选项。请问还有没有什么其他办法可以解决这个问题？

![Screenshot_20231006_190530_com android settings](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/133293581/0a64e3c4-337b-4620-a501-d53d620e8c81)

![Screenshot_20231006_190409_com android settings](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/133293581/1b7a7df5-d02c-4139-897a-722a99c874bb)

![Screenshot_20231006_190344_com android settings](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/133293581/b420cf4e-73c3-4ccf-aba1-a7df7f522dfa)

**Comment by Khaos423** [comment]
cv1172431

**Comment by Khaos423** [comment]
试试3.0.1吧

**Comment by Meow0x7E** [comment]
本来是还准备问一下侧边栏错位问题的。现在一想可能也是低版本WebView的锅。有个解决方法就是缩放到50%。缺点是触控无法更精确的点击。只能是插键盘解决

![Screenshot_20231007_083300_com vrelnir DegreesOfLewdityWE](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/133293581/48baea99-7c0a-4183-8be7-7e7b5273fdfd)

**Comment by Meow0x7E** [comment]
更新至 [v0.4.2.6-chs-alpha3.0.1](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/releases/tag/v0.4.2.6-chs-alpha3.0.1) 后问题解决

**Comment by Meow0x7E** [comment]
更新至 [v0.4.2.6-chs-alpha3.0.1](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/releases/tag/v0.4.2.6-chs-alpha3.0.1) 后问题解决

**Comment by Meow0x7E** [comment]
现在我写了一个教程，以帮助和我同样遇到WebView版本过低且无法更新WebView的人

[Run_Degrees_of_Lewdly_distributed_in_zip_format_on_your_Android_phone](https://github.com/Meow0x7E/Run_Degrees_of_Lewdly_distributed_in_zip_format_on_your_Android_phone)

**Comment by HSSkyBoy** [comment]
> 无法在系统应用商店中找到 `Huawei WebView` 并更新。从 Google Play 中安装了 `Android System WebView` 后无法在开发者设置中的 `WebView 实现` 中找到对应选项。请问还有没有什么其他办法可以解决这个问题？
> 
> ![Screenshot_20231006_190530_com android settings](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/133293581/0a64e3c4-337b-4620-a501-d53d620e8c81)
> 
> ![Screenshot_20231006_190409_com android settings](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/133293581/1b7a7df5-d02c-4139-897a-722a99c874bb)
> 
> ![Screenshot_20231006_190344_com android settings](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/133293581/b420cf4e-73c3-4ccf-aba1-a7df7f522dfa)
> 

您的设备可能有点确实太老了，我可以提供一下我这边的新版，您现在还需要吗？

**Comment by Meow0x7E** [comment]
> > 无法在系统应用商店中找到  并更新。从 Google Play 中安装了 后无法在开发者设置中的 中找到对应选项。请问还有没有什么其他办法可以解决这个问题？`Huawei WebView``Android System WebView``WebView 实现`
> > ![Screenshot_20231006_190530_com Android 设置](https://private-user-images.githubusercontent.com/133293581/273190454-0a64e3c4-337b-4620-a501-d53d620e8c81.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1Njc0NzQsIm5iZiI6MTcxNTU2NzE3NCwicGF0aCI6Ii8xMzMyOTM1ODEvMjczMTkwNDU0LTBhNjRlM2M0LTMzN2ItNDYyMC1hNTAxLWQ1M2Q2MjBlOGM4MS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QwMjI2MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNGQzZWY1ZmNmZjdhOWI5OTFlNWY2NzhkZDg3Zjg4ZTM0NGM2ZjhhODFhYzYwNmExODNmOTAwNmQyMWM3N2MwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.e1h-dLunpMe1D-QVgcDADTQhu_DU1bqtIO0PEyGSekU)
> 
> 您的设备可能有点确实太老了，我可以提供一下我这边的新版，您现在还需要吗？![Screenshot_20240512_143648_com.android.settings.jpg](https://private-user-images.githubusercontent.com/122550437/329830609-8b284d50-801a-4ed7-941a-6aad4215b6ef.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1Njc0NzQsIm5iZiI6MTcxNTU2NzE3NCwicGF0aCI6Ii8xMjI1NTA0MzcvMzI5ODMwNjA5LThiMjg0ZDUwLTgwMWEtNGVkNy05NDFhLTZhYWQ0MjE1YjZlZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QwMjI2MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OTA1YzJmMDA5M2QzY2M1Mjg1NjIxODA4ZTBiZWIzYjQzNTcyMjVjNGI0ZjY2Zjk5ZGI4MzBjZDE0MzZiOThmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.t27xCV65WP_MRuzZ0HqqdFK1V-Qi2k63aAyuvWYoBaA)

谢谢，但我现在已经不需要了，我使用自带高版本webview的第三方浏览器解决了这个问题，我唯一要做的就是在开始游戏前启动一个本地的web服务端来让我可以通过这个第三方浏览器访问游戏的html文件
