### ISSUE TITLE
下午兩點在學校上到科學課而不是游泳課

### ISSUE THREAD

**Issue by IzIzuu** [Eltirosto/Degrees-of-Lewdity-Chinese-Localization#99]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新发布版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

0.4.2.6-chs-alpha3.0.0版本中，在下午兩點的游泳課，自慰雙手撫摸胸部按了“迎來高潮”按鍵三次後，就突然開始上起了科學課，直到14:59。走出教室還會有上游泳課要遲到了的提示。

### 存档 / 代码

(content://org.telegram.messenger.provider/media/Android/data/org.telegram.messenger/files/Telegram/Telegram%20Documents/5_6125185764293610813.txt) 

### 截图

![IMG_20231006_220012_862](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/147172397/e08df334-5031-46b8-b0df-bfd14c927975)
![IMG_20231006_222234_034](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/147172397/c451251f-31b0-4801-93af-acfb83a1c3d1)
![IMG_20231006_222235_745](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/147172397/6a2212a6-845f-4cea-bf42-0cdec0ed7d7c)
![IMG_20231006_222250_124](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/147172397/ac3d5729-f28a-434a-9567-65124d12ceac)

### 还有别的吗？

沒有

**Comment by NumberSir** [comment]
存档没上传成功，请重新上传

**Comment by NumberSir** [comment]
已修复，请等待新版本发布

**Comment by zmh007007** [comment]
求修复一下，叫悉尼摘掉贞操锁的时候有bug
![Uploading Screenshot_20231007_185008_com.vrelnir.DegreesOfLewdityWE.jpg…]()

**Comment by zmh007007** [comment]
![Screenshot_20231007_185008_com vrelnir DegreesOfLewdityWE](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/assets/147246779/d5c38b12-6912-41ed-aef7-9c0ebfac220a)
